## alarabia

In [643]:
import pickle 
import os

In [644]:
os.listdir('alarabya_pkl')

['alarabya_abha.pkl',
 'alarabya_arar.pkl',
 'alarabya_buraidah.pkl',
 'alarabya_dammam.pkl',
 'alarabya_hail.pkl',
 'alarabya_hfouf.pkl',
 'alarabya_jazan.pkl',
 'alarabya_jeddah.pkl',
 'alarabya_jubil.pkl',
 'alarabya_khamis_mushiat.pkl',
 'alarabya_khobar.pkl',
 'alarabya_madina.pkl',
 'alarabya_mekka.pkl',
 'alarabya_najran.pkl',
 'alarabya_riyadh.pkl',
 'alarabya_tabouk.pkl',
 'alarabya_taif.pkl',
 'alarabya_tymaa.pkl',
 'alarabya_yanbu.pkl']

In [645]:
alarabya_list=pickle.load(open('alarabya_pkl\\alarabya_tabouk.pkl','rb'))
alarabya_list = [dictionary for dictionary in alarabya_list if 'الإسكندرية' not in dictionary['location'] and 'القاهرة' not in dictionary['location']]
print(len(alarabya_list))
alarabya_list

42

[{'store_name': 'العربية للعود |Arabian Oud',
  'rating': '4.4 نجمة ',
  'location': '3585، مروج الأمير، تبوك 47315، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.5 نجمة ',
  'location': 'طريق الملك فهد، سلطانة، تبوك 47312، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'العليا، تبوك 47911، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '4.0 نجمة ',
  'location': 'الامير عبدالمجيد بن عبدالعزيز، المروج ب،، تبوك 47312، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.4 نجمة ',
  'location': 'علي بن ابي طالب، السعادة، تبوك 47914، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'KGAB7336، 7336 خديجة بنت خويلد، 5635، الصفا، تبوك 47919، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.4 نجمة ',
  'location': 'طريق الملك فهد، العليا، تبوك 47911، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود بالشارع العام (Arabianoud Tabuk )',
  'rating': '4.4 نجمة ',
  'location': '3673 الامام محمد بن عبدالوهاب، المنشية القديمة، تبوك 47914، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.3 نجمة ',
  'location': 'عمر بن الخطاب، الصالحية، تبوك 47913، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'المصيف، المروج،،, تبوك 47321، المملكة العربية السعودية'},
 {'store_name': '129 العربية للعود | Arabian Oud',
  'rating': '3.9 نجمة ',
  'location': '3361 طيبة، العزيزية القديمة، تبوك 47912، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود فرع 102',
  'rating': '3.9 نجمة ',
  'location': '3593 جادة الامير فهد بن سلطان،، العوايشة، تبوك 47914، المملكة العربية السعودية'},
 {'store_name': '1225 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': 'شارع الخرج - مقابل رعد الشمال للرحلات، تبوك, تبوك المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '4.2 نجمة ',
  'location': 'طريق الملك فيصل، مروج الأمير، تبوك 47315، المملكة العربية السعودية'},
 {'store_name': '436 العربية للعود | Arabian Oud',
  'rating': '3.3 نجمة ',
  'location': '7619 ابي بكر الصديق، المروج،، تبوك 47312، المملكة العربية السعودية'},
 {'store_name': '706 العربية للعود | Arabian Oud',
  'rating': '4.0 نجمة ',
  'location': 'عمر بن الخطاب، العزيزية القديمة، تبوك 47912، المملكة العربية السعودية'},
 {'store_name': '606 العربية للعود | Arabian Oud',
  'rating': '4.0 نجمة ',
  'location': '7222 طريق الملك خالد، حي الفيصلية الجنوبية, KGAC3448، 3448, تبوك 47911، المملكة العربية السعودية'},
 {'store_name': 'الدخيل للعود',
  'rating': '4.3 نجمة ',
  'location': 'المميز، العليا، تبوك جوارالبلح، تبوك 47911، المملكة العربية السعودية'},
 {'store_name': 'الماجد للعود',
  'rating': '3.8 نجمة ',
  'location': 'بارك مول, مروج الأمير، تبوك 47315، المملكة العربية السعودية'},
 {'store_name': 'درعه DERAAH',
  'rating': '4.0 نجمة ',
  'location': '9G6F+H77، طريق الملك عبدالله، KGAJ4288، 4288 طريق الملك عبدالله، 7742، حي البوادي، تبوك 47917، تبوك المملكة العربية السعودية'},
 {'store_name': 'العربية للعود Arabian Oud',
  'rating': '4.4 نجمة ',
  'location': 'Juhaina Sq Mall of Arabia, Unit No. H96, محافظة الجيزة 12573'},
 {'store_name': 'العربيه للعود',
  'rating': '3.4 نجمة ',
  'location': 'طارق بن زياد، الرزيقية، العلا 43561، المملكة العربية السعودية'},
 {'store_name': 'Arabian oud',
  'rating': '4.7 نجمة ',
  'location': 'MALL OF EGYPT, قسم أول 6 أكتوبر، محافظة الجيزة 3294001'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'طريق الملك سعود، السوق القديم، تبوك، دومة الجندل 74632، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': '88PP+38F، السديرية، القريات 77481، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'الصمدة، ضبا 49311، المملكة العربية السعودية'},
 {'store_name': '535 العربية للعود | Arabian Oud',
  'rating': '3.7 نجمة ',
  'location': 'King Fahd Bin Abdulaziz rd، الظهرة، حقل 49938، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '5.0 نجمة ',
  'location': '88HV+C9P، الحميدية، القريات 77453، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '4.1 نجمة ',
  'location': 'Mecca Mall, Abdullah Al Dawoud St 20، عمّان، الأردن'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'الجوف بلازا .. 6902 طريق الملك سعود سكاكا السعودية،، سكاكا المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'العزيزية، الوجه 48721، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'العزيزية، العلا 43511، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود Arabia Oud',
  'rating': '4.4 نجمة ',
  'location': 'GVP8+C47، إربد، الأردن'},
 {'store_name': 'العربية للعود فرع التحلية',
  'rating': '3.4 نجمة ',
  'location': 'طريق الامير محمد بن عبدالعزيز، العريض، المدينة المنورة 42314، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.6 نجمة ',
  'location': 'المطر، 72341،، سكاكا المملكة العربية السعودية'},
 {'store_name': '323 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': 'King Fahd Rd, الصخيرات، العلا 43512، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.7 نجمة ',
  'location': '7477 طريق الملك عبدالله بن عبدالعزيز شمال, التاخي، ينبع 46429، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'شارع الاندلس، طبرجل 74765، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود ام اذينه',
  'rating': '5.0 نجمة ',
  'location': 'ش. شط العرب 16، عمّان، الأردن'},
 {'store_name': '548 العربية للعود | Arabian Oud',
  'rating': '4.2 نجمة ',
  'location': 'Sakakah Road Nayomi Al Jouf Plaza، سكاكا 72341، المملكة العربية السعودية'},
 {'store_name': '825 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': 'طريق الملك فيصل، الخالدية، القريات 77453، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'طريق الملك عبدالعزيز، الحي الإداري، سكاكا 72341، المملكة العربية السعودية'}]

In [646]:
alarabya_list_1=pickle.load(open('alarabya_pkl\\alarabya_tymaa.pkl','rb'))
alarabya_list_1 = [dictionary for dictionary in alarabya_list_1 if 'الإسكندرية' not in dictionary['location'] and 'القاهرة' not in dictionary['location']]
print(len(alarabya_list_1))

alarabya_list_1

113

[{'store_name': 'العربية للعود Arabian Oud',
  'rating': '4.4 نجمة ',
  'location': 'Juhaina Sq Mall of Arabia, Unit No. H96, محافظة الجيزة 12573'},
 {'store_name': 'العربيه للعود',
  'rating': '3.4 نجمة ',
  'location': 'طارق بن زياد، الرزيقية، العلا 43561، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود |Arabian Oud',
  'rating': '4.4 نجمة ',
  'location': '3585، مروج الأمير، تبوك 47315، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'العزيزية، العلا 43511، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'المصيف، المروج،،, تبوك 47321، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '4.2 نجمة ',
  'location': '2791 أبو أيوب الأنصاري، بني خدرة، المدينة المنورة 42311 6233،، بني خدرة، 42311،، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'KGAB7336، 7336 خديجة بنت خويلد، 5635، الصفا، تبوك 47919، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '4.2 نجمة ',
  'location': 'طريق الملك فيصل، مروج الأمير، تبوك 47315، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'طريق الملك سعود، السوق القديم، تبوك، دومة الجندل 74632، المملكة العربية السعودية'},
 {'store_name': '323 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': 'King Fahd Rd, الصخيرات، العلا 43512، المملكة العربية السعودية'},
 {'store_name': '1225 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': 'شارع الخرج - مقابل رعد الشمال للرحلات، تبوك, تبوك المملكة العربية السعودية'},
 {'store_name': '51 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': 'برزان، حائل 55428، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود بالشارع العام (Arabianoud Tabuk )',
  'rating': '4.4 نجمة ',
  'location': '3673 الامام محمد بن عبدالوهاب، المنشية القديمة، تبوك 47914، المملكة العربية السعودية'},
 {'store_name': '706 العربية للعود | Arabian Oud',
  'rating': '4.0 نجمة ',
  'location': 'عمر بن الخطاب، العزيزية القديمة، تبوك 47912، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '4.1 نجمة ',
  'location': 'طريق الامير عبداالمجيد بن العزيز المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '4.0 نجمة ',
  'location': 'الامير عبدالمجيد بن عبدالعزيز، المروج ب،، تبوك 47312، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'العليا، تبوك 47911، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.4 نجمة ',
  'location': 'علي بن ابي طالب، السعادة، تبوك 47914، المملكة العربية السعودية'},
 {'store_name': '942 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': 'ممر مشاة، بضاعة، المدينة المنورة 42311، المملكة العربية السعودية'},
 {'store_name': 'Arabian oud',
  'rating': '4.7 نجمة ',
  'location': 'MALL OF EGYPT, قسم أول 6 أكتوبر، محافظة الجيزة 3294001'},
 {'store_name': 'العربية للعود فرع التحلية',
  'rating': '3.4 نجمة ',
  'location': 'طريق الامير محمد بن عبدالعزيز، العريض، المدينة المنورة 42314، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'الروضة، خيبر 43488، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.5 نجمة ',
  'location': 'طريق الملك فهد، سلطانة، تبوك 47312، المملكة العربية السعودية'},
 {'store_name': '606 العربية للعود | Arabian Oud',
  'rating': '4.0 نجمة ',
  'location': '7222 طريق الملك خالد، حي الفيصلية الجنوبية, KGAC3448، 3448, تبوك 47911، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'العزيزية، الوجه 48721، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود فرع 102',
  'rating': '3.9 نجمة ',
  'location': '3593 جادة الامير فهد بن سلطان،، العوايشة، تبوك 47914، المملكة العربية السعودية'},
 {'store_name': '129 العربية للعود | Arabian Oud',
  'rating': '3.9 نجمة ',
  'location': '3361 طيبة، العزيزية القديمة، تبوك 47912، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.4 نجمة ',
  'location': 'طريق الملك فهد، العليا، تبوك 47911، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.6 نجمة ',
  'location': 'المطر، 72341،، سكاكا المملكة العربية السعودية'},
 {'store_name': '436 العربية للعود | Arabian Oud',
  'rating': '3.3 نجمة ',
  'location': '7619 ابي بكر الصديق، المروج،، تبوك 47312، المملكة العربية السعودية'},
 {'store_name': '57 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': '6459 باب الصفاقات، برزان، حائل 55428، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'الصمدة، ضبا 49311، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.3 نجمة ',
  'location': 'عمر بن الخطاب، الصالحية، تبوك 47913، المملكة العربية السعودية'},
 {'store_name': '659 العربية للعود | Arabian Oud',
  'rating': '4.3 نجمة ',
  'location': 'ممر مشاة، بضاعة، المدينة المنورة 42311، المملكة العربية السعودية'},
 {'store_name': '548 العربية للعود | Arabian Oud',
  'rating': '4.2 نجمة ',
  'location': 'Sakakah Road Nayomi Al Jouf Plaza، سكاكا 72341، المملكة العربية السعودية'},
 {'store_name': '257 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': 'سعد بن معاذ، بضاعة، المدينة المنورة 42311، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'طريق الملك عبدالعزيز، الحي الإداري، سكاكا 72341، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.4 نجمة ',
  'location': 'شارع الحسن بن عبدالعزيز، العزيزية، المدينة المنورة 42377، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'النقرة، حائل 55431، المملكة العربية السعودية'},
 {'store_name': '535 العربية للعود | Arabian Oud',
  'rating': '3.7 نجمة ',
  'location': 'King Fahd Bin Abdulaziz rd، الظهرة، حقل 49938، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': '88PP+38F، السديرية، القريات 77481، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'الامام البخاري، الدفاع، المدينة المنورة 42377، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'طريق الملك عبدالعزيز، برزان، حائل 55428، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'الامام البخاري، الدفاع، المدينة المنورة 42374، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '5.0 نجمة ',
  'location': '88HV+C9P، الحميدية، القريات 77453، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'شارع الاندلس، طبرجل 74765، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'طريق سلطانة، الراية، المدينة المنورة 42312، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': '4651، المنتزه الشرقي،، حائل 55428، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.6 نجمة ',
  'location': 'الراشد ميغا مول، شظاة، المدينة المنورة 42361، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'حي, الطريق العام, السويفلة، حائل 55481، المملكة العربية السعودية'},
 {'store_name': '503 العربية للعود | Arabian Oud',
  'rating': '4.7 نجمة ',
  'location': '8030، Al Henakiyah 42639،، الحناكية 42639، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': '3460 طريق الامير محمد بن عبدالعزيز،، 7210 Prince Mohammed Bin Abdulaziz St، المدينة المنورة 42314، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'المبعوث، الأمير مقرن ،، المدينة المنورة 42362، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'FM2H+X5، مذينب، المدينة المنورة 42364، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.0 نجمة ',
  'location': 'المنتزه الغربي، حائل 55427، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'طريق الأمير نايف بن عبدالعزيز، البركة، المدينة المنورة 42332، المملكة العربية السعودية'},
 {'store_name': '58 العربية للعود | Arabian Oud',
  'rating': '4.0 نجمة ',
  'location': '7673 الامير سلطان بن عبدالعزيز، 3515، المطار، حائل 55421، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'الامير عبدالمجيد بن عبدالعزيز، الشريبات، المدينة المنورة 42317، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.7 نجمة ',
  'location': 'الحديقة، المدينة المنورة 42383، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.6 نجمة ',
  'location': 'طريق صلاح الدين الايوبي، شوران، المدينة المنورة 42386، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'الجوف بلازا .. 6902 طريق الملك سعود سكاكا السعودية،، سكاكا المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': '2418 طريق سلطانة، بئر عثمان، المدينة المنورة 42331، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'القصواء، المدينة المنورة 42391، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'طريق قباء، الجمعة، المدينة المنورة 42315، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.5 نجمة ',
  'location': 'العباس بن عبادة، القصواء، المدينة المنورة 42391، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': '، حي، الخالدية، طريق الأمير محمد بن عبد العزيز، المدينة المنورة 42317، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'طريق الأمير عبد المجيد، الجمعة، المدينة المنورة 42316، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '4.0 نجمة ',
  'location': 'الحدائق، ينبع 46424، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'العيون، المدينة المنورة 42331، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'الزبارة، حائل 55425، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.7 نجمة ',
  'location': '7477 طريق الملك عبدالله بن عبدالعزيز شمال, التاخي، ينبع 46429، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '4.4 نجمة ',
  'location': 'مخطط الرواف 5070, بريدة 52379، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': '7337 الامير سلطان فرعي، حي المحمدية، جدة 23625 2115، المملكة العربية السعودية'},
 {'store_name': '783 العربية للعود | Arabian Oud',
  'rating': '3.0 نجمة ',
  'location': '6230 أبو أيوب الأنصاري، بني خدرة، 2665, المدينة المنورة 42311، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'طريق عثمان بن عفان، الصفراء، بريدة 52381، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'طريق الملك عبدالله، الصفراء، بريدة 52383، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'المشهد، ينبع 46423، المملكة العربية السعودية'},
 {'store_name': '159 العربية للعود | Arabian Oud',
  'rating': '1.0 نجمة ',
  'location': 'مصعب بن عمير، بضاعة، المدينة المنورة 42311، المملكة العربية السعودية'},
 {'store_name': '825 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': 'طريق الملك فيصل، الخالدية، القريات 77453، المملكة العربية السعودية'},
 {'store_name': '734 العربية للعود | Arabian Oud',
  'rating': '4.3 نجمة ',
  'location': 'الحرم North، المدينة المنورة 42311، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'الصفراء، بريدة 52382، المملكة العربية السعودية'},
 {'store_name': '905 العربية للعود | Arabian Oud',
  'rating': '4.2 نجمة ',
  'location': 'الشارع العام سوق الذهب، الحائط 57363، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'جوهرة، عرعر 73551، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'طريق الملك عبدالعزيز، عقلة الصقور 54714، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'طريق الأمير محمد بن عبدالعزيز، الروضة، جدة 23431، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.5 نجمة ',
  'location': 'طريق الملك عبدالله، 3363 طريق الملك عبدالله، حي ابرق الرغامة، جدة 22261، 9059، جدة 22261، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'شارع عمر بن سليم، سلطانة، بريدة 52375، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '2.0 نجمة ',
  'location': 'حي, الامير مقرن بن عبد العزيز, المروج، ينبع 46511، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '3.6 نجمة ',
  'location': '7248، 2415 سعود الفيصل، الصفا،، جدة 23451، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.4 نجمة ',
  'location': 'مهد الذهب 44411، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'الحمدانية، جدة 23761، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'العزيزية، طريف 75211، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.5 نجمة ',
  'location': '1, Dana Mall, Gate، ينبع 46435، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'الحمراء، جدة 23323، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': '4049، النازية، بريدة 52359، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'شارع عبدالله سليمان، الفيحاء، جدة 22246، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود Arabain Oud',
  'rating': '4.9 نجمة ',
  'location': 'الفهد، شارع السوق التجاري،، البكيرية 51941، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'Taibah District, جدة 23831، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'طريق الليث الفرعي، القرينية، جدة 22535، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.5 نجمة ',
  'location': 'Ibrahim Al Khalil, St Abraj Al Bait 1، مكة 24231، المملكة العربية السعودية'},
 {'store_name': '973 العربية للعود | Arabian Oud',
  'rating': '4.4 نجمة ',
  'location': 'فرع العربية للعود بالأمير نايف، 0،، حائل المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': '3006 قريش، 6211، حي البوادي، جدة 23531، المملكة العربية السعودية'},
 {'store_name': '853 العربية للعود | Arabian Oud',
  'rating': '4.3 نجمة ',
  'location': 'فرع العربية للعود بصالات النويصر،، شارع الملك خالد، ،، حائل 55424، المملكة العربية السعودية'},
 {'store_name': '1258 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': 'الحرم، المدينة المنورة 42311، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'الصمد، رابغ 25728، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': '6155 ابراهيم الخليل، الشوقية، مكة 24351، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.6 نجمة ',
  'location': 'الشيرمي، البدائع 56352، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.2 نجمة ',
  'location': 'شارع الأمير محمد بن عبدالعزيز، الرحاب، Jarir Mall،، جدة 23345، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': '3811 حراء, AZ Zahra District, جدة 23522، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'الجامعة، مكة 24243، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '1.9 نجمة ',
  'location': 'جراند مول, طريق الملك سعود، النقرة، حائل 55431، المملكة العربية السعودية'},
 {'store_name': '646 العربية للعود | Arabian Oud',
  'rating': '3.8 نجمة ',
  'location': '6793، Al Marwah District، جدة 23545، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'ابو حذيفه بن عتبه، مدائن الفهد، جدة 22337، المملكة العربية السعودية'}]

In [647]:
alarabya_list_2=pickle.load(open('alarabya_pkl\\alarabya_madina.pkl','rb'))
alarabya_list_2 = [dictionary for dictionary in alarabya_list_2 if 'الإسكندرية' not in dictionary['location'] and 'القاهرة' not in dictionary['location']]
print(len(alarabya_list_2))

alarabya_list_2

109

[{'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'الامام البخاري، الدفاع، المدينة المنورة 42377، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'طريق سلطانة، الراية، المدينة المنورة 42312، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': '3460 طريق الامير محمد بن عبدالعزيز،، 7210 Prince Mohammed Bin Abdulaziz St، المدينة المنورة 42314، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.6 نجمة ',
  'location': 'الراشد ميغا مول، شظاة، المدينة المنورة 42361، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': '، حي، الخالدية، طريق الأمير محمد بن عبد العزيز، المدينة المنورة 42317، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'FM2H+X5، مذينب، المدينة المنورة 42364، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'الامام البخاري، الدفاع، المدينة المنورة 42374، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'المبعوث، الأمير مقرن ،، المدينة المنورة 42362، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.4 نجمة ',
  'location': 'شارع الحسن بن عبدالعزيز، العزيزية، المدينة المنورة 42377، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'الامير عبدالمجيد بن عبدالعزيز، الشريبات، المدينة المنورة 42317، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'طريق الأمير نايف بن عبدالعزيز، البركة، المدينة المنورة 42332، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.6 نجمة ',
  'location': 'طريق صلاح الدين الايوبي، شوران، المدينة المنورة 42386، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': '2418 طريق سلطانة، بئر عثمان، المدينة المنورة 42331، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'طريق الأمير عبد المجيد، الجمعة، المدينة المنورة 42316، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود فرع التحلية',
  'rating': '3.4 نجمة ',
  'location': 'طريق الامير محمد بن عبدالعزيز، العريض، المدينة المنورة 42314، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'القصواء، المدينة المنورة 42391، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'طريق قباء، الجمعة، المدينة المنورة 42315، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.7 نجمة ',
  'location': 'الحديقة، المدينة المنورة 42383، المملكة العربية السعودية'},
 {'store_name': '768 العربية للعود | Arabian Oud',
  'rating': '4.6 نجمة ',
  'location': '6927 طريق الملك فهد، بضاعة، المدينة المنورة 42311، المملكة العربية السعودية'},
 {'store_name': '734 العربية للعود | Arabian Oud',
  'rating': '4.3 نجمة ',
  'location': 'الحرم North، المدينة المنورة 42311، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.5 نجمة ',
  'location': 'العباس بن عبادة، القصواء، المدينة المنورة 42391، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '4.1 نجمة ',
  'location': 'طريق الامير عبداالمجيد بن العزيز المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'العيون، المدينة المنورة 42331، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '4.2 نجمة ',
  'location': '2791 أبو أيوب الأنصاري، بني خدرة، المدينة المنورة 42311 6233،، بني خدرة، 42311،، المملكة العربية السعودية'},
 {'store_name': '942 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': 'ممر مشاة، بضاعة، المدينة المنورة 42311، المملكة العربية السعودية'},
 {'store_name': '659 العربية للعود | Arabian Oud',
  'rating': '4.3 نجمة ',
  'location': 'ممر مشاة، بضاعة، المدينة المنورة 42311، المملكة العربية السعودية'},
 {'store_name': '630 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': 'طريق الملك عبدالله، شظاة، المدينة المنورة 42361، المملكة العربية السعودية'},
 {'store_name': '158 العربية للعود | Arabian Oud',
  'rating': '4.3 نجمة ',
  'location': 'ممر مشاة، بضاعة، المدينة المنورة 42311، المملكة العربية السعودية'},
 {'store_name': '257 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': 'سعد بن معاذ، بضاعة، المدينة المنورة 42311، المملكة العربية السعودية'},
 {'store_name': '509 العربية للعود | Arabian Oud',
  'rating': '4.0 نجمة ',
  'location': 'طريق قباء، الجمعة، المدينة المنورة 42315، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود فرع المناخة',
  'rating': '3.8 نجمة ',
  'location': 'FJ74+WRC، الحرم، المدينة المنورة 42311، المملكة العربية السعودية'},
 {'store_name': '783 العربية للعود | Arabian Oud',
  'rating': '3.0 نجمة ',
  'location': '6230 أبو أيوب الأنصاري، بني خدرة، 2665, المدينة المنورة 42311، المملكة العربية السعودية'},
 {'store_name': '956 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': '2943، بضاعة، المدينة المنورة 42311، المملكة العربية السعودية'},
 {'store_name': '159 العربية للعود | Arabian Oud',
  'rating': '1.0 نجمة ',
  'location': 'مصعب بن عمير، بضاعة، المدينة المنورة 42311، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '4.1 نجمة ',
  'location': 'مول, الوبرة، طريق الملك عبدالله الفرعي - المنار المملكة العربية السعودية'},
 {'store_name': '1258 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': 'الحرم، المدينة المنورة 42311، المملكة العربية السعودية'},
 {'store_name': 'OudElite - نخبة العود 7509',
  'rating': '4.2 نجمة ',
  'location': 'CHGM+GF، ام قيس بنت محصن، القصواء،، المدينة المنورة 42391، المملكة العربية السعودية'},
 {'store_name': 'الماجد للعود',
  'rating': '4.2 نجمة ',
  'location': 'الامام البخاري، الدفاع،, المدينة المنورة المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.5 نجمة ',
  'location': '1, Dana Mall, Gate، ينبع 46435، المملكة العربية السعودية'},
 {'store_name': 'السامر للعود',
  'rating': '4.0 نجمة ',
  'location': 'اسماء بن عروة، القصواء، المدينة المنورة 42391، المملكة العربية السعودية'},
 {'store_name': 'OudElite - نخبة العود 7637',
  'rating': '3.6 نجمة ',
  'location': 'فندق المجيدي، ممر مشاة، بضاعة، المدينة المنورة 42311، المملكة العربية السعودية'},
 {'store_name': 'الماجد للعود',
  'rating': '4.2 نجمة ',
  'location': 'طريق سلطانة، بئر عثمان، المدينة المنورة 42331، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '4.5 نجمة ',
  'location': 'أبو أيوب الأنصاري، الحرم، المدينة المنورة 42311، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.5 نجمة ',
  'location': 'الشهداء، بدر 46357، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '4.0 نجمة ',
  'location': 'الحدائق، ينبع 46424، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.7 نجمة ',
  'location': '7477 طريق الملك عبدالله بن عبدالعزيز شمال, التاخي، ينبع 46429، المملكة العربية السعودية'},
 {'store_name': 'الدخيل للعود Al-Dakheel Oud',
  'rating': '4.2 نجمة ',
  'location': 'الامام البخاري، الدفاع، المدينة المنورة 42374، المملكة العربية السعودية'},
 {'store_name': 'Dkhoun | دخون',
  'rating': '4.8 نجمة ',
  'location': 'Al Rashid Mega Mall، طريق الملك عبدالله، Al Rashid Mega Mall، المدينة المنورة المملكة العربية السعودية'},
 {'store_name': '581 العربية للعود | Arabian Oud',
  'rating': '4.4 نجمة ',
  'location': 'علي بن أبي طالب، الشربتلي، ينبع 46424، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'المشهد، ينبع 46423، المملكة العربية السعودية'},
 {'store_name': 'الماجد للعود',
  'rating': '4.0 نجمة ',
  'location': '7066 طريق الامير محمد بن عبدالعزيز، العريض، المدينة المنورة 42314، المملكة العربية السعودية'},
 {'store_name': 'Dkhoun | دخون',
  'rating': '4.8 نجمة ',
  'location': '4549 طريق الملك عبدالله الفرعي، Al Manar Mall 8352، المدينة المنورة 42371، المملكة العربية السعودية'},
 {'store_name': 'عبق العود الراقي',
  'rating': '4.8 نجمة ',
  'location': 'قباء النازل، الجمعة، المدينة المنورة 42315، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '2.0 نجمة ',
  'location': 'حي, الامير مقرن بن عبد العزيز, المروج، ينبع 46511، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود Arabian Oud',
  'rating': '4.4 نجمة ',
  'location': 'Juhaina Sq Mall of Arabia, Unit No. H96, محافظة الجيزة 12573'},
 {'store_name': 'Arabian Oud',
  'rating': '4.1 نجمة ',
  'location': 'طريق الملك عبدالعزيز، السلام، املج 48321، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '3.4 نجمة ',
  'location': 'طارق بن زياد، الرزيقية، العلا 43561، المملكة العربية السعودية'},
 {'store_name': '503 العربية للعود | Arabian Oud',
  'rating': '4.7 نجمة ',
  'location': '8030، Al Henakiyah 42639،، الحناكية 42639، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'الروضة، خيبر 43488، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'حمد الجاسر، الروضة، جدة 23434، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.1 نجمة ',
  'location': '3952، 6873 حي، مريخ، جدة 23361، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود Arabia Oud',
  'rating': '4.4 نجمة ',
  'location': 'JDSA8673، 8673 ام القرى، 4142، حي الصفا،، جدة 23456، المملكة العربية السعودية'},
 {'store_name': '882 العربية للعود | Arabian Oud',
  'rating': '4.3 نجمة ',
  'location': '4618، As Sabuh، رابغ 25754، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': '7337 الامير سلطان فرعي، حي المحمدية، جدة 23625 2115، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'الصمد، رابغ 25728، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.5 نجمة ',
  'location': 'طريق سليمان الراجحي، حي القيم الأعلى، الطائف 26551، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.4 نجمة ',
  'location': 'مهد الذهب 44411، المملكة العربية السعودية'},
 {'store_name': '530 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': 'الصمد، رابغ 25728، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.5 نجمة ',
  'location': 'طريق الملك عبدالله، 3363 طريق الملك عبدالله، حي ابرق الرغامة، جدة 22261، 9059، جدة 22261، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'الحمدانية، جدة 23761، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'طريق الأمير محمد بن عبدالعزيز، الروضة، جدة 23431، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'البهجه، مشرفة، جدة 23336، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'الحمراء، جدة 23323، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود Arabian Oud',
  'rating': '4.9 نجمة ',
  'location': 'شارع الدكتور عبدالقادر كوشك، ولي العهد، مكة 24353، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '3.6 نجمة ',
  'location': '7248، 2415 سعود الفيصل، الصفا،، جدة 23451، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'شارع عبدالله سليمان، الفيحاء، جدة 22246، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'Taibah District, جدة 23831، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود الحمدانيه',
  'rating': '4.6 نجمة ',
  'location': 'حي, JGAA4079, 8462 عمرو بن ابي وقاص(رضي الله عن، الحمدانية، 4079, جدة 23761، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'شارع عابر القرات، أبحر الشمالية، جدة 23815، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.5 نجمة ',
  'location': 'Ibrahim Al Khalil, St Abraj Al Bait 1، مكة 24231، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': '6326 طريق الامير متعب بن عبدالعزيز، 3578، حي مشرفة، جدة 23341، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'طريق الملك فهد فرعي، الربوة، جدة 23533، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': '3006 قريش، 6211، حي البوادي، جدة 23531، المملكة العربية السعودية'},
 {'store_name': '698 العربية للعود | Arabian Oud',
  'rating': '4.3 نجمة ',
  'location': 'الحمدانية، جدة 23761، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': '6155 ابراهيم الخليل، الشوقية، مكة 24351، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'الجامعة، مكة 24243، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'ابو حذيفه بن عتبه، مدائن الفهد، جدة 22337، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'ابو حذيفه بن عتبه، مدائن الفهد، جدة 22337، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': '3811 حراء, AZ Zahra District, جدة 23522، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': '8912 قاسم زينة، 4471 قاسم زينة، حي الروضة، جدة 23434، جدة 23434، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'قصر الضيافة، الزهراء، مكة 24221، المملكة العربية السعودية'},
 {'store_name': '949 العربية للعود | Arabian Oud',
  'rating': '4.2 نجمة ',
  'location': 'الفيصلية، الجموم 25335، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'العزيزية، العلا 43511، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'ام القرى، الصفا، جدة 23453، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': '7599 الأمير ماجد، حي العزيزية، 2335، جدة 23342، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.2 نجمة ',
  'location': 'شارع الأمير محمد بن عبدالعزيز، الرحاب، Jarir Mall،، جدة 23345، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.6 نجمة ',
  'location': 'النزهة، جدة 23532، المملكة العربية السعودية'},
 {'store_name': '646 العربية للعود | Arabian Oud',
  'rating': '3.8 نجمة ',
  'location': '6793، Al Marwah District، جدة 23545، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'Fruit Boat Sculpture, شارع حراء، النهضة، جدة 23523، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'قاده الفكر، الرويس، جدة 23215، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'المنار، جدة 23462، المملكة العربية السعودية'},
 {'store_name': '624 العربية للعود | Arabian Oud',
  'rating': '3.4 نجمة ',
  'location': 'الحمدانية، جدة 23761، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'العزيزية، الوجه 48721، المملكة العربية السعودية'},
 {'store_name': '683 العربية للعود | Arabian Oud',
  'rating': '4.7 نجمة ',
  'location': 'طريق الملك عبدالله، الفيحاء، جدة 22251، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'النوارية، مكة 24215، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'طريق الملك فيصل، العدل، مكة 24244، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': '2167 محمد صالح باشراحيل، الراشدية، مكة 24268، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.7 نجمة ',
  'location': 'شارع الحسين السهواجي، الربيع، جدة 23461، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'اسماعيل بن كثير، البساتين، جدة 23719، المملكة العربية السعودية'}]

In [648]:
alarabya_list_3=pickle.load(open('alarabya_pkl\\alarabya_riyadh.pkl','rb'))
alarabya_list_3 = [dictionary for dictionary in alarabya_list_3 if 'الإسكندرية' not in dictionary['location'] and 'القاهرة' not in dictionary['location']]
print(len(alarabya_list_3))

alarabya_list_3

118

[{'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'طريق خريص، الروضة، الرياض 13211، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'طريق الإمام عبدالله بن سعود بن عبدالعزيز الفرعي، اليرموك، الرياض 13243، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '4.0 نجمة ',
  'location': 'الربوة،، الربوة، الرياض 12839، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'طريق أبو عبيدة عامر بن الجراح، حي السلي، السلي، الرياض 14267، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود التخصصي',
  'rating': '4.4 نجمة ',
  'location': '7324 شارع التخصصي، العليا، الرياض 12342، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'طريق الملك عبدالله الفرعي، الحمراء، الرياض 13217، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '3.9 نجمة ',
  'location': 'شارع جرير، الملز، الرياض 12836، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'العربية للعود، شارع عبد الرحمن الغافقي، شارع عبدالرحمن الغافقي، الرياض ،، الرياض المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'طريق أنس ابن مالك، الصحافة، الرياض 13321، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'عائشة بنت أبي بكر، السويدي، السويدي، الرياض 12788، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'اليرموك، الرياض 13251، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'سلمان الفارسي، النهضة،،، النهضة، الرياض 13221، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '4.3 نجمة ',
  'location': 'حي, طريق ابو عبيدة عامر بن الجراح، الفيحاء، الرياض 14254، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.7 نجمة ',
  'location': 'Riyadh Front، مطار الملك خالد الدولي، الرياض 11564، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'طريق الملك فهد، العقيق، الرياض 13515، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.5 نجمة ',
  'location': 'حي, طريق الملك عبدالعزيز، الربيع، الرياض 13316، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.0 نجمة ',
  'location': '2937 طريق الملك عبدالله الفرعي، الورود، الرياض 12253، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': '3427 طريق الخرج، المنصورة، الرياض 12692، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'طريق العروبة، العليا، الرياض 12244، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.4 نجمة ',
  'location': 'Othaim Market, الامير تركي بن عبدالعزيز الثاني، Opposit, الرياض 12282، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'طريق هارون الرشيد، الفيحاء، الرياض 14254، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'طريق الدمام الفرعي، المونسية، الرياض 13246، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'الإمام سعود بن عبد العزيز بن محمد، المغرزات، الرياض المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': '3708 طريق العزيزية الفرعي، العزيزية، 6776 طريق العزيزية،، الرياض 14511، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'Ayyubi Rd, صلاح الدين، Prince Faisal Bin Fahd Stadium, الرياض 12836، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'شارع الترمذي، أسواق العودة، الرياض 14712، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'الخالدية، الدرعية 13713، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.3 نجمة ',
  'location': 'طريق نجم الدين الأيوبي الفرعي، طويق، الرياض 14931، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'شارع التخصصي،، المعذر الشمالي، الرياض 12334، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': '7575 الطريق الدائري الشرقي الفرعي، القدس، الرياض 13214، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': '4239 طريق الملك فهد، العليا، 7062، الرياض 12311، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '5.0 نجمة ',
  'location': '8015 طريق الدمام الفرعي، اليرموك، الرياض 13243، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'شارع الإمام أحمد بن حنبل، النسيم الغربي، الرياض 14233، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'الاسكان، الرياض 14317، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud | العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'VJ3X+6CF، النرجس، الرياض 13333، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'Cenomi Tala Mall، النفل، الرياض 13312، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود arabian oud',
  'rating': '4.4 نجمة ',
  'location': 'كودو, الطريق الدائري الجنوبي الفرعي، الرياض-حى بجوار, الرياض المملكة العربية السعودية'},
 {'store_name': 'العربية للعود والعطور الشرقية',
  'rating': '4.0 نجمة ',
  'location': 'الشفا، الرياض 13781، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'حي, شارع الأمير عبدالعزيز بن مساعد بن جلوي، السليمانية، الرياض 12221، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'الطريق الدائري الغربي الفرعي، ظهرة نمار، الرياض 14924، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'طريق الملك فهد الفرعي، السويدي، الرياض 12791، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'ابن الرطبي، الشفا، الرياض 14721، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '4.0 نجمة ',
  'location': '8538 شارع أبي الأسود الدؤلي، النسيم الشرقي، الرياض 14243، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.6 نجمة ',
  'location': 'عرقة، الرياض 12543، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'طريق سعد بن عبدالرحمن الأول الفرعي، الروابي، الرياض 14216، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': '3516 الوادي, هجرة لبن، الرياض 12936، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.5 نجمة ',
  'location': 'المونسية، الرياض 13253، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'طريق النصر، العزيزية، الرياض 14514، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.4 نجمة ',
  'location': 'الندوة، حي الندوة، الرياض 14814، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.6 نجمة ',
  'location': 'طريق ابي بكر الصديق، النرجس، الرياض 13336، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': '6441 شارع حسان بن ثابت، النسيم الشرقي، الرياض 14241، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.5 نجمة ',
  'location': 'الريان،، الرياض المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'شارع عنيزة، الريان، الرياض 14213، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.6 نجمة ',
  'location': 'حي, الملك عبد العزيز، ذا فيو مول - طريق مكة المكرمة فرعي المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.7 نجمة ',
  'location': 'طريق الثمامة، المونسية، الرياض 13421، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'الملقا, طريق الامام سعود بن فيصل الفرعي المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'طريق عرفات الفرعي، الدار البيضاء، الرياض 14518، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'شارع الأمير بندر بن عبد العزيز، حي النهضة، النهضة، الرياض 13222، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'عبدالرحمن الداخل، طويق، الرياض 14922، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود - الإدارة الإقليمية',
  'rating': '4.4 نجمة ',
  'location': '6579 الطريق الدائري الشمالي الفرعي، النفل، حي, An Nafal، RALA3876، 3876، الرياض 13312، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'شارع العليا، العليا، الرياض 12222، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'اسواق التميمى، شارع خالد بن الوليد، الاندلس، الرياض 13212، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'Al Majd Mall، الربوة، 6838 Eastern Ring Branch Rd، الرياض 12839، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.4 نجمة ',
  'location': 'وادي الصمان، الملك فيصل، الرياض 13215، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.6 نجمة ',
  'location': 'صالح الهاشمي، العقيق، الرياض 13511، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.5 نجمة ',
  'location': 'الحارث بن عبدالله، حي الندوة، الرياض 14813، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'طريق الإمام سعود بن عبدالعزيز بن محمد، النخيل، الرياض 12381، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'طريق الأمير نايف بن عبدالعزيز، الملك فهد، الرياض 12273، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'السويدي العام، سلطانة، الرياض 12777، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'PM9C+XHJ، شارع العليا، الورود، الرياض 12215، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.7 نجمة ',
  'location': 'طريق الملك فهد الفرعي، العليا، المملكة،، الرياض 12214، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': '6426 طريق ابن تيمية، الشفا، الرياض 14713، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود فرع الوادي مخرج ٧',
  'rating': '4.0 نجمة ',
  'location': 'حي, طريق عثمان بن عفان الفرعي، الوادي، الرياض 13313، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '4.2 نجمة ',
  'location': 'الملقا، طريق الامام سعود بن فيصل الفرعي المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'طريق الملك عبدالعزيز، طويق، محافظة المزاحمية 19671، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.7 نجمة ',
  'location': 'طريق المدينة المنورة، ظهرة البديعة، الرياض 12982، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '4.4 نجمة ',
  'location': 'RQAA8666 3801 شبه الجزيرة، السعادة، الرياض 14255، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'المشتل، الحزم، الرياض 14964، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.0 نجمة ',
  'location': 'الاندلس، الرياض 11564، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.4 نجمة ',
  'location': '6774 طريق الأمير محمد بن سلمان بن عبدالعزيز، قرطبة، 3548، الرياض 13247، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'قرطبة، الرياض 13244، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود فرع الازدهار',
  'rating': '3.8 نجمة ',
  'location': 'طريق عثمان بن عفان, حي الازدهار، الرياض 12485، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'طريق المدينة المنورة، العريجاء الوسطى، الرياض 12768، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.5 نجمة ',
  'location': 'ظهرة لبن، الرياض 12411، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': '8077 شارع الإمام أبي حنيفة، العريجاء الغربية، 3129 الامام ابي حنيفة،، الرياض 12966، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'شارع عباس بن قيس، أم الحمام الغربي، الرياض 12322، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'طريق الامام سعود بن عبدالعزيز بن محمد الفرعي، المرسلات، الرياض 12464، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود 23',
  'rating': '4.1 نجمة ',
  'location': '2591 الامام تركي بن عبدالله بن محمد، الديرة، الرياض 12634، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود 4',
  'rating': '3.8 نجمة ',
  'location': '7093، الرياض 12262، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.6 نجمة ',
  'location': '3201 شارع الثميري، الديرة، 3201 شارع الثميري، الديرة 6869، الرياض 12634، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود 359',
  'rating': '4.2 نجمة ',
  'location': 'QPJJ+888، غرناطة، الرياض 13241، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'طريق الأمير محمد بن عبدالعزيز، المعذر الشمالي، الرياض 12332، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود 1091',
  'rating': '4.4 نجمة ',
  'location': '6869 الطريق الدائري الشرقي، الجزيرة، الرياض 14251، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود فرع الدائري الغربي',
  'rating': '4.7 نجمة ',
  'location': 'الطريق الدائري الغربي الفرعي، السويدي الغربي، الرياض 12992، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.5 نجمة ',
  'location': 'RURA7465, 2348 وادي الساحل، 7465, حي, الرمال, الرياض 13263، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود فرع العنود بارك',
  'rating': '4.0 نجمة ',
  'location': 'طريق الحائر, حي العزيزية، الرياض 14515، المملكة العربية السعودية'},
 {'store_name': '746 العربية للعود',
  'rating': '3.7 نجمة ',
  'location': '3243 شارع الطائف، ظهرة لبن، الرياض 13782، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.8 نجمة ',
  'location': '8820 شارع حمزة بن عبدالمطلب، السويدي الغربي، الرياض 12991، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.2 نجمة ',
  'location': 'Souq Hijab، شارع أسامة بن زيد، النسيم الغربي، الرياض 14233، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'RJ6H+XGR، الصحافة، الرياض 13321، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'طريق عثمان بن عفان، النزهة، الرياض 12474، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود فرع الرياض جاليري',
  'rating': '4.3 نجمة ',
  'location': '7639 طريق الملك فهد، حي الملك فهد، الرياض 12262 3168، المملكة العربية السعودية'},
 {'store_name': '672 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': 'Ground Floor, Othaim Mall, طريق خريص، النسيم الشرقي، Gate No 1, الرياض 14241، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود فرع جنى مول',
  'rating': '4.1 نجمة ',
  'location': 'الهفوف، الياسمين، الرياض 13325، المملكة العربية السعودية'},
 {'store_name': '720 العربية للعود | Arabian Oud',
  'rating': '4.0 نجمة ',
  'location': '8346 الترمذي، الشفا، الرياض 14713، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.4 نجمة ',
  'location': 'حي, الحمراء، سينومي الحمراء مول المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.8 نجمة ',
  'location': 'حي, وادي الاعشاب، ديراب، الرياض 14969، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود 18',
  'rating': '5.0 نجمة ',
  'location': 'الملك فهد، الرياض 12261، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود 177',
  'rating': '4.8 نجمة ',
  'location': 'PMM7+CG، الملك فهد، الرياض 12261، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود 680',
  'rating': '5.0 نجمة ',
  'location': 'قرطبة، الرياض 13245، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود 1247',
  'rating': '3.8 نجمة ',
  'location': 'طريق أنس ابن مالك، الملقا، الرياض 13524، المملكة العربية السعودية'},
 {'store_name': '45 العربية للعود | Arabian Oud',
  'rating': '3.4 نجمة ',
  'location': 'Tuwaiq, Unnamed Road، الرياض 14921، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.5 نجمة ',
  'location': 'مطار الملك خالد الدولي، الرياض 13455، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود 15',
  'rating': '5.0 نجمة ',
  'location': 'الامام تركي بن عبدالله بن محمد، الديرة، الرياض 12652، المملكة العربية السعودية'},
 {'store_name': 'مصنع العربية للعود',
  'rating': '3.8 نجمة ',
  'location': '3118، المدينة الصناعية الجديدة، الرياض 14332، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود 1206',
  'rating': '5.0 نجمة ',
  'location': 'طريق السيل الكبير، المهدية، الرياض 13757، المملكة العربية السعودية'},
 {'store_name': '187 العربية للعود | Arabian Oud',
  'rating': '4.0 نجمة ',
  'location': 'زهير بن المسيب، الربوة، الرياض 12839، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود 34',
  'rating': '5.0 نجمة ',
  'location': 'Othaim Market, شارع الامير تركي بن عبدالعزيز الثاني، Opposit, الرياض 12282، المملكة العربية السعودية'}]

In [649]:
alarabya_list_4=pickle.load(open('alarabya_pkl\\alarabya_mekka.pkl','rb'))
alarabya_list_4 = [dictionary for dictionary in alarabya_list_4 if 'الإسكندرية' not in dictionary['location'] and 'القاهرة' not in dictionary['location']]
print(len(alarabya_list_4))

alarabya_list_4

111

[{'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'الجامعة، مكة 24243، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '3.6 نجمة ',
  'location': '7248، 2415 سعود الفيصل، الصفا،، جدة 23451، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'شارع عبدالله سليمان، الفيحاء، جدة 22246، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': '7599 الأمير ماجد، حي العزيزية، 2335، جدة 23342، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'شارع عبدالله سليمان، الفيحاء، جدة 22246، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.3 نجمة ',
  'location': '2645 8840 طريق الملك عبدالله، السليمانية، جدة 22253، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'ابو حذيفه بن عتبه، مدائن الفهد، جدة 22337، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': '6155 ابراهيم الخليل، الشوقية، مكة 24351، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'Jabal Omar, الشبيكة، مكة 24231، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'المنار، جدة 23462، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.5 نجمة ',
  'location': 'Ibrahim Al Khalil, St Abraj Al Bait 1، مكة 24231، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود Arabia Oud',
  'rating': '4.4 نجمة ',
  'location': 'JDSA8673، 8673 ام القرى، 4142، حي الصفا،، جدة 23456، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'الاجاويد، جدة 22442، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'شارع أبي ذر الغفاري، حي النسيم 7280, جدة 23234، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '4.6 نجمة ',
  'location': 'عبدالعزيز بن ابراهيم، الصفا، جدة 23454، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.7 نجمة ',
  'location': 'شارع الحسين السهواجي، الربيع، جدة 23461، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود arabian oud',
  'rating': '3.5 نجمة ',
  'location': 'Al Marwah District، 3972 حراء،، جدة 23543، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': '3789، جدة 22434، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'CV77+4X، المرسلات، مكة 24243، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'شارع الشيخ محمد بن جبير، الشوقية، مكة 24351، المملكة العربية السعودية'},
 {'store_name': '963 العربية للعود | Arabian Oud',
  'rating': '4.1 نجمة ',
  'location': 'الحمراء وأم الجود، مكة 24331، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'CRW5+5M، طريق المدينة المنورة، الحجون، مكة 24237، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': '6306 Al Shouhadaa, الشهداء، 3576، مكة 24223، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'طريق الليث الفرعي، القرينية، جدة 22535، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': '6326 طريق الامير متعب بن عبدالعزيز، 3578، حي مشرفة، جدة 23341، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'قصر الضيافة، الزهراء، مكة 24221، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.5 نجمة ',
  'location': 'طريق الملك عبدالله، 3363 طريق الملك عبدالله، حي ابرق الرغامة، جدة 22261، 9059، جدة 22261، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '4.6 نجمة ',
  'location': 'الهجلة، مكة 24231، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'ام القرى، الصفا، جدة 23453، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'البهجه، مشرفة، جدة 23336، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'الحمراء، الحمراء وأم الجود،، مكة 24321، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'المنار، حي المنار، 3938, جدة 23463، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'النوارية، مكة 24215، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.7 نجمة ',
  'location': 'الصيرفي مول، حي الفيصلية، الفيصلية، جدة 23441، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود حراء الفحص',
  'rating': '3.6 نجمة ',
  'location': 'المروة، جدة 23541، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.2 نجمة ',
  'location': 'شارع الأمير محمد بن عبدالعزيز، الرحاب، Jarir Mall،، جدة 23345، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود Arabian Oud',
  'rating': '4.9 نجمة ',
  'location': 'شارع الدكتور عبدالقادر كوشك، ولي العهد، مكة 24353، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud العربية للعود',
  'rating': '4.5 نجمة ',
  'location': 'FQGR+GRF، مكة 24227، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.7 نجمة ',
  'location': 'Batha Quraish, 9400, مكة 24361، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود Arabian Oud',
  'rating': '3.8 نجمة ',
  'location': '6248 طريق الليث، ولي العهد، مكة 24356، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'شارع إبراهيم الجفالي، مكة 24372، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.1 نجمة ',
  'location': '3952، 6873 حي، مريخ، جدة 23361، المملكة العربية السعودية'},
 {'store_name': '674 العربية للعود | Arabian Oud',
  'rating': '4.1 نجمة ',
  'location': 'District, Madain Al Fahd, جدة 22347، المملكة العربية السعودية'},
 {'store_name': '646 العربية للعود | Arabian Oud',
  'rating': '3.8 نجمة ',
  'location': '6793، Al Marwah District، جدة 23545، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'الزاهر، مكة 24222، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'طريق الملك فيصل، العدل، مكة 24244، المملكة العربية السعودية'},
 {'store_name': '843 العربية للعود | Arabian Oud',
  'rating': '3.9 نجمة ',
  'location': '3141 الطريق الدائري الثالث، الخالدية، مكة 24232، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': '7906، الجامعة،، مكة 24242، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.7 نجمة ',
  'location': 'شارع فاطمة الزهراء، النسيم، مكة 24245، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.7 نجمة ',
  'location': 'طريق الامير متعب بن عبدالعزيز، الصفا، جدة 23451، المملكة العربية السعودية'},
 {'store_name': '949 العربية للعود | Arabian Oud',
  'rating': '4.2 نجمة ',
  'location': 'الفيصلية، الجموم 25335، المملكة العربية السعودية'},
 {'store_name': '683 العربية للعود | Arabian Oud',
  'rating': '4.7 نجمة ',
  'location': 'طريق الملك عبدالله، الفيحاء، جدة 22251، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': '5026 الشيخ عبدالله القرعاوي، الملك فهد, 6510، مكة 24341، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': '3297، مكة 24416، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود | Arabian Oud',
  'rating': '4.4 نجمة ',
  'location': 'طريق الليث، ولي العهد، مكة 24567، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'طريق مكة القديم, القديمة، بحره 22826، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '5.0 نجمة ',
  'location': 'مدرسه الثغر، District، 5580 Ahmad Al Badawi، جدة 22338، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'الامير فواز الجنوبي، جدة 22431، المملكة العربية السعودية'},
 {'store_name': '982 العربية للعود | Arabian Oud',
  'rating': '4.6 نجمة ',
  'location': '7425 قصر الضيافة، الزهراء، مكة 24221، المملكة العربية السعودية'},
 {'store_name': '291 العربية للعود | Arabian Oud',
  'rating': '3.6 نجمة ',
  'location': 'شارع الأجواد، المنار، جدة 23462، المملكة العربية السعودية'},
 {'store_name': '358 العربية للعود | Arabian Oud',
  'rating': '3.1 نجمة ',
  'location': '8276 الأمير ماجد، الفيصلية، جدة 23447، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '4.2 نجمة ',
  'location': 'المحمل سنتر, طريق الملك عبدالعزيز الفرعي، البلد، جدة 22233، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود - Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': 'F6RC+FC8، الفيحاء، جدة 22246، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'حي, شارع العزيزية العام، الجامعة، مكة 24243، المملكة العربية السعودية'},
 {'store_name': '228 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': 'البهجه، مشرفة، جدة 23336، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'قاده الفكر، الرويس، جدة 23215، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'الحمراء، جدة 23323، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': '3006 قريش، 6211، حي البوادي، جدة 23531، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '2.7 نجمة ',
  'location': 'المنصور، مكة 24231، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'مطار الملك عبدالعزيز الدولي، جدة 23635، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': 'طريق الملك عبدالله، النخيل، جدة 22261، المملكة العربية السعودية'},
 {'store_name': '726 العربية للعود | Arabian Oud',
  'rating': '4.0 نجمة ',
  'location': '3413 شارع الحجون، الحجون، مكة 24231، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'طريق القاضي، بطحاء قريش، مكة 24352، المملكة العربية السعودية'},
 {'store_name': '486 العربية للعود | Arabian Oud',
  'rating': '4.0 نجمة ',
  'location': 'الخالدية، الجموم 25335، المملكة العربية السعودية'},
 {'store_name': '235 العربية للعود | Arabian Oud',
  'rating': '4.0 نجمة ',
  'location': '6945 حمزة بن عبدالمطلب، 4006, الهجلة، مكة 24231، المملكة العربية السعودية'},
 {'store_name': '258 العربية للعود | Arabian Oud',
  'rating': '3.7 نجمة ',
  'location': '3923 ابراهيم الخليل، الهجلة، 7089 ابراهيم الخليل،، مكة 24231، المملكة العربية السعودية'},
 {'store_name': '220 العربية للعود | Arabian Oud',
  'rating': '4.8 نجمة ',
  'location': 'سوق الحجاز، طريق مكة جدة السريع، النزهة، مكة 24225، المملكة العربية السعودية'},
 {'store_name': 'الإدارة الإقليمية لشركة العربية للعود بمكة',
  'rating': '4.4 نجمة ',
  'location': 'طريق مكة جدة القديم، النزهة، مكة 24225، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'المحاميد 22393، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'طريق الملك فهد فرعي، الربوة، جدة 23533، المملكة العربية السعودية'},
 {'store_name': 'Arabian oud العربية للعود 1273',
  'rating': '5.0 نجمة ',
  'location': '9QHV+JV3، الشوقية، مكة 24351، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'مطار الملك عبدالعزيز الدولي، جدة 23635، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': '8912 قاسم زينة، 4471 قاسم زينة، حي الروضة، جدة 23434، جدة 23434، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'حمد الجاسر، الروضة، جدة 23434، المملكة العربية السعودية'},
 {'store_name': '288 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': 'الجامعة، 5510, حي الثغر, JIJB7134، 7134, جدة 22338، المملكة العربية السعودية'},
 {'store_name': '1231 العربية للعود | Arabian Oud',
  'rating': '4.5 نجمة ',
  'location': 'الحمراء، جدة 23324، المملكة العربية السعودية'},
 {'store_name': '212 العربية للعود | Arabian Oud',
  'rating': '3.6 نجمة ',
  'location': 'البوادي، جدة 23443، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '4.1 نجمة ',
  'location': 'H5V3+VV4، شارع شرق النهضه، السلامة، جدة 28383، المملكة العربية السعودية'},
 {'store_name': 'مستودع العربيه للعود',
  'rating': '5.0 نجمة ',
  'location': '9PQC+4V7، Unnamed Road, الملك فهد،، مكة 24346، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '4.2 نجمة ',
  'location': 'طريق الامير سلطان، الزهراء، جدة 23425، المملكة العربية السعودية'},
 {'store_name': '696 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': 'Jabal Omar, الشبيكة، مكة 24231، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud العربية للعود',
  'rating': '4.8 نجمة ',
  'location': '9W53+XVV Dan Plaza, مكة 58644، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.6 نجمة ',
  'location': 'النزهة، جدة 23532، المملكة العربية السعودية'},
 {'store_name': '662 العربية للعود | Arabian Oud',
  'rating': '2.9 نجمة ',
  'location': '3749 صقر قريش، As Salamah District، جدة 23436، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'الخضراء، مكة 24267، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '3.7 نجمة ',
  'location': 'حي, طريق المدينة المنورة، النعيم، جدة 23526، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': '3811 حراء, AZ Zahra District, جدة 23522، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.4 نجمة ',
  'location': 'طريق الأمير سلطان، النهضة، جدة 23523، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'البترجي فرعي، الزهراء، جدة 23521، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'Fruit Boat Sculpture, شارع حراء، النهضة، جدة 23523، المملكة العربية السعودية'},
 {'store_name': '224 العربية للعود | Arabian Oud',
  'rating': '3.9 نجمة ',
  'location': '7871 طريق الامير سلطان، 2647, An Naim District, جدة 23621، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'الراشدية، مكة 24269، المملكة العربية السعودية'},
 {'store_name': '1218 العربية للعود | Arabian Oud',
  'rating': '4.0 نجمة ',
  'location': 'الحمدانية، جدة 23761، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'الحمدانية، جدة 23761، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': '8712 شارع القادسية، 3863, مكة 24268، المملكة العربية السعودية'},
 {'store_name': '1217 العربية للعود | Arabian Oud',
  'rating': '4.5 نجمة ',
  'location': '7358، 5431 عبد الرحمن الناصر، الأصالة، جدة 23738، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'شارع عابر القرات، أبحر الشمالية، جدة 23815، المملكة العربية السعودية'},
 {'store_name': 'نخبة العود',
  'rating': '4.2 نجمة ',
  'location': 'حي، شارع الأجواد، السامر، جدة 23462، المملكة العربية السعودية'},
 {'store_name': '624 العربية للعود | Arabian Oud',
  'rating': '3.4 نجمة ',
  'location': 'الحمدانية، جدة 23761، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود الحمدانيه',
  'rating': '4.6 نجمة ',
  'location': 'حي, JGAA4079, 8462 عمرو بن ابي وقاص(رضي الله عن، الحمدانية، 4079, جدة 23761، المملكة العربية السعودية'},
 {'store_name': 'الدخيل للعود',
  'rating': '4.4 نجمة ',
  'location': 'شارع الأجواد، حي السامر، جدة 23462، المملكة العربية السعودية'}]

In [650]:
alarabya_list_5=pickle.load(open('alarabya_pkl\\alarabya_abha.pkl','rb'))
alarabya_list_5 = [dictionary for dictionary in alarabya_list_5 if 'الإسكندرية' not in dictionary['location'] and 'القاهرة' not in dictionary['location']]
print(len(alarabya_list_5))

alarabya_list_5

110

[{'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'المنسك، حي، أبها 62581، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '4.3 نجمة ',
  'location': 'شارع وهب بن مسرة, المروج، أبها 62527، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '3.7 نجمة ',
  'location': 'شارع الملك فيصل، وسط المدينة، أبها 62521، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '4.3 نجمة ',
  'location': 'حي, طريق الملك عبدالعزيز، ذرة، أبها 62521، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'حي, طريق الملك عبدالعزيز، الشرفية، أبها 62542، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': '3980، بحر ابو سكينة 63585، المملكة العربية السعودية'},
 {'store_name': '1224 العربية للعود | Arabian Oud',
  'rating': '4.0 نجمة ',
  'location': 'الراشد مول, طريق الملك فهد، البديع، أبها 12839، المملكة العربية السعودية'},
 {'store_name': '857 العربية للعود | Arabian Oud',
  'rating': '4.0 نجمة ',
  'location': '76MR+H2، الجرف 63454، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.0 نجمة ',
  'location': '4608 طريق الملك عبدالعزيز، السد، أبها 62521، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'الفيصلية، محايل عسير 63715، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.6 نجمة ',
  'location': 'مجمع الغنيم، طريق الملك فيصل، الخالدية، Muhayil,Abha 63687، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.7 نجمة ',
  'location': 'طريق الملك فيصل، الفيصلية، محايل عسير 63687، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': '2555, مخطط الموسى, خميس مشيط 62463، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.4 نجمة ',
  'location': 'الواحة سنتر، طريق الملك فهد، خميس مشيط 62434، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.7 نجمة ',
  'location': 'الواحة، خميس مشيط 62456، المملكة العربية السعودية'},
 {'store_name': 'الماجد للعود',
  'rating': '4.1 نجمة ',
  'location': 'البديع، أبها 62581، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.6 نجمة ',
  'location': 'HMPW+J9، عريجة، وادي ابن هشبل 62931، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '3.9 نجمة ',
  'location': 'أم سرور، خميس مشيط 62461، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.5 نجمة ',
  'location': 'شارع الملك خالد، الشفاء، خميس مشيط 62433، المملكة العربية السعودية'},
 {'store_name': '131 العربية للعود | Arabian Oud',
  'rating': '3.8 نجمة ',
  'location': '8770، السلام، خميس مشيط 62461، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '5.0 نجمة ',
  'location': 'Unnamed Road 62497، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': '5457 طريق الملك فهد، خميس مشيط 62461، المملكة العربية السعودية'},
 {'store_name': '498 العربية للعود | Arabian Oud',
  'rating': '4.0 نجمة ',
  'location': '8P4J+CX3، العرق الجنوبي، خميس مشيط 62461، المملكة العربية السعودية'},
 {'store_name': '716 العربية للعود | Arabian Oud',
  'rating': '3.0 نجمة ',
  'location': 'العرق الجنوبي، خميس مشيط 62461، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '5.0 نجمة ',
  'location': '9061 الشارع العام، AGPB2375، 2375، آل عامر 62263، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '4.1 نجمة ',
  'location': '8379 طريق الأمير سلطان، الموسى، خميس مشيط 62463، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'Avenue، طريق الملك خالد،، ذلالة، خميس مشيط 62411، المملكة العربية السعودية'},
 {'store_name': '1228 العربية للعود | Arabian Oud',
  'rating': '3.7 نجمة ',
  'location': '8772 البلد 13, حي السلام, AKPA3785، 3785, خميس مشيط 62461، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '5.0 نجمة ',
  'location': '8452 جنوبا الى احد رفيده و شمالا الى خميس مشيط، سكن المدينة العسكرية، 3615، خميس مشيط 62413، المملكة العربية السعودية'},
 {'store_name': 'الماجد للعود',
  'rating': '4.2 نجمة ',
  'location': 'مذركير الراشد، البديع، أبها 62581، المملكة العربية السعودية'},
 {'store_name': 'الدخيل للعود AL-Dakheel Oud',
  'rating': '3.9 نجمة ',
  'location': 'طريق الملك عبدالعزيز، الشفاء، أبها 62521، المملكة العربية السعودية'},
 {'store_name': '578 العربية للعود | Arabian Oud',
  'rating': '3.7 نجمة ',
  'location': 'الرونة، أحد رفيدة 62447، المملكة العربية السعودية'},
 {'store_name': 'درعه DERAAH',
  'rating': '4.3 نجمة ',
  'location': '6HF3+6XW، 6HF4+622، أبها 11551، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '4.5 نجمة ',
  'location': 'حي, شكر، طريق الامير سلطان - حديقة موجان المملكة العربية السعودية'},
 {'store_name': '871 العربية للعود | Arabian Oud',
  'rating': '4.7 نجمة ',
  'location': 'P7PC+WC، الدرب 89888، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'P7RH+9V، الدرب 89699، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '5.0 نجمة ',
  'location': '6142 طريق الملك عبدالله، حي الزهور، AEPA3680، 3680، بارق 63916، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'طريق الكورنيش، الشاطيء، جازان 82811، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': '44FJ+H2، طريق الملك فيصل، السلام، النماص 67393، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'الملك فهد،، الملك فهد، أبو عريش 84522، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود والعطور',
  'rating': '3.6 نجمة ',
  'location': 'Q97H+M2، الصفة 28939، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'طريق الداير وادي الجنية، الدائر 83862، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': '15، تنومة 62795، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.7 نجمة ',
  'location': 'طريق الملك فهد، تاج مول، أبو عريش 84416، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'طريق الكورنيش، كادي مول، جازان 82725، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'بارق 63916، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': '5، الشريعة 87587، المملكة العربية السعودية'},
 {'store_name': '745 العربية للعود | Arabian Oud',
  'rating': '4.1 نجمة ',
  'location': 'H6G5+G3، طريب 62828، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.6 نجمة ',
  'location': 'طريق الملك عبدالعزيز، 6349، GBMA3194، 3194، ضمد 84971، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.4 نجمة ',
  'location': 'طريق الملك خالد بن عبدالعزيز،، الروضة، سراة عبيدة 64532، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '5.0 نجمة ',
  'location': '6714، الباحة 65522 3341، 65522، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.6 نجمة ',
  'location': 'طريق احمد بن عبدالعزيز، القوز 28829، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'طريق بدر، المجاردة 63971، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.0 نجمة ',
  'location': 'طريق الملك فهد بن عبدالعزيز، القنفذة 28822، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'Dhahran Al Janub، Dhahran 64271، المملكة العربية السعودية'},
 {'store_name': '1248 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': 'طريق الملك عبدالعزيز، 6316, GBMA3134، 3134, ضمد 84971، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.6 نجمة ',
  'location': 'VHQC+P6W، جازان 82722، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.4 نجمة ',
  'location': '3033 طريق الملك عبدالعزيز، الرحاب، 7228 طريق الملك عبدالعزيز،، صبيا 85457، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.6 نجمة ',
  'location': 'الملك عبد العزيز، القنفذة 28821، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'شارع الملك عبدالعزيز, حي الشامية، جازان 82714، المملكة العربية السعودية'},
 {'store_name': 'العربية للعطور',
  'rating': '3.8 نجمة ',
  'location': 'العزيزية، بللسمر 62767، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': '8764 طريق الملك فهد، الشاطيء، جازان 82727، المملكة العربية السعودية'},
 {'store_name': '756 العربية للعود | Arabian Oud',
  'rating': '3.9 نجمة ',
  'location': 'العزيزية، صبيا 85297، المملكة العربية السعودية'},
 {'store_name': '262 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': 'شارع حلي، الأزهار، القنفذة 28821، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'طريق الامير سلطان، ذي ريجن مول، أبو عريش 84522، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '5.0 نجمة ',
  'location': 'الطريق العام, نمرة 65439، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'HMJ6+XJ, 211، نمرة 65466، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud العربية للعود',
  'rating': '5.0 نجمة ',
  'location': '6193 فهد بن عبدالعزيز, حي الاثايبة, NJMB2554، 2554, نجران 66258، المملكة العربية السعودية'},
 {'store_name': '776 العربية للعود | Arabian Oud',
  'rating': '4.3 نجمة ',
  'location': '2687 طريق المطار، جازان 82722، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.5 نجمة ',
  'location': 'الطريق العام, حبونا 66342، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': '9674، 3491 طريق الملك عبد العزيز، نجران 66263 المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.5 نجمة ',
  'location': 'طريق سليمان الراجحي، حي القيم الأعلى، الطائف 26551، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.3 نجمة ',
  'location': 'المستشفى، بلجرشي 65635، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '4.1 نجمة ',
  'location': 'H5V3+VV4، شارع شرق النهضه، السلامة، جدة 28383، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': '2F77+4GJ، الإمام محمد بن سعود، الحاوية، الباحة 65525، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.6 نجمة ',
  'location': 'الملك عبدالعزيز, النصباء 65581، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'الملك عبدالله، بيشة 67712، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': '3144، 7842، النزهة، الباحة 65711، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'صامطة 86736، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.0 نجمة ',
  'location': '6221 2054 طريق الملك عبدالعزيز، المجد، صبيا 85534، المملكة العربية السعودية'},
 {'store_name': '1227 العربية للعود | Arabian Oud',
  'rating': '1.0 نجمة ',
  'location': 'الشرقية، القنفذة 28822، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '5.0 نجمة ',
  'location': 'الشروق، طريق الملك فهد - مول, الباحة المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': '7HF3QC8M+FV، المخواة 65614، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': '7337 الامير سلطان فرعي، حي المحمدية، جدة 23625 2115، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'طريق الملك فهد، المخواة 65311، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.7 نجمة ',
  'location': 'طريق الملك عبدالعزيز، مخطط العريسة الشمالي 66243، المملكة العربية السعودية'},
 {'store_name': '1213 العربية للعود | Arabian Oud',
  'rating': '4.4 نجمة ',
  'location': 'NJUB7872، 7872 حمد ابن ماضي, 3844, حي أبا السعود, نجران 66281، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'طريق الملك فهد، النسيم، قلوة 65335، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': '4020 شارع الامير سلطان، الخزامى، بيشة 67711، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '4.0 نجمة ',
  'location': 'السداد، الطائف 26514، المملكة العربية السعودية'},
 {'store_name': '364 العربية للعود | Arabian Oud',
  'rating': '3.5 نجمة ',
  'location': 'العزيزية، سبت العلاية 67542، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.7 نجمة ',
  'location': 'طريق الملك خالد، الخزامى، بيشة 67711، المملكة العربية السعودية'},
 {'store_name': '701 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': 'التاج مول, طريق الملك فهد، بن عبدالعزيز, أبو عريش 82511، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'شارع الملك سعود، الشرقية، الطائف 26513، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud |العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'الخالدية، 4177، الخالدية، نجران 66261 9299, نجران 66261، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.3 نجمة ',
  'location': '2645 8840 طريق الملك عبدالله، السليمانية، جدة 22253، المملكة العربية السعودية'},
 {'store_name': '1242 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': '7610 الضحى 2, MOPA2483، 2483, أضم, اضم 28665، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.1 نجمة ',
  'location': 'العقيق 65914، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'طريق الملك عبدالعزيز، الصفا، جازان 82721، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.5 نجمة ',
  'location': 'Ibrahim Al Khalil, St Abraj Al Bait 1، مكة 24231، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'بلجرشي البلد ش الملك فهد مقابل مجمع بن زوما، بلجرشي المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '3.6 نجمة ',
  'location': '7248، 2415 سعود الفيصل، الصفا،، جدة 23451، المملكة العربية السعودية'},
 {'store_name': '923 العربية للعود | Arabian Oud',
  'rating': '3.9 نجمة ',
  'location': 'نجران 66252، المملكة العربية السعودية'},
 {'store_name': '155 العربية للعود | Arabian Oud',
  'rating': '4.3 نجمة ',
  'location': '6714، الباحة 65522 3341، 65522، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'الجامعة، مكة 24243، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'Taibah District, جدة 23831، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': '2167 محمد صالح باشراحيل، الراشدية، مكة 24268، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'شارع إبراهيم الجفالي، مكة 24372، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'الخضراء، مكة 24267، المملكة العربية السعودية'},
 {'store_name': '717 العربية للعود | Arabian Oud',
  'rating': '2.3 نجمة ',
  'location': 'Al Husayn Market, Al Husayn rd 66273، المملكة العربية السعودية'}]

In [651]:
alarabya_list_7=pickle.load(open('alarabya_pkl\\alarabya_dammam.pkl','rb'))
alarabya_list_7 = [dictionary for dictionary in alarabya_list_7 if 'الإسكندرية' not in dictionary['location'] and 'القاهرة' not in dictionary['location']]
print(len(alarabya_list_7))

alarabya_list_7

115

[{'store_name': 'العربيه للعود',
  'rating': '3.9 نجمة ',
  'location': 'طريق الملك خالد الفرعي، الحمراء، الخبر 34628، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'شارع عبدالرحمن بن عوف، بدر، الدمام 32274، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'العقربية، الخبر 34445، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': '7103 الامير بندر بن عبد العزيز، حي الخبر الشمالية، الخبر 34428، المملكة العربية السعودية'},
 {'store_name': '629 العربية للعود | Arabian Oud',
  'rating': '4.0 نجمة ',
  'location': '8277 2363 الخوارزمي, أحد، الدمام 32264، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود والعطور',
  'rating': '4.0 نجمة ',
  'location': 'شارع عمر بن الخطاب، الفيصلية، الدمام 32272، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': '7579 طريق الأمير محمد بن فهد بن عبدالعزيز، الاسكان، الدمام 32236، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'طريق الأمير نايف بن عبدالعزيز، البحيرة، الدمام 32431، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'حي, شارع الملك خالد، الجلوية، الدمام 32246، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'الجسر، الخبر 34714، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.6 نجمة ',
  'location': 'حي الجامعة، الظهران 34257، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'طريق الملك فهد، أحد، الدمام 32263، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'طريق الملك خالد، التحلية، الخبر 34716، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': '8073 طريق الملك سعود, الصفا، الدمام 34222، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود فرع الثقبة',
  'rating': '4.1 نجمة ',
  'location': 'الثالث عشر، الثقبة، الخبر 34623، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.7 نجمة ',
  'location': '13th Street, الدواسر، الدمام 32416، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'الدانة، رأس تنورة 32817، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '4.3 نجمة ',
  'location': 'مول دارين, Khaleej Rd, العزيزية، الدمام 32424، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'العثيم مول، حي عبد الله فؤاد، عبدالله فؤاد، الدمام 32236، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'النزهة، الدمام 32252، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'الثقبة، الخبر 34623، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'طريق الملك فهد, حي الفيصلية، الدمام 32272، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'العنود، الدمام 32427، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '4.1 نجمة ',
  'location': 'المدرسة, حي طيبة، الجبيل 35514، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'المستودعات، القطيف 32632، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'شارع ١٧ (د)، الشاطئ، القطيف 32617، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.5 نجمة ',
  'location': '4845 أبو أمية المخزومي، 8048، المزروعية، الدمام 32414، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'مطار الملك فهد الدولي، الدمام 32567، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '4.2 نجمة ',
  'location': '39 ب، الندى، الدمام 32271، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'طريق الملك فهد، العدامة، الدمام 32242، المملكة العربية السعودية'},
 {'store_name': '555 العربية للعود | Arabian Oud',
  'rating': '4.4 نجمة ',
  'location': 'الشاطئ الشرقي، الدمام 32414، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود فرع الصفا',
  'rating': '4.0 نجمة ',
  'location': '7921 طريق الملك سعود بن عبدالعزيز، حي الصفا، الدمام 34222 3374، المملكة العربية السعودية'},
 {'store_name': '360 العربية للعود | Arabian Oud',
  'rating': '4.2 نجمة ',
  'location': 'مجمع الظهران، شارع فيصل بن فهد، حي، الدوحة الجنوبية، الظهران 34457، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'السلام،، الدمام 32416، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود شارع البيبسي',
  'rating': '4.6 نجمة ',
  'location': '4312 طريق الأمير فيصل بن فهد، الحزام الأخضر، الخبر 34436 6229، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'المدينة، بقيق 33261، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود |Arabian Oud',
  'rating': '3.6 نجمة ',
  'location': '9185 الملك فيصل الغربي، W, الجبيل 35518، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'حي, طريق الملك عبدالعزيز، البحر، الجبيل 35419، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'الجبيل البلد، الجبيل 35513، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '4.7 نجمة ',
  'location': 'طريق الأمير فيصل بن فهد، العقربية، الخبر 34436، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.5 نجمة ',
  'location': 'شارع عمر بن الخطاب، الفيصلية، الدمام 32272، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '4.5 نجمة ',
  'location': 'P356+MJV، نواف بن عبدالعزيز، شارع الأمير، رأس تنورة المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '4.5 نجمة ',
  'location': 'حي, شارع خالد بن الوليد، الراكة الجنوبية، الخبر 34226، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود مجمع الراشد',
  'rating': '3.0 نجمة ',
  'location': '75RJ+CHQ، طريق خادم الحرمين الشريفين، العليا، الخبر 32652، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'الحويلات، الجبيل 35718، المملكة العربية السعودية'},
 {'store_name': '551 العربية للعود | Arabian Oud',
  'rating': '3.0 نجمة ',
  'location': 'حي, شارع الملك خالد، الجلوية، الدمام 32246، المملكة العربية السعودية'},
 {'store_name': 'مستودع العربية للعود',
  'rating': '5.0 نجمة ',
  'location': 'C578+C5M، الخالدية الجنوبية، Unnamed Road، الدمام 32221، المملكة العربية السعودية'},
 {'store_name': '3602 العربية للعود | Arabian Oud',
  'rating': '4.8 نجمة ',
  'location': 'Shop 155 Building 184 Road 28 Block 410 SANABIS, المنامة 973، البحرين'},
 {'store_name': 'العربية للعود',
  'rating': '3.6 نجمة ',
  'location': 'الفناتير، The Galleria Mall, Al Khamis Road، الجبيل 35811، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'شارع الرفاع، الرفاع، البحرين'},
 {'store_name': 'موسسه سيوفي العربيه للعود والعطور',
  'rating': '5.0 نجمة ',
  'location': '76R7+FC4، حي الخبر الشمالية، الخبر 34428، المملكة العربية السعودية'},
 {'store_name': 'OudElite - نخبة العود 7399',
  'rating': '3.8 نجمة ',
  'location': '75RJ+49، العليا، 3556 الراشد مول الخبر SA، الخبر 34448، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود مجمع السيف',
  'rating': '3.7 نجمة ',
  'location': 'مجمع السيف, Rd No 2819، ضاحية السيف، البحرين'},
 {'store_name': 'OudElite - نخبة العود 7335',
  'rating': '3.9 نجمة ',
  'location': 'C4C7+M7، 4386 عبد الملك البصري، مدينة العمال، الدمام 32253 8082، الدمام المملكة العربية السعودية'},
 {'store_name': 'الماجد للعود',
  'rating': '4.3 نجمة ',
  'location': '4925 شارع الأشرعة، المزروعية، الدمام 32414، المملكة العربية السعودية'},
 {'store_name': '3607 العربية للعود | Arabian Oud',
  'rating': '4.5 نجمة ',
  'location': 'Shop 1193 Building، 3977 Road 4660، المنامة 973، البحرين'},
 {'store_name': 'Almajed For Oud',
  'rating': '4.5 نجمة ',
  'location': 'شارع الملك سعود بن عبدالعزيز، النور، الدمام 32445، المملكة العربية السعودية'},
 {'store_name': 'الدخيل للعود AL-Dakheel Oud',
  'rating': '4.3 نجمة ',
  'location': 'طريق الكورنيش،، السلام، الدمام 32416، المملكة العربية السعودية'},
 {'store_name': 'الماجد للعود',
  'rating': '4.1 نجمة ',
  'location': 'الامير محمد، الجبيل البلد، الجبيل 35514، المملكة العربية السعودية'},
 {'store_name': 'OudElite - نخبة العود 7357',
  'rating': '4.3 نجمة ',
  'location': 'C334+9M، الفيصلية،، الدمام 32272، المملكة العربية السعودية'},
 {'store_name': 'الدخيل للعود AL-Dakheel Oud',
  'rating': '4.1 نجمة ',
  'location': 'طريق خادم الحرمين الشريفين، الثقبة، الخبر 34623، المملكة العربية السعودية'},
 {'store_name': 'Dkhoun',
  'rating': '4.3 نجمة ',
  'location': 'Al Rashid Mall, 3554 Al Ulaya، الخبر المملكة العربية السعودية'},
 {'store_name': 'OudElite - نخبة العود 7360',
  'rating': '4.2 نجمة ',
  'location': '7763 شارع عبدالرحمن بن معاذ، الخبر الجنوبيه عبد الرحمن بن معاذ، الخبر 34714، المملكة العربية السعودية'},
 {'store_name': '3606 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': 'Shop 243 Building, 180 Road 41, المنامة 340، البحرين'},
 {'store_name': 'درعه DERAAH',
  'rating': '4.5 نجمة ',
  'location': '8369 الملك فيصل الغربي، ميناء الملك فهد الصناعي، 3404 XJHW+XXG الجبيل SA، الجبيل 35518، المملكة العربية السعودية'},
 {'store_name': 'Almajed For Oud',
  'rating': '5.0 نجمة ',
  'location': 'Othaim Mall, عبدالله فؤاد، الدمام 32236، المملكة العربية السعودية'},
 {'store_name': 'درعه DERAAH',
  'rating': '4.2 نجمة ',
  'location': 'الشارع الثاني والعشرون، العقربية، الخبر 34446، المملكة العربية السعودية'},
 {'store_name': 'درعه DERAAH',
  'rating': '4.5 نجمة ',
  'location': '6674+9X6، فخر الدين بن سلام، الجسر، الخبر 34714، المملكة العربية السعودية'},
 {'store_name': 'درعه DERAAH',
  'rating': '4.5 نجمة ',
  'location': 'شارع 13، السوق، الدمام 32253، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'شارع الأمير محمد بن فهد بن عبدالعزيز، المروج، قرية العليا 37633، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '4.1 نجمة ',
  'location': 'طريق الظهران، حي الخرس، المبرز 36342، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'طريق الملك سعود، السلام الثاني، المبرز 36422، المملكة العربية السعودية'},
 {'store_name': '1150 العربية للعود | Arabian Oud',
  'rating': '4.1 نجمة ',
  'location': '4506 طريق الملك خالد، وسط الهفوف التاريخي، حي, 7055، الهفوف 36361، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'طريق الخليج، حي الروضة، الهفوف 36362، المملكة العربية السعودية'},
 {'store_name': 'عطور رسيس | Rasees perfumes',
  'rating': '4.8 نجمة ',
  'location': 'المزروعية،, الدمام 32414، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'Mahasin, شارع خالد بن الوليد، اسواق القرية الشعبية، حي،، الهفوف 36421، المملكة العربية السعودية'},
 {'store_name': '986 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': '9J8R+P9C، الفردوس، الهفوف 36368، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'النايفية، الهفوف 36445، المملكة العربية السعودية'},
 {'store_name': 'دخون الجزيرة للعود',
  'rating': '4.9 نجمة ',
  'location': 'شارع مكة المكرمة، الثقبة، شارع 20 تقاطع 12634، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '5.0 نجمة ',
  'location': 'الأمير سلطان بن عبدالعزيز، الفيصلية، النعيرية 37485، المملكة العربية السعودية'},
 {'store_name': '807 العربية للعود | Arabian Oud',
  'rating': '4.4 نجمة ',
  'location': 'شارع الأمير طلال بن عبدالعزيز،، الهفوف 36361، المملكة العربية السعودية'},
 {'store_name': '838 العربية للعود | Arabian Oud',
  'rating': '3.9 نجمة ',
  'location': 'السلمانية الشمالية، الهفوف 36421، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'طريق أنس ابن مالك، الصحافة، الرياض 13321، المملكة العربية السعودية'},
 {'store_name': 'Dkhoun | دخون',
  'rating': '4.7 نجمة ',
  'location': 'الجبيل البلد، الجبيل 35514، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud | العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'VJ3X+6CF، النرجس، الرياض 13333، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'طريق الملك عبدالله الفرعي، الحمراء، الرياض 13217، المملكة العربية السعودية'},
 {'store_name': 'درعه DERAAH',
  'rating': '4.5 نجمة ',
  'location': '85F8+G3R، الدوحة الجنوبية، الظهران 34451، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'الإمام سعود بن عبد العزيز بن محمد، المغرزات، الرياض المملكة العربية السعودية'},
 {'store_name': 'العربية للعود التخصصي',
  'rating': '4.4 نجمة ',
  'location': '7324 شارع التخصصي، العليا، الرياض 12342، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '3.9 نجمة ',
  'location': 'شارع جرير، الملز، الرياض 12836، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.5 نجمة ',
  'location': 'المونسية، الرياض 13253، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': '7575 الطريق الدائري الشرقي الفرعي، القدس، الرياض 13214، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.4 نجمة ',
  'location': 'الندوة، حي الندوة، الرياض 14814، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'اليرموك، الرياض 13251، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'طريق الملك فهد، العقيق، الرياض 13515، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'طريق الإمام عبدالله بن سعود بن عبدالعزيز الفرعي، اليرموك، الرياض 13243، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.5 نجمة ',
  'location': 'حي, طريق الملك عبدالعزيز، الربيع، الرياض 13316، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود 18',
  'rating': '5.0 نجمة ',
  'location': 'الملك فهد، الرياض 12261، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': '6441 شارع حسان بن ثابت، النسيم الشرقي، الرياض 14241، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.6 نجمة ',
  'location': 'طريق ابي بكر الصديق، النرجس، الرياض 13336، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.0 نجمة ',
  'location': 'الاندلس، الرياض 11564، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': '3708 طريق العزيزية الفرعي، العزيزية، 6776 طريق العزيزية،، الرياض 14511، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود ArabianOud',
  'rating': '4.8 نجمة ',
  'location': 'قطر مول، الدوحة، قطر'},
 {'store_name': 'العربية للعود',
  'rating': '3.3 نجمة ',
  'location': 'طريق نجم الدين الأيوبي الفرعي، طويق، الرياض 14931، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'شارع الأمير بندر بن عبد العزيز، حي النهضة، النهضة، الرياض 13222، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.4 نجمة ',
  'location': '6774 طريق الأمير محمد بن سلمان بن عبدالعزيز، قرطبة، 3548، الرياض 13247، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.5 نجمة ',
  'location': 'الحارث بن عبدالله، حي الندوة، الرياض 14813، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': '3427 طريق الخرج، المنصورة، الرياض 12692، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'شارع عنيزة، الريان، الرياض 14213، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'شارع الترمذي، أسواق العودة، الرياض 14712، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'شارع الإمام أحمد بن حنبل، النسيم الغربي، الرياض 14233، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'سلمان الفارسي، النهضة،،، النهضة، الرياض 13221، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'الملقا, طريق الامام سعود بن فيصل الفرعي المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.6 نجمة ',
  'location': 'صالح الهاشمي، العقيق، الرياض 13511، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': '3516 الوادي, هجرة لبن، الرياض 12936، المملكة العربية السعودية'}]

In [652]:
alarabya_list_8=pickle.load(open('alarabya_pkl\\alarabya_hfouf.pkl','rb'))
alarabya_list_8 = [dictionary for dictionary in alarabya_list_8 if 'الإسكندرية' not in dictionary['location'] and 'القاهرة' not in dictionary['location']]
print(len(alarabya_list_8))

alarabya_list_8

113

[{'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'طريق الملك سعود، السلام الثاني، المبرز 36422، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'طريق الخليج، حي الروضة، الهفوف 36362، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '4.1 نجمة ',
  'location': 'طريق الظهران، حي الخرس، المبرز 36342، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'النايفية، الهفوف 36445، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'Mahasin, شارع خالد بن الوليد، اسواق القرية الشعبية، حي،، الهفوف 36421، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '3.8 نجمة ',
  'location': 'طريق الرياض, المحمدية، الهفوف 36421، المملكة العربية السعودية'},
 {'store_name': '807 العربية للعود | Arabian Oud',
  'rating': '4.4 نجمة ',
  'location': 'شارع الأمير طلال بن عبدالعزيز،، الهفوف 36361، المملكة العربية السعودية'},
 {'store_name': '838 العربية للعود | Arabian Oud',
  'rating': '3.9 نجمة ',
  'location': 'السلمانية الشمالية، الهفوف 36421، المملكة العربية السعودية'},
 {'store_name': '1150 العربية للعود | Arabian Oud',
  'rating': '4.1 نجمة ',
  'location': '4506 طريق الملك خالد، وسط الهفوف التاريخي، حي, 7055، الهفوف 36361، المملكة العربية السعودية'},
 {'store_name': '986 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': '9J8R+P9C، الفردوس، الهفوف 36368، المملكة العربية السعودية'},
 {'store_name': 'الدخيل للعود AL-Dakheel Oud',
  'rating': '4.0 نجمة ',
  'location': 'الفوارس مول بوابة 2، الرفعة الجنوبية الهفوف، المبرز 36361، المملكة العربية السعودية'},
 {'store_name': 'OudElite - نخبة العود 7345',
  'rating': '4.1 نجمة ',
  'location': 'طريق الملك عبدالله، المبرز 36342، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'المدينة، بقيق 33261، المملكة العربية السعودية'},
 {'store_name': 'الماجد للعود',
  'rating': '4.2 نجمة ',
  'location': 'الاحساء2, الهفوف 36361، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود شارع البيبسي',
  'rating': '4.6 نجمة ',
  'location': '4312 طريق الأمير فيصل بن فهد، الحزام الأخضر، الخبر 34436 6229، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.5 نجمة ',
  'location': 'شارع عمر بن الخطاب، الفيصلية، الدمام 32272، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود فرع الصفا',
  'rating': '4.0 نجمة ',
  'location': '7921 طريق الملك سعود بن عبدالعزيز، حي الصفا، الدمام 34222 3374، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '4.3 نجمة ',
  'location': 'مول دارين, Khaleej Rd, العزيزية، الدمام 32424، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '4.2 نجمة ',
  'location': '39 ب، الندى، الدمام 32271، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '4.0 نجمة ',
  'location': 'الربوة،، الربوة، الرياض 12839، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '4.7 نجمة ',
  'location': 'طريق الأمير فيصل بن فهد، العقربية، الخبر 34436، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'السلام،، الدمام 32416، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '5.0 نجمة ',
  'location': '8015 طريق الدمام الفرعي، اليرموك، الرياض 13243، المملكة العربية السعودية'},
 {'store_name': 'دخون',
  'rating': '4.9 نجمة ',
  'location': 'Al Othaim Mall, Al Ahsa المملكة العربية السعودية'},
 {'store_name': 'العربية للعود مجمع الراشد',
  'rating': '3.0 نجمة ',
  'location': '75RJ+CHQ، طريق خادم الحرمين الشريفين، العليا، الخبر 32652، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '4.5 نجمة ',
  'location': 'P356+MJV، نواف بن عبدالعزيز، شارع الأمير، رأس تنورة المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'طريق الملك خالد، التحلية، الخبر 34716، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '3.9 نجمة ',
  'location': 'طريق الملك خالد الفرعي، الحمراء، الخبر 34628، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'الجسر، الخبر 34714، المملكة العربية السعودية'},
 {'store_name': '629 العربية للعود | Arabian Oud',
  'rating': '4.0 نجمة ',
  'location': '8277 2363 الخوارزمي, أحد، الدمام 32264، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': '7103 الامير بندر بن عبد العزيز، حي الخبر الشمالية، الخبر 34428، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'العقربية، الخبر 34445، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'شارع عبدالرحمن بن عوف، بدر، الدمام 32274، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'الثقبة، الخبر 34623، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.6 نجمة ',
  'location': 'حي الجامعة، الظهران 34257، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'طريق الملك فهد، أحد، الدمام 32263، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'طريق الملك فهد, حي الفيصلية، الدمام 32272، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'العثيم مول، حي عبد الله فؤاد، عبدالله فؤاد، الدمام 32236، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'طريق الأمير نايف بن عبدالعزيز، البحيرة، الدمام 32431، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'حي, شارع الملك خالد، الجلوية، الدمام 32246، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.7 نجمة ',
  'location': '13th Street, الدواسر، الدمام 32416، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'عائشة بنت أبي بكر، السويدي، السويدي، الرياض 12788، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': '7579 طريق الأمير محمد بن فهد بن عبدالعزيز، الاسكان، الدمام 32236، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'مطار الملك فهد الدولي، الدمام 32567، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود والعطور',
  'rating': '4.0 نجمة ',
  'location': 'شارع عمر بن الخطاب، الفيصلية، الدمام 32272، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.5 نجمة ',
  'location': '4845 أبو أمية المخزومي، 8048، المزروعية، الدمام 32414، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'النزهة، الدمام 32252، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'العنود، الدمام 32427، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': '8073 طريق الملك سعود, الصفا، الدمام 34222، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'طريق الدمام الفرعي، المونسية، الرياض 13246، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود فرع الثقبة',
  'rating': '4.1 نجمة ',
  'location': 'الثالث عشر، الثقبة، الخبر 34623، المملكة العربية السعودية'},
 {'store_name': '360 العربية للعود | Arabian Oud',
  'rating': '4.2 نجمة ',
  'location': 'مجمع الظهران، شارع فيصل بن فهد، حي، الدوحة الجنوبية، الظهران 34457، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'طريق الملك فهد، العدامة، الدمام 32242، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'طريق أنس ابن مالك، الصحافة، الرياض 13321، المملكة العربية السعودية'},
 {'store_name': '555 العربية للعود | Arabian Oud',
  'rating': '4.4 نجمة ',
  'location': 'الشاطئ الشرقي، الدمام 32414، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud | العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'VJ3X+6CF، النرجس، الرياض 13333، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'الجبيل البلد، الجبيل 35513، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'المستودعات، القطيف 32632، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'شارع ١٧ (د)، الشاطئ، القطيف 32617، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'طريق الملك عبدالله الفرعي، الحمراء، الرياض 13217، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'الإمام سعود بن عبد العزيز بن محمد، المغرزات، الرياض المملكة العربية السعودية'},
 {'store_name': '551 العربية للعود | Arabian Oud',
  'rating': '3.0 نجمة ',
  'location': 'حي, شارع الملك خالد، الجلوية، الدمام 32246، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '4.3 نجمة ',
  'location': 'حي, طريق ابو عبيدة عامر بن الجراح، الفيحاء، الرياض 14254، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود التخصصي',
  'rating': '4.4 نجمة ',
  'location': '7324 شارع التخصصي، العليا، الرياض 12342، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.5 نجمة ',
  'location': 'المونسية، الرياض 13253، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.4 نجمة ',
  'location': 'الندوة، حي الندوة، الرياض 14814، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': '7575 الطريق الدائري الشرقي الفرعي، القدس، الرياض 13214، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود 18',
  'rating': '5.0 نجمة ',
  'location': 'الملك فهد، الرياض 12261، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '4.0 نجمة ',
  'location': '8538 شارع أبي الأسود الدؤلي، النسيم الشرقي، الرياض 14243، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'طريق أبو عبيدة عامر بن الجراح، حي السلي، السلي، الرياض 14267، المملكة العربية السعودية'},
 {'store_name': '187 العربية للعود | Arabian Oud',
  'rating': '4.0 نجمة ',
  'location': 'زهير بن المسيب، الربوة، الرياض 12839، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': '6441 شارع حسان بن ثابت، النسيم الشرقي، الرياض 14241، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'طريق خريص، الروضة، الرياض 13211، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': '4239 طريق الملك فهد، العليا، 7062، الرياض 12311، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'اليرموك، الرياض 13251، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.7 نجمة ',
  'location': 'طريق الثمامة، المونسية، الرياض 13421، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'طريق الملك فهد، العقيق، الرياض 13515، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'الاسكان، الرياض 14317، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'الدانة، رأس تنورة 32817، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '4.1 نجمة ',
  'location': 'السلام، الخرج 16278، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.6 نجمة ',
  'location': 'طريق ابي بكر الصديق، النرجس، الرياض 13336، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.5 نجمة ',
  'location': 'الحارث بن عبدالله، حي الندوة، الرياض 14813، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.5 نجمة ',
  'location': 'حي, طريق الملك عبدالعزيز، الربيع، الرياض 13316، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.0 نجمة ',
  'location': '2937 طريق الملك عبدالله الفرعي، الورود، الرياض 12253، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.0 نجمة ',
  'location': 'الاندلس، الرياض 11564، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '4.4 نجمة ',
  'location': 'RQAA8666 3801 شبه الجزيرة، السعادة، الرياض 14255، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.5 نجمة ',
  'location': 'الريان،، الرياض المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'شارع الأمير بندر بن عبد العزيز، حي النهضة، النهضة، الرياض 13222، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود 185',
  'rating': '5.0 نجمة ',
  'location': '8320 شريح الحجازي، الروضة، الرياض 13213، المملكة العربية السعودية'},
 {'store_name': '720 العربية للعود | Arabian Oud',
  'rating': '4.0 نجمة ',
  'location': '8346 الترمذي، الشفا، الرياض 14713، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'شارع عنيزة، الريان، الرياض 14213، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'شارع الإمام أحمد بن حنبل، النسيم الغربي، الرياض 14233، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'طريق العروبة، العليا، الرياض 12244، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'Ayyubi Rd, صلاح الدين، Prince Faisal Bin Fahd Stadium, الرياض 12836، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': '3427 طريق الخرج، المنصورة، الرياض 12692، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': '3708 طريق العزيزية الفرعي، العزيزية، 6776 طريق العزيزية،، الرياض 14511، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'سلمان الفارسي، النهضة،،، النهضة، الرياض 13221، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'حي, شارع الأمير عبدالعزيز بن مساعد بن جلوي، السليمانية، الرياض 12221، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.5 نجمة ',
  'location': 'RURA7465, 2348 وادي الساحل، 7465, حي, الرمال, الرياض 13263، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': '3516 الوادي, هجرة لبن، الرياض 12936، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.6 نجمة ',
  'location': 'صالح الهاشمي، العقيق، الرياض 13511، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'طريق الملك فهد، السليمانية، الخرج 16278، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.5 نجمة ',
  'location': '6774 طريق الأمير محمد بن سلمان بن عبدالعزيز، قرطبة، 3548، الرياض 13247، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'طريق الإمام سعود بن عبدالعزيز بن محمد، النخيل، الرياض 12381، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'طريق الملك فهد الفرعي، السويدي، الرياض 12791، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'شارع الترمذي، أسواق العودة، الرياض 14712، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'شارع العليا، العليا، الرياض 12222، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'العربية للعود، شارع عبد الرحمن الغافقي، شارع عبدالرحمن الغافقي، الرياض ،، الرياض المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'السويدي العام، سلطانة، الرياض 12777، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'اسواق التميمى، شارع خالد بن الوليد، الاندلس، الرياض 13212، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.4 نجمة ',
  'location': 'وادي الصمان، الملك فيصل، الرياض 13215، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.3 نجمة ',
  'location': 'طريق نجم الدين الأيوبي الفرعي، طويق، الرياض 14931، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': '8484 طريق الملك فهد، 3392 طريق الملك فهد، المنتزة، الخرج 16439، الخرج 16439، المملكة العربية السعودية'}]

In [653]:
alarabya_list_9=pickle.load(open('alarabya_pkl\\alarabya_hail.pkl','rb'))
alarabya_list_9 = [dictionary for dictionary in alarabya_list_9 if 'الإسكندرية' not in dictionary['location'] and 'القاهرة' not in dictionary['location']]
print(len(alarabya_list_9))

alarabya_list_9

114

[{'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'النقرة، حائل 55431، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'طريق الملك عبدالعزيز، برزان، حائل 55428، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '3.5 نجمة ',
  'location': 'المنتزه الشرقي، حائل 55428، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '3.8 نجمة ',
  'location': 'طريق الملك عبدالله بن عبدالعزيز، النقرة، حائل 55432، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'الزبارة، حائل 55425، المملكة العربية السعودية'},
 {'store_name': '58 العربية للعود | Arabian Oud',
  'rating': '4.0 نجمة ',
  'location': '7673 الامير سلطان بن عبدالعزيز، 3515، المطار، حائل 55421، المملكة العربية السعودية'},
 {'store_name': '51 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': 'برزان، حائل 55428، المملكة العربية السعودية'},
 {'store_name': '57 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': '6459 باب الصفاقات، برزان، حائل 55428، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.0 نجمة ',
  'location': 'المنتزه الغربي، حائل 55427، المملكة العربية السعودية'},
 {'store_name': '853 العربية للعود | Arabian Oud',
  'rating': '4.3 نجمة ',
  'location': 'فرع العربية للعود بصالات النويصر،، شارع الملك خالد، ،، حائل 55424، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': '4651، المنتزه الشرقي،، حائل 55428، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '1.9 نجمة ',
  'location': 'جراند مول, طريق الملك سعود، النقرة، حائل 55431، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'حي, الطريق العام, السويفلة، حائل 55481، المملكة العربية السعودية'},
 {'store_name': '973 العربية للعود | Arabian Oud',
  'rating': '4.4 نجمة ',
  'location': 'فرع العربية للعود بالأمير نايف، 0،، حائل المملكة العربية السعودية'},
 {'store_name': 'Dkhoun | دخون',
  'rating': '4.4 نجمة ',
  'location': 'Grand Mall, حائل المملكة العربية السعودية'},
 {'store_name': 'العربية للعود Arabian Oud',
  'rating': '4.4 نجمة ',
  'location': 'Juhaina Sq Mall of Arabia, Unit No. H96, محافظة الجيزة 12573'},
 {'store_name': 'العربيه للعود',
  'rating': '3.4 نجمة ',
  'location': 'طارق بن زياد، الرزيقية، العلا 43561، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '4.4 نجمة ',
  'location': 'مخطط الرواف 5070, بريدة 52379، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'طريق الملك عبدالله، الصفراء، بريدة 52383، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'شارع عمر بن سليم، سلطانة، بريدة 52375، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'طريق عثمان بن عفان، الصفراء، بريدة 52381، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'طريق الملك سعود، السوق القديم، تبوك، دومة الجندل 74632، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.6 نجمة ',
  'location': 'المطر، 72341،، سكاكا المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'الصفراء، بريدة 52382، المملكة العربية السعودية'},
 {'store_name': '76 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': 'شارع الملك خالد بن عبدالعزيز، الملك فهد، الرس 58851، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود Arabain Oud',
  'rating': '4.9 نجمة ',
  'location': 'الفهد، شارع السوق التجاري،، البكيرية 51941، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود فرع التحلية',
  'rating': '3.4 نجمة ',
  'location': 'طريق الامير محمد بن عبدالعزيز، العريض، المدينة المنورة 42314، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود |Arabian Oud',
  'rating': '4.4 نجمة ',
  'location': '3585، مروج الأمير، تبوك 47315، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': '4049، النازية، بريدة 52359، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'الجوف بلازا .. 6902 طريق الملك سعود سكاكا السعودية،، سكاكا المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'طريق أنس ابن مالك، الصحافة، الرياض 13321، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'طريق فيصل بن عبدالعزيز، البلدية، حفر الباطن 39921، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'القادسية، رياض الخبراء 52722، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'طريق الملك عبدالعزيز، الحي الإداري، سكاكا 72341، المملكة العربية السعودية'},
 {'store_name': '79 العربية للعود | Arabian Oud',
  'rating': '3.6 نجمة ',
  'location': 'حي الإسكان، بريدة 52384، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'الروضة، خيبر 43488، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.6 نجمة ',
  'location': 'الراشد ميغا مول، شظاة، المدينة المنورة 42361، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.6 نجمة ',
  'location': 'الشيرمي، البدائع 56352، المملكة العربية السعودية'},
 {'store_name': '548 العربية للعود | Arabian Oud',
  'rating': '4.2 نجمة ',
  'location': 'Sakakah Road Nayomi Al Jouf Plaza، سكاكا 72341، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'الامام البخاري، الدفاع، المدينة المنورة 42377، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '4.1 نجمة ',
  'location': 'شارع الملك خالد بن عبدالعزيز، الملك فهد، الرس 58881، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.4 نجمة ',
  'location': 'شارع الحسن بن عبدالعزيز، العزيزية، المدينة المنورة 42377، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'طريق الملك عبدالله، الملز، رفحاء 76333، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'طريق الملك عبدالعزيز، عقلة الصقور 54714، المملكة العربية السعودية'},
 {'store_name': '503 العربية للعود | Arabian Oud',
  'rating': '4.7 نجمة ',
  'location': '8030، Al Henakiyah 42639،، الحناكية 42639، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'طريق سلطانة، الراية، المدينة المنورة 42312، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud | العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'VJ3X+6CF، النرجس، الرياض 13333، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'District, AL Waha Mall, King Fahad Rd، الملك خالد، الرس 58877، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': '7011، عين ابن فهيد 52454، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود Arabian Oud',
  'rating': '3.8 نجمة ',
  'location': '8552، حي الريان،، عنيزة 56241، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'المصيف، المروج،،, تبوك 47321، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'طريق الملك عبدالله الفرعي، الحمراء، الرياض 13217، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'العزيزية، العلا 43511، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'حي وسط المدينة، 3555, عنيزة 56219، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.0 نجمة ',
  'location': '2937 طريق الملك عبدالله الفرعي، الورود، الرياض 12253، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': '3460 طريق الامير محمد بن عبدالعزيز،، 7210 Prince Mohammed Bin Abdulaziz St، المدينة المنورة 42314، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'الامام البخاري، الدفاع، المدينة المنورة 42374، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'المبعوث، الأمير مقرن ،، المدينة المنورة 42362، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.6 نجمة ',
  'location': 'طريق صلاح الدين الايوبي، شوران، المدينة المنورة 42386، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'FM2H+X5، مذينب، المدينة المنورة 42364، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.3 نجمة ',
  'location': 'طريق نجم الدين الأيوبي الفرعي، طويق، الرياض 14931، المملكة العربية السعودية'},
 {'store_name': '905 العربية للعود | Arabian Oud',
  'rating': '4.2 نجمة ',
  'location': 'الشارع العام سوق الذهب، الحائط 57363، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'KGAB7336، 7336 خديجة بنت خويلد، 5635، الصفا، تبوك 47919، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': '، حي، الخالدية، طريق الأمير محمد بن عبد العزيز، المدينة المنورة 42317، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.5 نجمة ',
  'location': 'حي, طريق الملك عبدالعزيز، الربيع، الرياض 13316، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.7 نجمة ',
  'location': 'الحديقة، المدينة المنورة 42383، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'طريق الأمير نايف بن عبدالعزيز، البركة، المدينة المنورة 42332، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'الامير عبدالمجيد بن عبدالعزيز، الشريبات، المدينة المنورة 42317، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'الطريق العام, رفائع الجمش 58262، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.4 نجمة ',
  'location': 'علي بن ابي طالب، السعادة، تبوك 47914، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.5 نجمة ',
  'location': 'المونسية، الرياض 13253، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'طريق أبو عبيدة عامر بن الجراح، حي السلي، السلي، الرياض 14267، المملكة العربية السعودية'},
 {'store_name': '66 العربية للعود | Arabian Oud',
  'rating': '4.0 نجمة ',
  'location': 'حي الجردة، بريدة 52354، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'العليا، تبوك 47911، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': '2418 طريق سلطانة، بئر عثمان، المدينة المنورة 42331، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود التخصصي',
  'rating': '4.4 نجمة ',
  'location': '7324 شارع التخصصي، العليا، الرياض 12342، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': '7575 الطريق الدائري الشرقي الفرعي، القدس، الرياض 13214، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'القصواء، المدينة المنورة 42391، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'طريق الملك فهد، الفيحاء، المجمعة 15362، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.4 نجمة ',
  'location': 'الندوة، حي الندوة، الرياض 14814، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.6 نجمة ',
  'location': 'طريق ابي بكر الصديق، النرجس، الرياض 13336، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'طريق خريص، الروضة، الرياض 13211، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'طريق الأمير عبد المجيد، الجمعة، المدينة المنورة 42316، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'طريق قباء، الجمعة، المدينة المنورة 42315، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'جوهرة، عرعر 73551، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'طريق عبدالعزيز بن مساعد، الادارية، رفحاء 76313، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'الخالدية، الدرعية 13713، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '4.3 نجمة ',
  'location': 'الفيصلية، الدوادمي 17441، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.7 نجمة ',
  'location': 'طريق الثمامة، المونسية، الرياض 13421، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': '4239 طريق الملك فهد، العليا، 7062، الرياض 12311، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '4.0 نجمة ',
  'location': 'الامير عبدالمجيد بن عبدالعزيز، المروج ب،، تبوك 47312، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.5 نجمة ',
  'location': 'العباس بن عبادة، القصواء، المدينة المنورة 42391، المملكة العربية السعودية'},
 {'store_name': '609 العربية للعود | Arabian Oud',
  'rating': '4.1 نجمة ',
  'location': 'فرع العربية للعود بالعثيم عكيرشة ، 0، القصيم القصيم المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.4 نجمة ',
  'location': 'مهد الذهب 44411، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'اليرموك، الرياض 13251، المملكة العربية السعودية'},
 {'store_name': '968 العربية للعود | Arabian Oud',
  'rating': '4.1 نجمة ',
  'location': 'فرع العربية للعود بعنيزة حي المنتزه، 0، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': '6441 شارع حسان بن ثابت، النسيم الشرقي، الرياض 14241، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'الخالدية، حفر الباطن 39953، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'شارع الاندلس، طبرجل 74765، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.5 نجمة ',
  'location': '6774 طريق الأمير محمد بن سلمان بن عبدالعزيز، قرطبة، 3548، الرياض 13247، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.7 نجمة ',
  'location': 'Riyadh Front، مطار الملك خالد الدولي، الرياض 11564، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.1 نجمة ',
  'location': 'الشفاء، شقراء 15557، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.5 نجمة ',
  'location': '5JR2+5W، ساجر 17658، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'الاسكان، الرياض 14317، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود بالشارع العام (Arabianoud Tabuk )',
  'rating': '4.4 نجمة ',
  'location': '3673 الامام محمد بن عبدالوهاب، المنشية القديمة، تبوك 47914، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.6 نجمة ',
  'location': 'حي, الملك عبد العزيز، ذا فيو مول - طريق مكة المكرمة فرعي المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': '3516 الوادي, هجرة لبن، الرياض 12936، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '2.8 نجمة ',
  'location': 'الجديدة، المذنب 56634، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': '88PP+38F، السديرية، القريات 77481، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.6 نجمة ',
  'location': 'صالح الهاشمي، العقيق، الرياض 13511، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'الدرع، الدوادمي 17463، المملكة العربية السعودية'},
 {'store_name': '323 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': 'King Fahd Rd, الصخيرات، العلا 43512، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'أبو بكر الصديق، المحمدية، حفر الباطن 39911، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'الملقا, طريق الامام سعود بن فيصل الفرعي المملكة العربية السعودية'}]

In [654]:
alarabya_list_10=pickle.load(open('alarabya_pkl\\alarabya_buraidah.pkl','rb'))
alarabya_list_10 = [dictionary for dictionary in alarabya_list_10 if 'الإسكندرية' not in dictionary['location'] and 'القاهرة' not in dictionary['location']]
print(len(alarabya_list_10))

alarabya_list_10

120

[{'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'الصفراء، بريدة 52382، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '4.4 نجمة ',
  'location': 'مخطط الرواف 5070, بريدة 52379، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'طريق الملك عبدالله، الصفراء، بريدة 52383، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'شارع عمر بن سليم، سلطانة، بريدة 52375، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': '4049، النازية، بريدة 52359، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'طريق عثمان بن عفان، الصفراء، بريدة 52381، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود Arabain Oud',
  'rating': '4.9 نجمة ',
  'location': 'الفهد، شارع السوق التجاري،، البكيرية 51941، المملكة العربية السعودية'},
 {'store_name': '609 العربية للعود | Arabian Oud',
  'rating': '4.1 نجمة ',
  'location': 'فرع العربية للعود بالعثيم عكيرشة ، 0، القصيم القصيم المملكة العربية السعودية'},
 {'store_name': '79 العربية للعود | Arabian Oud',
  'rating': '3.6 نجمة ',
  'location': 'حي الإسكان، بريدة 52384، المملكة العربية السعودية'},
 {'store_name': '66 العربية للعود | Arabian Oud',
  'rating': '4.0 نجمة ',
  'location': 'حي الجردة، بريدة 52354، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.7 نجمة ',
  'location': '9W2W+C65، المنتزه،، الامير فيصل بن بندر بن عبدالعزيز،، بريدة 52381، المملكة العربية السعودية'},
 {'store_name': '968 العربية للعود | Arabian Oud',
  'rating': '4.1 نجمة ',
  'location': 'فرع العربية للعود بعنيزة حي المنتزه، 0، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'حي وسط المدينة، 3555, عنيزة 56219، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود Arabian Oud',
  'rating': '3.8 نجمة ',
  'location': '8552، حي الريان،، عنيزة 56241، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'القادسية، رياض الخبراء 52722، المملكة العربية السعودية'},
 {'store_name': 'الماجد للعود',
  'rating': '4.6 نجمة ',
  'location': '8437 شارع البخاري، حي الريان، بريدة 52379، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.6 نجمة ',
  'location': 'الشيرمي، البدائع 56352، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'District, AL Waha Mall, King Fahad Rd، الملك خالد، الرس 58877، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '4.1 نجمة ',
  'location': 'شارع الملك خالد بن عبدالعزيز، الملك فهد، الرس 58881، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': '7011، عين ابن فهيد 52454، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '2.8 نجمة ',
  'location': 'الجديدة، المذنب 56634، المملكة العربية السعودية'},
 {'store_name': '76 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': 'شارع الملك خالد بن عبدالعزيز، الملك فهد، الرس 58851، المملكة العربية السعودية'},
 {'store_name': '612 العربية للعود | Arabian Oud',
  'rating': '4.4 نجمة ',
  'location': 'فرع العربية للعود بالزلفي الشارع العام، شارع العام ، القصيم القصيم المملكة العربية السعودية'},
 {'store_name': 'Dkhoun | دخون',
  'rating': '3.9 نجمة ',
  'location': '6803-6881 طريق عمر بن الخطاب، حي الريان، بريدة 52379، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'طريق الملك فهد، الفيحاء، المجمعة 15362، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'النقرة، حائل 55431، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': '15313، حوطة سدير 15313، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.5 نجمة ',
  'location': '5JR2+5W، ساجر 17658، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'طريق الملك عبدالعزيز، برزان، حائل 55428، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'الدرع، الدوادمي 17463، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'الطريق العام, رفائع الجمش 58262، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'طريق الملك عبدالعزيز، عقلة الصقور 54714، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود التخصصي',
  'rating': '4.4 نجمة ',
  'location': '7324 شارع التخصصي، العليا، الرياض 12342، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '4.3 نجمة ',
  'location': 'الفيصلية، الدوادمي 17441، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'قرطبة، الرياض 13244، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'الملقا, طريق الامام سعود بن فيصل الفرعي المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'العربية للعود، شارع عبد الرحمن الغافقي، شارع عبدالرحمن الغافقي، الرياض ،، الرياض المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.1 نجمة ',
  'location': 'الشفاء، شقراء 15557، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'عبدالرحمن الداخل، طويق، الرياض 14922، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': '4239 طريق الملك فهد، العليا، 7062، الرياض 12311، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'الزبارة، حائل 55425، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'طريق أنس ابن مالك، الصحافة، الرياض 13321، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'طريق الإمام سعود بن عبدالعزيز بن محمد، النخيل، الرياض 12381، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'الإمام سعود بن عبد العزيز بن محمد، المغرزات، الرياض المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'اليرموك، الرياض 13251، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'Ayyubi Rd, صلاح الدين، Prince Faisal Bin Fahd Stadium, الرياض 12836، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'شارع التخصصي،، المعذر الشمالي، الرياض 12334، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': '3516 الوادي, هجرة لبن، الرياض 12936، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.6 نجمة ',
  'location': 'طريق ابي بكر الصديق، النرجس، الرياض 13336، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'طريق العروبة، العليا، الرياض 12244، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'طريق الملك عبدالله الفرعي، الحمراء، الرياض 13217، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'حي, شارع الأمير عبدالعزيز بن مساعد بن جلوي، السليمانية، الرياض 12221، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'السويدي العام، سلطانة، الرياض 12777، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': '7575 الطريق الدائري الشرقي الفرعي، القدس، الرياض 13214، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود 23',
  'rating': '4.1 نجمة ',
  'location': '2591 الامام تركي بن عبدالله بن محمد، الديرة، الرياض 12634، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'طريق هارون الرشيد، الفيحاء، الرياض 14254، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'طريق الأمير نايف بن عبدالعزيز، الملك فهد، الرياض 12273، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.7 نجمة ',
  'location': 'طريق الثمامة، المونسية، الرياض 13421، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.6 نجمة ',
  'location': '3201 شارع الثميري، الديرة، 3201 شارع الثميري، الديرة 6869، الرياض 12634، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'طريق الملك فهد الفرعي، السويدي، الرياض 12791، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'شارع عباس بن قيس، أم الحمام الغربي، الرياض 12322، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'طريق الملك فهد، العقيق، الرياض 13515، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'شارع عنيزة، الريان، الرياض 14213، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.5 نجمة ',
  'location': 'المونسية، الرياض 13253، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.7 نجمة ',
  'location': 'طريق المدينة المنورة، ظهرة البديعة، الرياض 12982، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'شارع الأمير بندر بن عبد العزيز، حي النهضة، النهضة، الرياض 13222، المملكة العربية السعودية'},
 {'store_name': '58 العربية للعود | Arabian Oud',
  'rating': '4.0 نجمة ',
  'location': '7673 الامير سلطان بن عبدالعزيز، 3515، المطار، حائل 55421، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': '3427 طريق الخرج، المنصورة، الرياض 12692، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'الخالدية، الدرعية 13713، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': '6426 طريق ابن تيمية، الشفا، الرياض 14713، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.7 نجمة ',
  'location': 'Riyadh Front، مطار الملك خالد الدولي، الرياض 11564، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'الاسكان، الرياض 14317، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.5 نجمة ',
  'location': '6774 طريق الأمير محمد بن سلمان بن عبدالعزيز، قرطبة، 3548، الرياض 13247، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.4 نجمة ',
  'location': 'الندوة، حي الندوة، الرياض 14814، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.6 نجمة ',
  'location': 'صالح الهاشمي، العقيق، الرياض 13511، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.8 نجمة ',
  'location': '8820 شارع حمزة بن عبدالمطلب، السويدي الغربي، الرياض 12991، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'طريق عرفات الفرعي، الدار البيضاء، الرياض 14518، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'طريق خريص، الروضة، الرياض 13211، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'شارع العليا، العليا، الرياض 12222، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': '3708 طريق العزيزية الفرعي، العزيزية، 6776 طريق العزيزية،، الرياض 14511، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'سلمان الفارسي، النهضة،،، النهضة، الرياض 13221، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.5 نجمة ',
  'location': 'حي, طريق الملك عبدالعزيز، الربيع، الرياض 13316، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '3.9 نجمة ',
  'location': 'شارع جرير، الملز، الرياض 12836، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود والعطور الشرقية',
  'rating': '4.0 نجمة ',
  'location': 'الشفا، الرياض 13781، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.0 نجمة ',
  'location': '2937 طريق الملك عبدالله الفرعي، الورود، الرياض 12253، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': '6441 شارع حسان بن ثابت، النسيم الشرقي، الرياض 14241، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'حي الزهور، القويعية 19248، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'المشتل، الحزم، الرياض 14964، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'طريق الملك عبدالعزيز، طويق، محافظة المزاحمية 19671، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.0 نجمة ',
  'location': 'الاندلس، الرياض 11564، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'أبو بكر الصديق، المحمدية، حفر الباطن 39911، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.3 نجمة ',
  'location': 'طريق نجم الدين الأيوبي الفرعي، طويق، الرياض 14931، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'اسواق التميمى، شارع خالد بن الوليد، الاندلس، الرياض 13212، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'شارع الترمذي، أسواق العودة، الرياض 14712، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود 4',
  'rating': '3.8 نجمة ',
  'location': '7093، الرياض 12262، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود 359',
  'rating': '4.2 نجمة ',
  'location': 'QPJJ+888، غرناطة، الرياض 13241، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'ابن الرطبي، الشفا، الرياض 14721، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'طريق الملك عبدالعزيز، الحي الإداري، سكاكا 72341، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'الخالدية، حفر الباطن 39953، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': '8077 شارع الإمام أبي حنيفة، العريجاء الغربية، 3129 الامام ابي حنيفة،، الرياض 12966، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.7 نجمة ',
  'location': 'طريق الملك فهد الفرعي، العليا، المملكة،، الرياض 12214، المملكة العربية السعودية'},
 {'store_name': '57 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': '6459 باب الصفاقات، برزان، حائل 55428، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'طريق الملك عبدالعزيز، البديع الغربي، ضرما 19869، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود فرع الازدهار',
  'rating': '3.8 نجمة ',
  'location': 'طريق عثمان بن عفان, حي الازدهار، الرياض 12485، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'حي, الطريق العام, السويفلة، حائل 55481، المملكة العربية السعودية'},
 {'store_name': '746 العربية للعود',
  'rating': '3.7 نجمة ',
  'location': '3243 شارع الطائف، ظهرة لبن، الرياض 13782، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود 1070',
  'rating': '4.9 نجمة ',
  'location': 'حي, طريق الملك سعود، الشفاء، شقراء 15571، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'طريق الدمام الفرعي، المونسية، الرياض 13246، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': '4651، المنتزه الشرقي،، حائل 55428، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود 1091',
  'rating': '4.4 نجمة ',
  'location': '6869 الطريق الدائري الشرقي، الجزيرة، الرياض 14251، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.0 نجمة ',
  'location': 'المنتزه الغربي، حائل 55427، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.5 نجمة ',
  'location': 'RURA7465, 2348 وادي الساحل، 7465, حي, الرمال, الرياض 13263، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.8 نجمة ',
  'location': 'حي, وادي الاعشاب، ديراب، الرياض 14969، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.6 نجمة ',
  'location': 'طريق صلاح الدين الايوبي، شوران، المدينة المنورة 42386، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'طريق الامام سعود بن عبدالعزيز بن محمد الفرعي، المرسلات، الرياض 12464، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '4.2 نجمة ',
  'location': 'الملقا، طريق الامام سعود بن فيصل الفرعي المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'الامام البخاري، الدفاع، المدينة المنورة 42377، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': '3460 طريق الامير محمد بن عبدالعزيز،، 7210 Prince Mohammed Bin Abdulaziz St، المدينة المنورة 42314، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': '، حي، الخالدية، طريق الأمير محمد بن عبد العزيز، المدينة المنورة 42317، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.4 نجمة ',
  'location': 'Othaim Market, الامير تركي بن عبدالعزيز الثاني، Opposit, الرياض 12282، المملكة العربية السعودية'}]

In [655]:
alarabya_list_11=pickle.load(open('alarabya_pkl\\alarabya_khamis_mushiat.pkl','rb'))
alarabya_list_11 = [dictionary for dictionary in alarabya_list_11 if 'الإسكندرية' not in dictionary['location'] and 'القاهرة' not in dictionary['location']]
print(len(alarabya_list_11))

alarabya_list_11

108

[{'store_name': 'العربيه للعود',
  'rating': '3.9 نجمة ',
  'location': 'أم سرور، خميس مشيط 62461، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '3.7 نجمة ',
  'location': 'شارع الملك فيصل، وسط المدينة، أبها 62521، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': '2555, مخطط الموسى, خميس مشيط 62463، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'المنسك، حي، أبها 62581، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '4.3 نجمة ',
  'location': 'شارع وهب بن مسرة, المروج، أبها 62527، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'Avenue، طريق الملك خالد،، ذلالة، خميس مشيط 62411، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.5 نجمة ',
  'location': 'شارع الملك خالد، الشفاء، خميس مشيط 62433، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '4.1 نجمة ',
  'location': '8379 طريق الأمير سلطان، الموسى، خميس مشيط 62463، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.7 نجمة ',
  'location': 'الواحة، خميس مشيط 62456، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': '5457 طريق الملك فهد، خميس مشيط 62461، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.4 نجمة ',
  'location': 'الواحة سنتر، طريق الملك فهد، خميس مشيط 62434، المملكة العربية السعودية'},
 {'store_name': '578 العربية للعود | Arabian Oud',
  'rating': '3.7 نجمة ',
  'location': 'الرونة، أحد رفيدة 62447، المملكة العربية السعودية'},
 {'store_name': '498 العربية للعود | Arabian Oud',
  'rating': '4.0 نجمة ',
  'location': '8P4J+CX3، العرق الجنوبي، خميس مشيط 62461، المملكة العربية السعودية'},
 {'store_name': '1224 العربية للعود | Arabian Oud',
  'rating': '4.0 نجمة ',
  'location': 'الراشد مول, طريق الملك فهد، البديع، أبها 12839، المملكة العربية السعودية'},
 {'store_name': '716 العربية للعود | Arabian Oud',
  'rating': '3.0 نجمة ',
  'location': 'العرق الجنوبي، خميس مشيط 62461، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'حي, طريق الملك عبدالعزيز، الشرفية، أبها 62542، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '5.0 نجمة ',
  'location': '8452 جنوبا الى احد رفيده و شمالا الى خميس مشيط، سكن المدينة العسكرية، 3615، خميس مشيط 62413، المملكة العربية السعودية'},
 {'store_name': '131 العربية للعود | Arabian Oud',
  'rating': '3.8 نجمة ',
  'location': '8770، السلام، خميس مشيط 62461، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '4.3 نجمة ',
  'location': 'حي, طريق الملك عبدالعزيز، ذرة، أبها 62521، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '5.0 نجمة ',
  'location': 'Unnamed Road 62497، المملكة العربية السعودية'},
 {'store_name': '1228 العربية للعود | Arabian Oud',
  'rating': '3.7 نجمة ',
  'location': '8772 البلد 13, حي السلام, AKPA3785، 3785, خميس مشيط 62461، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.0 نجمة ',
  'location': '4608 طريق الملك عبدالعزيز، السد، أبها 62521، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '5.0 نجمة ',
  'location': '9061 الشارع العام، AGPB2375، 2375، آل عامر 62263، المملكة العربية السعودية'},
 {'store_name': 'الماجد للعود',
  'rating': '4.1 نجمة ',
  'location': 'البديع، أبها 62581، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.6 نجمة ',
  'location': 'HMPW+J9، عريجة، وادي ابن هشبل 62931، المملكة العربية السعودية'},
 {'store_name': 'درعه DERAAH',
  'rating': '4.2 نجمة ',
  'location': '6QW7+6VV، طريق الملك خالد،،، ذلالة، Khamis Avenue، خميس مشيط 62411، المملكة العربية السعودية'},
 {'store_name': 'الدخيل للعود AL-Dakheel Oud',
  'rating': '3.9 نجمة ',
  'location': 'طريق الملك عبدالعزيز، الشفاء، أبها 62521، المملكة العربية السعودية'},
 {'store_name': 'الماجد للعود',
  'rating': '4.2 نجمة ',
  'location': 'مذركير الراشد، البديع، أبها 62581، المملكة العربية السعودية'},
 {'store_name': 'درعه DERAAH',
  'rating': '4.3 نجمة ',
  'location': '6HF3+6XW، 6HF4+622، أبها 11551، المملكة العربية السعودية'},
 {'store_name': 'Abdul Samad Al Qurashi',
  'rating': '4.1 نجمة ',
  'location': 'خميس مشيط طريق المدينة العسكرية الخميس افينيو مول، خميس مشيط المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.6 نجمة ',
  'location': 'مجمع الغنيم، طريق الملك فيصل، الخالدية، Muhayil,Abha 63687، المملكة العربية السعودية'},
 {'store_name': '857 العربية للعود | Arabian Oud',
  'rating': '4.0 نجمة ',
  'location': '76MR+H2، الجرف 63454، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.4 نجمة ',
  'location': 'طريق الملك خالد بن عبدالعزيز،، الروضة، سراة عبيدة 64532، المملكة العربية السعودية'},
 {'store_name': '745 العربية للعود | Arabian Oud',
  'rating': '4.1 نجمة ',
  'location': 'H6G5+G3، طريب 62828، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.7 نجمة ',
  'location': 'طريق الملك فيصل، الفيصلية، محايل عسير 63687، المملكة العربية السعودية'},
 {'store_name': 'الدخيل للعود',
  'rating': '3.9 نجمة ',
  'location': 'شارع القاعدة العسكرية، ذلالة، خميس مشيط 62411، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'الفيصلية، محايل عسير 63715، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': '44FJ+H2، طريق الملك فيصل، السلام، النماص 67393، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '5.0 نجمة ',
  'location': '6142 طريق الملك عبدالله، حي الزهور، AEPA3680، 3680، بارق 63916، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'طريق الكورنيش، الشاطيء، جازان 82811، المملكة العربية السعودية'},
 {'store_name': '871 العربية للعود | Arabian Oud',
  'rating': '4.7 نجمة ',
  'location': 'P7PC+WC، الدرب 89888، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'P7RH+9V، الدرب 89699، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.7 نجمة ',
  'location': 'طريق الملك فهد، تاج مول، أبو عريش 84416، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'الملك فهد،، الملك فهد، أبو عريش 84522، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'بارق 63916، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': '5، الشريعة 87587، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود والعطور',
  'rating': '3.6 نجمة ',
  'location': 'Q97H+M2، الصفة 28939، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'طريق الكورنيش، كادي مول، جازان 82725، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'Dhahran Al Janub، Dhahran 64271، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.6 نجمة ',
  'location': 'طريق الملك عبدالعزيز، 6349، GBMA3194، 3194، ضمد 84971، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.5 نجمة ',
  'location': 'الطريق العام, حبونا 66342، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '5.0 نجمة ',
  'location': '6714، الباحة 65522 3341، 65522، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.4 نجمة ',
  'location': '3033 طريق الملك عبدالعزيز، الرحاب، 7228 طريق الملك عبدالعزيز،، صبيا 85457، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.6 نجمة ',
  'location': 'طريق احمد بن عبدالعزيز، القوز 28829، المملكة العربية السعودية'},
 {'store_name': '1248 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': 'طريق الملك عبدالعزيز، 6316, GBMA3134، 3134, ضمد 84971، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'طريق بدر، المجاردة 63971، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'طريق الداير وادي الجنية، الدائر 83862، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': '15، تنومة 62795، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'شارع الملك عبدالعزيز, حي الشامية، جازان 82714، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.8 نجمة ',
  'location': 'جرير، النخيل، السليل 18621، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': '3980، بحر ابو سكينة 63585، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.0 نجمة ',
  'location': '6221 2054 طريق الملك عبدالعزيز، المجد، صبيا 85534، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud العربية للعود',
  'rating': '5.0 نجمة ',
  'location': '6193 فهد بن عبدالعزيز, حي الاثايبة, NJMB2554، 2554, نجران 66258، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '5.0 نجمة ',
  'location': 'الطريق العام, نمرة 65439، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.0 نجمة ',
  'location': 'طريق الملك فهد بن عبدالعزيز، القنفذة 28822، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '4.1 نجمة ',
  'location': 'H5V3+VV4، شارع شرق النهضه، السلامة، جدة 28383، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': '8764 طريق الملك فهد، الشاطيء، جازان 82727، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.6 نجمة ',
  'location': 'الملك عبد العزيز، القنفذة 28821، المملكة العربية السعودية'},
 {'store_name': 'العربية للعطور',
  'rating': '3.8 نجمة ',
  'location': 'العزيزية، بللسمر 62767، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'الملك عبدالله، بيشة 67712، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.3 نجمة ',
  'location': 'المستشفى، بلجرشي 65635، المملكة العربية السعودية'},
 {'store_name': '756 العربية للعود | Arabian Oud',
  'rating': '3.9 نجمة ',
  'location': 'العزيزية، صبيا 85297، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.1 نجمة ',
  'location': 'العقيق 65914، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '5.0 نجمة ',
  'location': 'الشروق، طريق الملك فهد - مول, الباحة المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'طريق الملك فهد، النسيم، قلوة 65335، المملكة العربية السعودية'},
 {'store_name': '1227 العربية للعود | Arabian Oud',
  'rating': '1.0 نجمة ',
  'location': 'الشرقية، القنفذة 28822، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.5 نجمة ',
  'location': 'طريق سليمان الراجحي، حي القيم الأعلى، الطائف 26551، المملكة العربية السعودية'},
 {'store_name': '364 العربية للعود | Arabian Oud',
  'rating': '3.5 نجمة ',
  'location': 'العزيزية، سبت العلاية 67542، المملكة العربية السعودية'},
 {'store_name': '1213 العربية للعود | Arabian Oud',
  'rating': '4.4 نجمة ',
  'location': 'NJUB7872، 7872 حمد ابن ماضي, 3844, حي أبا السعود, نجران 66281، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.6 نجمة ',
  'location': 'الملك عبدالعزيز, النصباء 65581، المملكة العربية السعودية'},
 {'store_name': '717 العربية للعود | Arabian Oud',
  'rating': '2.3 نجمة ',
  'location': 'Al Husayn Market, Al Husayn rd 66273، المملكة العربية السعودية'},
 {'store_name': '262 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': 'شارع حلي، الأزهار، القنفذة 28821، المملكة العربية السعودية'},
 {'store_name': '776 العربية للعود | Arabian Oud',
  'rating': '4.3 نجمة ',
  'location': '2687 طريق المطار، جازان 82722، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': '3144، 7842، النزهة، الباحة 65711، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.6 نجمة ',
  'location': 'VHQC+P6W، جازان 82722، المملكة العربية السعودية'},
 {'store_name': '701 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': 'التاج مول, طريق الملك فهد، بن عبدالعزيز, أبو عريش 82511، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': '7HF3QC8M+FV، المخواة 65614، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'HMJ6+XJ, 211، نمرة 65466، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.7 نجمة ',
  'location': 'طريق الملك خالد، الخزامى، بيشة 67711، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': '4020 شارع الامير سلطان، الخزامى، بيشة 67711، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud |العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'الخالدية، 4177، الخالدية، نجران 66261 9299, نجران 66261، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'بلجرشي البلد ش الملك فهد مقابل مجمع بن زوما، بلجرشي المملكة العربية السعودية'},
 {'store_name': '923 العربية للعود | Arabian Oud',
  'rating': '3.9 نجمة ',
  'location': 'نجران 66252، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '4.0 نجمة ',
  'location': 'السداد، الطائف 26514، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'حي, شارع العزيزية العام، الجامعة، مكة 24243، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'شارع الملك سعود، الشرقية، الطائف 26513، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.3 نجمة ',
  'location': '2645 8840 طريق الملك عبدالله، السليمانية، جدة 22253، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'الجامعة، مكة 24243، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': '9674، 3491 طريق الملك عبد العزيز، نجران 66263 المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'شارع إبراهيم الجفالي، مكة 24372، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.7 نجمة ',
  'location': 'طريق الملك عبدالعزيز، مخطط العريسة الشمالي 66243، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'طريق الملك عبدالعزيز، الصفا، جازان 82721، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': '2167 محمد صالح باشراحيل، الراشدية، مكة 24268، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.6 نجمة ',
  'location': 'شارع الخمسين، حي الجال، الطائف 26523، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'بلجرشي مول، المحمدية، بلجرشي 65627، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'Taibah District, جدة 23831، المملكة العربية السعودية'},
 {'store_name': '264 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': 'TADC2314، 2314 سعد بن بخيت, حي شبرا, 7070, الطائف 26523، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '3.6 نجمة ',
  'location': '7248، 2415 سعود الفيصل، الصفا،، جدة 23451، المملكة العربية السعودية'}]

In [656]:
alarabya_list_12=pickle.load(open('alarabya_pkl\\alarabya_jubil.pkl','rb'))
alarabya_list_12 = [dictionary for dictionary in alarabya_list_12 if 'الإسكندرية' not in dictionary['location'] and 'القاهرة' not in dictionary['location']]
print(len(alarabya_list_12))

alarabya_list_12

112

[{'store_name': 'Arabian Oud',
  'rating': '4.1 نجمة ',
  'location': 'المدرسة, حي طيبة، الجبيل 35514، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'الفيصلية، النعيرية 37482، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'الجبيل البلد، الجبيل 35513، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'الحويلات، الجبيل 35718، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود |Arabian Oud',
  'rating': '3.6 نجمة ',
  'location': '9185 الملك فيصل الغربي، W, الجبيل 35518، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'حي, طريق الملك عبدالعزيز، البحر، الجبيل 35419، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.6 نجمة ',
  'location': 'الفناتير، The Galleria Mall, Al Khamis Road، الجبيل 35811، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '5.0 نجمة ',
  'location': 'الأمير سلطان بن عبدالعزيز، الفيصلية، النعيرية 37485، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'مطار الملك فهد الدولي، الدمام 32567، المملكة العربية السعودية'},
 {'store_name': 'الماجد للعود',
  'rating': '4.1 نجمة ',
  'location': 'الامير محمد، الجبيل البلد، الجبيل 35514، المملكة العربية السعودية'},
 {'store_name': 'عبد الصمد القرشي للعود والعطورات',
  'rating': '3.9 نجمة ',
  'location': 'شارع الفناتير بجوار صيدلية النهدي، الجبيل المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '4.5 نجمة ',
  'location': 'P356+MJV، نواف بن عبدالعزيز، شارع الأمير، رأس تنورة المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '4.3 نجمة ',
  'location': 'مول دارين, Khaleej Rd, العزيزية، الدمام 32424، المملكة العربية السعودية'},
 {'store_name': 'درعه DERAAH',
  'rating': '4.5 نجمة ',
  'location': '8369 الملك فيصل الغربي، ميناء الملك فهد الصناعي، 3404 XJHW+XXG الجبيل SA، الجبيل 35518، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.5 نجمة ',
  'location': 'شارع عمر بن الخطاب، الفيصلية، الدمام 32272، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'المستودعات، القطيف 32632، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'السلام،، الدمام 32416، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود فرع الصفا',
  'rating': '4.0 نجمة ',
  'location': '7921 طريق الملك سعود بن عبدالعزيز، حي الصفا، الدمام 34222 3374، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'شارع ١٧ (د)، الشاطئ، القطيف 32617، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود شارع البيبسي',
  'rating': '4.6 نجمة ',
  'location': '4312 طريق الأمير فيصل بن فهد، الحزام الأخضر، الخبر 34436 6229، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'طريق الأمير نايف بن عبدالعزيز، البحيرة، الدمام 32431، المملكة العربية السعودية'},
 {'store_name': '629 العربية للعود | Arabian Oud',
  'rating': '4.0 نجمة ',
  'location': '8277 2363 الخوارزمي, أحد، الدمام 32264، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'الدانة، رأس تنورة 32817، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '4.2 نجمة ',
  'location': '39 ب، الندى، الدمام 32271، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'شارع الأمير محمد بن فهد بن عبدالعزيز، المروج، قرية العليا 37633، المملكة العربية السعودية'},
 {'store_name': '551 العربية للعود | Arabian Oud',
  'rating': '3.0 نجمة ',
  'location': 'حي, شارع الملك خالد، الجلوية، الدمام 32246، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'شارع عبدالرحمن بن عوف، بدر، الدمام 32274، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'العنود، الدمام 32427، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'طريق الملك فهد, حي الفيصلية، الدمام 32272، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'حي, شارع الملك خالد، الجلوية، الدمام 32246، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'طريق الملك فهد، أحد، الدمام 32263، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '4.7 نجمة ',
  'location': 'طريق الأمير فيصل بن فهد، العقربية، الخبر 34436، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود والعطور',
  'rating': '4.0 نجمة ',
  'location': 'شارع عمر بن الخطاب، الفيصلية، الدمام 32272، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.7 نجمة ',
  'location': '13th Street, الدواسر، الدمام 32416، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': '7579 طريق الأمير محمد بن فهد بن عبدالعزيز، الاسكان، الدمام 32236، المملكة العربية السعودية'},
 {'store_name': '555 العربية للعود | Arabian Oud',
  'rating': '4.4 نجمة ',
  'location': 'الشاطئ الشرقي، الدمام 32414، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'النزهة، الدمام 32252، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'العثيم مول، حي عبد الله فؤاد، عبدالله فؤاد، الدمام 32236، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'طريق الملك فهد، العدامة، الدمام 32242، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.5 نجمة ',
  'location': '4845 أبو أمية المخزومي، 8048، المزروعية، الدمام 32414، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.6 نجمة ',
  'location': 'حي الجامعة، الظهران 34257، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': '8073 طريق الملك سعود, الصفا، الدمام 34222، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '3.9 نجمة ',
  'location': 'طريق الملك خالد الفرعي، الحمراء، الخبر 34628، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'العقربية، الخبر 34445، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': '7103 الامير بندر بن عبد العزيز، حي الخبر الشمالية، الخبر 34428، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'الجسر، الخبر 34714، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'طريق الملك خالد، التحلية، الخبر 34716، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'الثقبة، الخبر 34623، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '4.0 نجمة ',
  'location': 'الربوة،، الربوة، الرياض 12839، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود فرع الثقبة',
  'rating': '4.1 نجمة ',
  'location': 'الثالث عشر، الثقبة، الخبر 34623، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '5.0 نجمة ',
  'location': '8015 طريق الدمام الفرعي، اليرموك، الرياض 13243، المملكة العربية السعودية'},
 {'store_name': '360 العربية للعود | Arabian Oud',
  'rating': '4.2 نجمة ',
  'location': 'مجمع الظهران، شارع فيصل بن فهد، حي، الدوحة الجنوبية، الظهران 34457، المملكة العربية السعودية'},
 {'store_name': 'Dkhoun | دخون',
  'rating': '4.7 نجمة ',
  'location': 'الجبيل البلد، الجبيل 35514، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'المدينة، بقيق 33261، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '4.1 نجمة ',
  'location': 'طريق الظهران، حي الخرس، المبرز 36342، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود مجمع الراشد',
  'rating': '3.0 نجمة ',
  'location': '75RJ+CHQ، طريق خادم الحرمين الشريفين، العليا، الخبر 32652، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'طريق الدمام الفرعي، المونسية، الرياض 13246، المملكة العربية السعودية'},
 {'store_name': '986 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': '9J8R+P9C، الفردوس، الهفوف 36368، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud | العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'VJ3X+6CF، النرجس، الرياض 13333، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'طريق الخليج، حي الروضة، الهفوف 36362، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود 185',
  'rating': '5.0 نجمة ',
  'location': '8320 شريح الحجازي، الروضة، الرياض 13213، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'طريق الملك سعود، السلام الثاني، المبرز 36422، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'طريق أنس ابن مالك، الصحافة، الرياض 13321، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود 18',
  'rating': '5.0 نجمة ',
  'location': 'الملك فهد، الرياض 12261، المملكة العربية السعودية'},
 {'store_name': '3607 العربية للعود | Arabian Oud',
  'rating': '4.5 نجمة ',
  'location': 'Shop 1193 Building، 3977 Road 4660، المنامة 973، البحرين'},
 {'store_name': 'العربية للعود',
  'rating': '5.0 نجمة ',
  'location': 'شارع الملك عبدالله بن عبدالعزيز, الريان، الخفجي 39261، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': '3802، الخفجي 39261، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'طريق فيصل بن عبدالعزيز، البلدية، حفر الباطن 39921، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'Mahasin, شارع خالد بن الوليد، اسواق القرية الشعبية، حي،، الهفوف 36421، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'طريق الملك عبدالله الفرعي، الحمراء، الرياض 13217، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'الإمام سعود بن عبد العزيز بن محمد، المغرزات، الرياض المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'النايفية، الهفوف 36445، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.4 نجمة ',
  'location': 'الندوة، حي الندوة، الرياض 14814، المملكة العربية السعودية'},
 {'store_name': '699 العربية للعود | Arabian Oud',
  'rating': '3.9 نجمة ',
  'location': 'شارع الملك خالد، التعاون، الخفجي 39255، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود التخصصي',
  'rating': '4.4 نجمة ',
  'location': '7324 شارع التخصصي، العليا، الرياض 12342، المملكة العربية السعودية'},
 {'store_name': '720 العربية للعود | Arabian Oud',
  'rating': '4.0 نجمة ',
  'location': '8346 الترمذي، الشفا، الرياض 14713، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.5 نجمة ',
  'location': 'المونسية، الرياض 13253، المملكة العربية السعودية'},
 {'store_name': '807 العربية للعود | Arabian Oud',
  'rating': '4.4 نجمة ',
  'location': 'شارع الأمير طلال بن عبدالعزيز،، الهفوف 36361، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.0 نجمة ',
  'location': 'الاندلس، الرياض 11564، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': '7575 الطريق الدائري الشرقي الفرعي، القدس، الرياض 13214، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.0 نجمة ',
  'location': '2937 طريق الملك عبدالله الفرعي، الورود، الرياض 12253، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.5 نجمة ',
  'location': '6774 طريق الأمير محمد بن سلمان بن عبدالعزيز، قرطبة، 3548، الرياض 13247، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.5 نجمة ',
  'location': 'حي, طريق الملك عبدالعزيز، الربيع، الرياض 13316، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'الملقا, طريق الامام سعود بن فيصل الفرعي المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'طريق الإمام سعود بن عبدالعزيز بن محمد، النخيل، الرياض 12381، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.6 نجمة ',
  'location': 'طريق ابي بكر الصديق، النرجس، الرياض 13336، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.7 نجمة ',
  'location': 'طريق الثمامة، المونسية، الرياض 13421، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.0 نجمة ',
  'location': 'مطار الملك خالد الدولي بالرياض، مطار الملك خالد الدولي، الرياض 13458، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'اليرموك، الرياض 13251، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.6 نجمة ',
  'location': 'طريق عثمان بن عفان، النزهة، الرياض 12474، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '4.0 نجمة ',
  'location': '8538 شارع أبي الأسود الدؤلي، النسيم الشرقي، الرياض 14243، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'الاسكان، الرياض 14317، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'طريق الملك فهد، العقيق، الرياض 13515، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'طريق خريص، الروضة، الرياض 13211، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.3 نجمة ',
  'location': 'طريق نجم الدين الأيوبي الفرعي، طويق، الرياض 14931، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'سلمان الفارسي، النهضة،،، النهضة، الرياض 13221، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'طريق العروبة، العليا، الرياض 12244، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': '6441 شارع حسان بن ثابت، النسيم الشرقي، الرياض 14241، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'شارع الأمير بندر بن عبد العزيز، حي النهضة، النهضة، الرياض 13222، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': '3427 طريق الخرج، المنصورة، الرياض 12692، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'قرطبة، الرياض 13244، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.5 نجمة ',
  'location': 'RURA7465, 2348 وادي الساحل، 7465, حي, الرمال, الرياض 13263، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': '4239 طريق الملك فهد، العليا، 7062، الرياض 12311، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.5 نجمة ',
  'location': 'الحارث بن عبدالله، حي الندوة، الرياض 14813، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'اسواق التميمى، شارع خالد بن الوليد، الاندلس، الرياض 13212، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'حي, شارع الأمير عبدالعزيز بن مساعد بن جلوي، السليمانية، الرياض 12221، المملكة العربية السعودية'},
 {'store_name': '838 العربية للعود | Arabian Oud',
  'rating': '3.9 نجمة ',
  'location': 'السلمانية الشمالية، الهفوف 36421، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود 680',
  'rating': '5.0 نجمة ',
  'location': 'قرطبة، الرياض 13245، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'الخالدية، الدرعية 13713، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'السويدي العام، سلطانة، الرياض 12777، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': '3708 طريق العزيزية الفرعي، العزيزية، 6776 طريق العزيزية،، الرياض 14511، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'Ayyubi Rd, صلاح الدين، Prince Faisal Bin Fahd Stadium, الرياض 12836، المملكة العربية السعودية'}]

In [657]:
alarabya_list_13=pickle.load(open('alarabya_pkl\\alarabya_yanbu.pkl','rb'))
alarabya_list_13 = [dictionary for dictionary in alarabya_list_13 if 'الإسكندرية' not in dictionary['location'] and 'القاهرة' not in dictionary['location']]
print(len(alarabya_list_13))

alarabya_list_13

118

[{'store_name': 'العربيه للعود',
  'rating': '4.0 نجمة ',
  'location': 'الحدائق، ينبع 46424، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.7 نجمة ',
  'location': '7477 طريق الملك عبدالله بن عبدالعزيز شمال, التاخي، ينبع 46429، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.5 نجمة ',
  'location': '1, Dana Mall, Gate، ينبع 46435، المملكة العربية السعودية'},
 {'store_name': '581 العربية للعود | Arabian Oud',
  'rating': '4.4 نجمة ',
  'location': 'علي بن أبي طالب، الشربتلي، ينبع 46424، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'المشهد، ينبع 46423، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '2.0 نجمة ',
  'location': 'حي, الامير مقرن بن عبد العزيز, المروج، ينبع 46511، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.5 نجمة ',
  'location': 'الشهداء، بدر 46357، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '4.1 نجمة ',
  'location': 'طريق الملك عبدالعزيز، السلام، املج 48321، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '4.2 نجمة ',
  'location': '2791 أبو أيوب الأنصاري، بني خدرة، المدينة المنورة 42311 6233،، بني خدرة، 42311،، المملكة العربية السعودية'},
 {'store_name': 'محمود للعود',
  'rating': '4.6 نجمة ',
  'location': 'التاخي، ينبع 46429، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود Arabian Oud',
  'rating': '4.4 نجمة ',
  'location': 'Juhaina Sq Mall of Arabia, Unit No. H96, محافظة الجيزة 12573'},
 {'store_name': 'العربيه للعود',
  'rating': '3.4 نجمة ',
  'location': 'طارق بن زياد، الرزيقية، العلا 43561، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'الامام البخاري، الدفاع، المدينة المنورة 42377، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '4.1 نجمة ',
  'location': 'طريق الامير عبداالمجيد بن العزيز المملكة العربية السعودية'},
 {'store_name': 'العربية للعود فرع التحلية',
  'rating': '3.4 نجمة ',
  'location': 'طريق الامير محمد بن عبدالعزيز، العريض، المدينة المنورة 42314، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.4 نجمة ',
  'location': 'شارع الحسن بن عبدالعزيز، العزيزية، المدينة المنورة 42377، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '4.1 نجمة ',
  'location': 'H5V3+VV4، شارع شرق النهضه، السلامة، جدة 28383، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': '7337 الامير سلطان فرعي، حي المحمدية، جدة 23625 2115، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'طريق سلطانة، الراية، المدينة المنورة 42312، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'حمد الجاسر، الروضة، جدة 23434، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'الامام البخاري، الدفاع، المدينة المنورة 42374، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود فرع المناخة',
  'rating': '3.8 نجمة ',
  'location': 'FJ74+WRC، الحرم، المدينة المنورة 42311، المملكة العربية السعودية'},
 {'store_name': '768 العربية للعود | Arabian Oud',
  'rating': '4.6 نجمة ',
  'location': '6927 طريق الملك فهد، بضاعة، المدينة المنورة 42311، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود Arabia Oud',
  'rating': '4.4 نجمة ',
  'location': 'JDSA8673، 8673 ام القرى، 4142، حي الصفا،، جدة 23456، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.6 نجمة ',
  'location': 'الراشد ميغا مول، شظاة، المدينة المنورة 42361، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': '2418 طريق سلطانة، بئر عثمان، المدينة المنورة 42331، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.1 نجمة ',
  'location': '3952، 6873 حي، مريخ، جدة 23361، المملكة العربية السعودية'},
 {'store_name': '942 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': 'ممر مشاة، بضاعة، المدينة المنورة 42311، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': '3460 طريق الامير محمد بن عبدالعزيز،، 7210 Prince Mohammed Bin Abdulaziz St، المدينة المنورة 42314، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': '، حي، الخالدية، طريق الأمير محمد بن عبد العزيز، المدينة المنورة 42317، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'طريق الأمير نايف بن عبدالعزيز، البركة، المدينة المنورة 42332، المملكة العربية السعودية'},
 {'store_name': '659 العربية للعود | Arabian Oud',
  'rating': '4.3 نجمة ',
  'location': 'ممر مشاة، بضاعة، المدينة المنورة 42311، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'القصواء، المدينة المنورة 42391، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.6 نجمة ',
  'location': 'طريق صلاح الدين الايوبي، شوران، المدينة المنورة 42386، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'طريق الأمير عبد المجيد، الجمعة، المدينة المنورة 42316، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'المبعوث، الأمير مقرن ،، المدينة المنورة 42362، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.7 نجمة ',
  'location': 'الحديقة، المدينة المنورة 42383، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'الامير عبدالمجيد بن عبدالعزيز، الشريبات، المدينة المنورة 42317، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'الصمد، رابغ 25728، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'FM2H+X5، مذينب، المدينة المنورة 42364، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'طريق قباء، الجمعة، المدينة المنورة 42315، المملكة العربية السعودية'},
 {'store_name': '158 العربية للعود | Arabian Oud',
  'rating': '4.3 نجمة ',
  'location': 'ممر مشاة، بضاعة، المدينة المنورة 42311، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'Taibah District, جدة 23831، المملكة العربية السعودية'},
 {'store_name': '1231 العربية للعود | Arabian Oud',
  'rating': '4.5 نجمة ',
  'location': 'الحمراء، جدة 23324، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.5 نجمة ',
  'location': 'العباس بن عبادة، القصواء، المدينة المنورة 42391، المملكة العربية السعودية'},
 {'store_name': '257 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': 'سعد بن معاذ، بضاعة، المدينة المنورة 42311، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.5 نجمة ',
  'location': 'طريق سليمان الراجحي، حي القيم الأعلى، الطائف 26551، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'الحمراء، جدة 23323، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '3.6 نجمة ',
  'location': '7248، 2415 سعود الفيصل، الصفا،، جدة 23451، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'طريق الأمير محمد بن عبدالعزيز، الروضة، جدة 23431، المملكة العربية السعودية'},
 {'store_name': '882 العربية للعود | Arabian Oud',
  'rating': '4.3 نجمة ',
  'location': '4618، As Sabuh، رابغ 25754، المملكة العربية السعودية'},
 {'store_name': '228 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': 'البهجه، مشرفة، جدة 23336، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'شارع عبدالله سليمان، الفيحاء، جدة 22246، المملكة العربية السعودية'},
 {'store_name': '509 العربية للعود | Arabian Oud',
  'rating': '4.0 نجمة ',
  'location': 'طريق قباء، الجمعة، المدينة المنورة 42315، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'الحمدانية، جدة 23761، المملكة العربية السعودية'},
 {'store_name': '530 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': 'الصمد، رابغ 25728، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.5 نجمة ',
  'location': 'طريق الملك عبدالله، 3363 طريق الملك عبدالله، حي ابرق الرغامة، جدة 22261، 9059، جدة 22261، المملكة العربية السعودية'},
 {'store_name': '734 العربية للعود | Arabian Oud',
  'rating': '4.3 نجمة ',
  'location': 'الحرم North، المدينة المنورة 42311، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'البهجه، مشرفة، جدة 23336، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'العيون، المدينة المنورة 42331، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'ابو حذيفه بن عتبه، مدائن الفهد، جدة 22337، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'طريق الملك فهد فرعي، الربوة، جدة 23533، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': '3811 حراء, AZ Zahra District, جدة 23522، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'شارع عابر القرات، أبحر الشمالية، جدة 23815، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'شارع عبدالله سليمان، الفيحاء، جدة 22246، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': '7599 الأمير ماجد، حي العزيزية، 2335، جدة 23342، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.7 نجمة ',
  'location': 'الصيرفي مول، حي الفيصلية، الفيصلية، جدة 23441، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': '3006 قريش، 6211، حي البوادي، جدة 23531، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '4.2 نجمة ',
  'location': 'طريق الامير سلطان، الزهراء، جدة 23425، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود arabian oud',
  'rating': '3.5 نجمة ',
  'location': 'Al Marwah District، 3972 حراء،، جدة 23543، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'المنار، جدة 23462، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': '8912 قاسم زينة، 4471 قاسم زينة، حي الروضة، جدة 23434، جدة 23434، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'طريق الليث الفرعي، القرينية، جدة 22535، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.5 نجمة ',
  'location': 'Ibrahim Al Khalil, St Abraj Al Bait 1، مكة 24231، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'الروضة، خيبر 43488، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'اسماعيل بن كثير، البساتين، جدة 23719، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.7 نجمة ',
  'location': 'شارع الحسين السهواجي، الربيع، جدة 23461، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.6 نجمة ',
  'location': 'النزهة، جدة 23532، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود Arabian Oud',
  'rating': '4.9 نجمة ',
  'location': 'شارع الدكتور عبدالقادر كوشك، ولي العهد، مكة 24353، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.2 نجمة ',
  'location': 'شارع الأمير محمد بن عبدالعزيز، الرحاب، Jarir Mall،، جدة 23345، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'شارع أبي ذر الغفاري، حي النسيم 7280, جدة 23234، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': '6326 طريق الامير متعب بن عبدالعزيز، 3578، حي مشرفة، جدة 23341، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود الحمدانيه',
  'rating': '4.6 نجمة ',
  'location': 'حي, JGAA4079, 8462 عمرو بن ابي وقاص(رضي الله عن، الحمدانية، 4079, جدة 23761، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.4 نجمة ',
  'location': 'طريق الأمير سلطان، النهضة، جدة 23523، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'الجامعة، مكة 24243، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': '6155 ابراهيم الخليل، الشوقية، مكة 24351، المملكة العربية السعودية'},
 {'store_name': '698 العربية للعود | Arabian Oud',
  'rating': '4.3 نجمة ',
  'location': 'الحمدانية، جدة 23761، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'قاده الفكر، الرويس، جدة 23215، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'المحاميد 22393، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'Fruit Boat Sculpture, شارع حراء، النهضة، جدة 23523، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'فازع، خليص 25542، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'ام القرى، الصفا، جدة 23453، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'الخضراء، مكة 24267، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'الاجاويد، جدة 22442، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'قصر الضيافة، الزهراء، مكة 24221، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': '3789، جدة 22434، المملكة العربية السعودية'},
 {'store_name': '783 العربية للعود | Arabian Oud',
  'rating': '3.0 نجمة ',
  'location': '6230 أبو أيوب الأنصاري، بني خدرة، 2665, المدينة المنورة 42311، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'المنار، حي المنار، 3938, جدة 23463، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'العزيزية، الوجه 48721، المملكة العربية السعودية'},
 {'store_name': '646 العربية للعود | Arabian Oud',
  'rating': '3.8 نجمة ',
  'location': '6793، Al Marwah District، جدة 23545، المملكة العربية السعودية'},
 {'store_name': '662 العربية للعود | Arabian Oud',
  'rating': '2.9 نجمة ',
  'location': '3749 صقر قريش، As Salamah District، جدة 23436، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '4.0 نجمة ',
  'location': 'السداد، الطائف 26514، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'شارع إبراهيم الجفالي، مكة 24372، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'CV77+4X، المرسلات، مكة 24243، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود |Arabian Oud',
  'rating': '4.4 نجمة ',
  'location': '3585، مروج الأمير، تبوك 47315، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود حراء الفحص',
  'rating': '3.6 نجمة ',
  'location': 'المروة، جدة 23541، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'حي, شارع العزيزية العام، الجامعة، مكة 24243، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': '8712 شارع القادسية، 3863, مكة 24268، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'النوارية، مكة 24215، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.4 نجمة ',
  'location': 'مهد الذهب 44411، المملكة العربية السعودية'},
 {'store_name': '503 العربية للعود | Arabian Oud',
  'rating': '4.7 نجمة ',
  'location': '8030، Al Henakiyah 42639،، الحناكية 42639، المملكة العربية السعودية'},
 {'store_name': '683 العربية للعود | Arabian Oud',
  'rating': '4.7 نجمة ',
  'location': 'طريق الملك عبدالله، الفيحاء، جدة 22251، المملكة العربية السعودية'},
 {'store_name': '624 العربية للعود | Arabian Oud',
  'rating': '3.4 نجمة ',
  'location': 'الحمدانية، جدة 23761، المملكة العربية السعودية'},
 {'store_name': '224 العربية للعود | Arabian Oud',
  'rating': '3.9 نجمة ',
  'location': '7871 طريق الامير سلطان، 2647, An Naim District, جدة 23621، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'العزيزية، العلا 43511، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '5.0 نجمة ',
  'location': 'مدرسه الثغر، District، 5580 Ahmad Al Badawi، جدة 22338، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'طريق الملك فيصل، العدل، مكة 24244، المملكة العربية السعودية'},
 {'store_name': '674 العربية للعود | Arabian Oud',
  'rating': '4.1 نجمة ',
  'location': 'District, Madain Al Fahd, جدة 22347، المملكة العربية السعودية'}]

In [658]:
alarabya_list_14=pickle.load(open('alarabya_pkl\\alarabya_jeddah.pkl','rb'))
alarabya_list_14 = [dictionary for dictionary in alarabya_list_14 if 'الإسكندرية' not in dictionary['location'] and 'القاهرة' not in dictionary['location']]
print(len(alarabya_list_14))

alarabya_list_14

114

[{'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'الحمراء، جدة 23323، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'طريق الأمير محمد بن عبدالعزيز، الروضة، جدة 23431، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'شارع عبدالله سليمان، الفيحاء، جدة 22246، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '3.6 نجمة ',
  'location': '7248، 2415 سعود الفيصل، الصفا،، جدة 23451، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'Taibah District, جدة 23831، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'طريق الملك فهد فرعي، الربوة، جدة 23533، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '4.2 نجمة ',
  'location': 'طريق الامير سلطان، الزهراء، جدة 23425، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': '7599 الأمير ماجد، حي العزيزية، 2335، جدة 23342، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'ابو حذيفه بن عتبه، مدائن الفهد، جدة 22337، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'شارع عبدالله سليمان، الفيحاء، جدة 22246، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': '8912 قاسم زينة، 4471 قاسم زينة، حي الروضة، جدة 23434، جدة 23434، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': '6155 ابراهيم الخليل، الشوقية، مكة 24351، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': '3811 حراء, AZ Zahra District, جدة 23522، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'الخضراء، مكة 24267، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '4.1 نجمة ',
  'location': 'H5V3+VV4، شارع شرق النهضه، السلامة، جدة 28383، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'شارع إبراهيم الجفالي، مكة 24372، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.5 نجمة ',
  'location': 'Ibrahim Al Khalil, St Abraj Al Bait 1، مكة 24231، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'الجامعة، مكة 24243، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'المنار، جدة 23462، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.3 نجمة ',
  'location': '2645 8840 طريق الملك عبدالله، السليمانية، جدة 22253، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'سوق الشاطئ _ شارع أحمد العطاس _ حي الزهراء، الزهراء، جدة 23425، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'اسماعيل بن كثير، البساتين، جدة 23719، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': '3006 قريش، 6211، حي البوادي، جدة 23531، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'الاجاويد، جدة 22442، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'شارع أبي ذر الغفاري، حي النسيم 7280, جدة 23234، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': '6326 طريق الامير متعب بن عبدالعزيز، 3578، حي مشرفة، جدة 23341، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'شارع الشيخ محمد بن جبير، الشوقية، مكة 24351، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.7 نجمة ',
  'location': 'شارع الحسين السهواجي، الربيع، جدة 23461، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': '2167 محمد صالح باشراحيل، الراشدية، مكة 24268، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود arabian oud',
  'rating': '3.5 نجمة ',
  'location': 'Al Marwah District، 3972 حراء،، جدة 23543، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'الحمدانية، جدة 23761، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': '6306 Al Shouhadaa, الشهداء، 3576، مكة 24223، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'حمد الجاسر، الروضة، جدة 23434، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': '3789، جدة 22434، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'CRW5+5M، طريق المدينة المنورة، الحجون، مكة 24237، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'شارع عابر القرات، أبحر الشمالية، جدة 23815، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'طريق الليث الفرعي، القرينية، جدة 22535، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'CV77+4X، المرسلات، مكة 24243، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': '7337 الامير سلطان فرعي، حي المحمدية، جدة 23625 2115، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود Arabian Oud',
  'rating': '4.9 نجمة ',
  'location': 'شارع الدكتور عبدالقادر كوشك، ولي العهد، مكة 24353، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.7 نجمة ',
  'location': 'الصيرفي مول، حي الفيصلية، الفيصلية، جدة 23441، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'الحمراء، الحمراء وأم الجود،، مكة 24321، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'قاده الفكر، الرويس، جدة 23215، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'Fruit Boat Sculpture, شارع حراء، النهضة، جدة 23523، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'ام القرى، الصفا، جدة 23453، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'قصر الضيافة، الزهراء، مكة 24221، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'البهجه، مشرفة، جدة 23336، المملكة العربية السعودية'},
 {'store_name': '698 العربية للعود | Arabian Oud',
  'rating': '4.3 نجمة ',
  'location': 'الحمدانية، جدة 23761، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '3.7 نجمة ',
  'location': 'حي, طريق المدينة المنورة، النعيم، جدة 23526، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '4.6 نجمة ',
  'location': 'عبدالعزيز بن ابراهيم، الصفا، جدة 23454، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود Arabian Oud',
  'rating': '3.8 نجمة ',
  'location': '6248 طريق الليث، ولي العهد، مكة 24356، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'النوارية، مكة 24215، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود حراء الفحص',
  'rating': '3.6 نجمة ',
  'location': 'المروة، جدة 23541، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'Jabal Omar, الشبيكة، مكة 24231، المملكة العربية السعودية'},
 {'store_name': '949 العربية للعود | Arabian Oud',
  'rating': '4.2 نجمة ',
  'location': 'الفيصلية، الجموم 25335، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.7 نجمة ',
  'location': 'طريق الامير متعب بن عبدالعزيز، الصفا، جدة 23451، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'المنار، حي المنار، 3938, جدة 23463، المملكة العربية السعودية'},
 {'store_name': '224 العربية للعود | Arabian Oud',
  'rating': '3.9 نجمة ',
  'location': '7871 طريق الامير سلطان، 2647, An Naim District, جدة 23621، المملكة العربية السعودية'},
 {'store_name': '674 العربية للعود | Arabian Oud',
  'rating': '4.1 نجمة ',
  'location': 'District, Madain Al Fahd, جدة 22347، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.6 نجمة ',
  'location': 'النزهة، جدة 23532، المملكة العربية السعودية'},
 {'store_name': '646 العربية للعود | Arabian Oud',
  'rating': '3.8 نجمة ',
  'location': '6793، Al Marwah District، جدة 23545، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود Arabia Oud',
  'rating': '4.4 نجمة ',
  'location': 'JDSA8673، 8673 ام القرى، 4142، حي الصفا،، جدة 23456، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.7 نجمة ',
  'location': 'شارع فاطمة الزهراء، النسيم، مكة 24245، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.2 نجمة ',
  'location': 'شارع الأمير محمد بن عبدالعزيز، الرحاب، Jarir Mall،، جدة 23345، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.7 نجمة ',
  'location': 'Batha Quraish, 9400, مكة 24361، المملكة العربية السعودية'},
 {'store_name': '843 العربية للعود | Arabian Oud',
  'rating': '3.9 نجمة ',
  'location': '3141 الطريق الدائري الثالث، الخالدية، مكة 24232، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'الراشدية، مكة 24269، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'مطار الملك عبدالعزيز الدولي، جدة 23635، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '4.2 نجمة ',
  'location': 'المحمل سنتر, طريق الملك عبدالعزيز الفرعي، البلد، جدة 22233، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': '7906، الجامعة،، مكة 24242، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'فازع، خليص 25542، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'طريق الملك فيصل، العدل، مكة 24244، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'طريق مكة القديم, القديمة، بحره 22826، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'الزاهر، مكة 24222، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود - Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': 'F6RC+FC8، الفيحاء، جدة 22246، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': '5026 الشيخ عبدالله القرعاوي، الملك فهد, 6510، مكة 24341، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود | Arabian Oud',
  'rating': '4.4 نجمة ',
  'location': 'طريق الليث، ولي العهد، مكة 24567، المملكة العربية السعودية'},
 {'store_name': '683 العربية للعود | Arabian Oud',
  'rating': '4.7 نجمة ',
  'location': 'طريق الملك عبدالله، الفيحاء، جدة 22251، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'البترجي فرعي، الزهراء، جدة 23521، المملكة العربية السعودية'},
 {'store_name': '662 العربية للعود | Arabian Oud',
  'rating': '2.9 نجمة ',
  'location': '3749 صقر قريش، As Salamah District، جدة 23436، المملكة العربية السعودية'},
 {'store_name': '982 العربية للعود | Arabian Oud',
  'rating': '4.6 نجمة ',
  'location': '7425 قصر الضيافة، الزهراء، مكة 24221، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': '3297، مكة 24416، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.4 نجمة ',
  'location': 'طريق الأمير سلطان، النهضة، جدة 23523، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': 'طريق الملك عبدالله، النخيل، جدة 22261، المملكة العربية السعودية'},
 {'store_name': '212 العربية للعود | Arabian Oud',
  'rating': '3.6 نجمة ',
  'location': 'البوادي، جدة 23443، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '4.6 نجمة ',
  'location': 'الهجلة، مكة 24231، المملكة العربية السعودية'},
 {'store_name': '291 العربية للعود | Arabian Oud',
  'rating': '3.6 نجمة ',
  'location': 'شارع الأجواد، المنار، جدة 23462، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '5.0 نجمة ',
  'location': 'مدرسه الثغر، District، 5580 Ahmad Al Badawi، جدة 22338، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود الحمدانيه',
  'rating': '4.6 نجمة ',
  'location': 'حي, JGAA4079, 8462 عمرو بن ابي وقاص(رضي الله عن، الحمدانية، 4079, جدة 23761، المملكة العربية السعودية'},
 {'store_name': '1217 العربية للعود | Arabian Oud',
  'rating': '4.5 نجمة ',
  'location': '7358، 5431 عبد الرحمن الناصر، الأصالة، جدة 23738، المملكة العربية السعودية'},
 {'store_name': '624 العربية للعود | Arabian Oud',
  'rating': '3.4 نجمة ',
  'location': 'الحمدانية، جدة 23761، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.5 نجمة ',
  'location': 'طريق الملك عبدالله، 3363 طريق الملك عبدالله، حي ابرق الرغامة، جدة 22261، 9059، جدة 22261، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud العربية للعود',
  'rating': '4.5 نجمة ',
  'location': 'FQGR+GRF، مكة 24227، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'الامير فواز الجنوبي، جدة 22431، المملكة العربية السعودية'},
 {'store_name': '228 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': 'البهجه، مشرفة، جدة 23336، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '4.6 نجمة ',
  'location': 'حي, الشاطئ، مول البحر الاحمر المملكة العربية السعودية'},
 {'store_name': 'الإدارة الإقليمية لشركة العربية للعود بمكة',
  'rating': '4.4 نجمة ',
  'location': 'طريق مكة جدة القديم، النزهة، مكة 24225، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'مطار الملك عبدالعزيز الدولي، جدة 23635، المملكة العربية السعودية'},
 {'store_name': '358 العربية للعود | Arabian Oud',
  'rating': '3.1 نجمة ',
  'location': '8276 الأمير ماجد، الفيصلية، جدة 23447، المملكة العربية السعودية'},
 {'store_name': '1231 العربية للعود | Arabian Oud',
  'rating': '4.5 نجمة ',
  'location': 'الحمراء، جدة 23324، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'حي, شارع العزيزية العام، الجامعة، مكة 24243، المملكة العربية السعودية'},
 {'store_name': '726 العربية للعود | Arabian Oud',
  'rating': '4.0 نجمة ',
  'location': '3413 شارع الحجون، الحجون، مكة 24231، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.1 نجمة ',
  'location': '3952، 6873 حي، مريخ، جدة 23361، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'طريق القاضي، بطحاء قريش، مكة 24352، المملكة العربية السعودية'},
 {'store_name': '235 العربية للعود | Arabian Oud',
  'rating': '4.0 نجمة ',
  'location': '6945 حمزة بن عبدالمطلب، 4006, الهجلة، مكة 24231، المملكة العربية السعودية'},
 {'store_name': '220 العربية للعود | Arabian Oud',
  'rating': '4.8 نجمة ',
  'location': 'سوق الحجاز، طريق مكة جدة السريع، النزهة، مكة 24225، المملكة العربية السعودية'},
 {'store_name': '992 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': 'حي الخضراء, MEKA4495، 4495 شارع الحدرجان بن مالك الأزدي، 8592, مكة 24263، المملكة العربية السعودية'},
 {'store_name': '258 العربية للعود | Arabian Oud',
  'rating': '3.7 نجمة ',
  'location': '3923 ابراهيم الخليل، الهجلة، 7089 ابراهيم الخليل،، مكة 24231، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '2.7 نجمة ',
  'location': 'المنصور، مكة 24231، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'المحاميد 22393، المملكة العربية السعودية'},
 {'store_name': 'Arabian oud العربية للعود 1273',
  'rating': '5.0 نجمة ',
  'location': '9QHV+JV3، الشوقية، مكة 24351، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud العربية للعود',
  'rating': '4.8 نجمة ',
  'location': '9W53+XVV Dan Plaza, مكة 58644، المملكة العربية السعودية'},
 {'store_name': '288 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': 'الجامعة، 5510, حي الثغر, JIJB7134، 7134, جدة 22338، المملكة العربية السعودية'},
 {'store_name': '1218 العربية للعود | Arabian Oud',
  'rating': '4.0 نجمة ',
  'location': 'الحمدانية، جدة 23761، المملكة العربية السعودية'}]

In [659]:
alarabya_list_15=pickle.load(open('alarabya_pkl\\alarabya_khobar.pkl','rb'))
alarabya_list_15 = [dictionary for dictionary in alarabya_list_15 if 'الإسكندرية' not in dictionary['location'] and 'القاهرة' not in dictionary['location']]
print(len(alarabya_list_15))

alarabya_list_15

27

[{'store_name': 'العربيه للعود',
  'rating': '3.9 نجمة ',
  'location': 'طريق الملك خالد الفرعي، الحمراء، الخبر 34628، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'شارع عبدالرحمن بن عوف، بدر، الدمام 32274، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'العقربية، الخبر 34445، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': '7103 الامير بندر بن عبد العزيز، حي الخبر الشمالية، الخبر 34428، المملكة العربية السعودية'},
 {'store_name': '629 العربية للعود | Arabian Oud',
  'rating': '4.0 نجمة ',
  'location': '8277 2363 الخوارزمي, أحد، الدمام 32264، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود والعطور',
  'rating': '4.0 نجمة ',
  'location': 'شارع عمر بن الخطاب، الفيصلية، الدمام 32272، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': '7579 طريق الأمير محمد بن فهد بن عبدالعزيز، الاسكان، الدمام 32236، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'حي, شارع الملك خالد، الجلوية، الدمام 32246، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'الجسر، الخبر 34714، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.6 نجمة ',
  'location': 'حي الجامعة، الظهران 34257، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'طريق الملك فهد، أحد، الدمام 32263، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'طريق الملك خالد، التحلية، الخبر 34716، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': '8073 طريق الملك سعود, الصفا، الدمام 34222، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود فرع الثقبة',
  'rating': '4.1 نجمة ',
  'location': 'الثالث عشر، الثقبة، الخبر 34623، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'العثيم مول، حي عبد الله فؤاد، عبدالله فؤاد، الدمام 32236، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'الثقبة، الخبر 34623، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'النزهة، الدمام 32252، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'طريق الملك فهد, حي الفيصلية، الدمام 32272، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '4.2 نجمة ',
  'location': '39 ب، الندى، الدمام 32271، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'طريق الملك فهد، العدامة، الدمام 32242، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود فرع الصفا',
  'rating': '4.0 نجمة ',
  'location': '7921 طريق الملك سعود بن عبدالعزيز، حي الصفا، الدمام 34222 3374، المملكة العربية السعودية'},
 {'store_name': '360 العربية للعود | Arabian Oud',
  'rating': '4.2 نجمة ',
  'location': 'مجمع الظهران، شارع فيصل بن فهد، حي، الدوحة الجنوبية، الظهران 34457، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود شارع البيبسي',
  'rating': '4.6 نجمة ',
  'location': '4312 طريق الأمير فيصل بن فهد، الحزام الأخضر، الخبر 34436 6229، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '4.7 نجمة ',
  'location': 'طريق الأمير فيصل بن فهد، العقربية، الخبر 34436، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.5 نجمة ',
  'location': 'شارع عمر بن الخطاب، الفيصلية، الدمام 32272، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'العنود، الدمام 32427، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.7 نجمة ',
  'location': '13th Street, الدواسر، الدمام 32416، المملكة العربية السعودية'}]

In [660]:
alarabya_list_16=pickle.load(open('alarabya_pkl\\alarabya_najran.pkl','rb'))
alarabya_list_16 = [dictionary for dictionary in alarabya_list_16 if 'الإسكندرية' not in dictionary['location'] and 'القاهرة' not in dictionary['location']]
print(len(alarabya_list_16))

alarabya_list_16

81

[{'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': '9674، 3491 طريق الملك عبد العزيز، نجران 66263 المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': '8457 طريق الملك عبدالعزيز، الخالدية، نجران 66262، المملكة العربية السعودية'},
 {'store_name': '923 العربية للعود | Arabian Oud',
  'rating': '3.9 نجمة ',
  'location': 'نجران 66252، المملكة العربية السعودية'},
 {'store_name': '717 العربية للعود | Arabian Oud',
  'rating': '2.3 نجمة ',
  'location': 'Al Husayn Market, Al Husayn rd 66273، المملكة العربية السعودية'},
 {'store_name': '1213 العربية للعود | Arabian Oud',
  'rating': '4.4 نجمة ',
  'location': 'NJUB7872، 7872 حمد ابن ماضي, 3844, حي أبا السعود, نجران 66281، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '3.0 نجمة ',
  'location': 'طريق الملك عبدالعزيز، الخالدية، نجران 66261، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud العربية للعود',
  'rating': '5.0 نجمة ',
  'location': '6193 فهد بن عبدالعزيز, حي الاثايبة, NJMB2554، 2554, نجران 66258، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud |العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'الخالدية، 4177، الخالدية، نجران 66261 9299, نجران 66261، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.7 نجمة ',
  'location': 'طريق الملك عبدالعزيز، مخطط العريسة الشمالي 66243، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '4.3 نجمة ',
  'location': 'طريق الملك عبدالعزيز، مخطط العريسة الشمالي 66243، المملكة العربية السعودية'},
 {'store_name': 'OudElite - نخبة العود 7289',
  'rating': '4.3 نجمة ',
  'location': 'G6P7+39، طريق الملك عبدالعزيز، حي الفيصلية، نجران 66262، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.5 نجمة ',
  'location': 'الطريق العام, حبونا 66342، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'Dhahran Al Janub، Dhahran 64271، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': '2555, مخطط الموسى, خميس مشيط 62463، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'طريق الداير وادي الجنية، الدائر 83862، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.7 نجمة ',
  'location': 'طريق الملك فهد، تاج مول، أبو عريش 84416، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '5.0 نجمة ',
  'location': '9061 الشارع العام، AGPB2375، 2375، آل عامر 62263، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'الملك فهد،، الملك فهد، أبو عريش 84522، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'طريق الكورنيش، الشاطيء، جازان 82811، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '3.7 نجمة ',
  'location': 'شارع الملك فيصل، وسط المدينة، أبها 62521، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'طريق الكورنيش، كادي مول، جازان 82725، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.6 نجمة ',
  'location': 'طريق الملك عبدالعزيز، 6349، GBMA3194، 3194، ضمد 84971، المملكة العربية السعودية'},
 {'store_name': '1248 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': 'طريق الملك عبدالعزيز، 6316, GBMA3134، 3134, ضمد 84971، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '4.3 نجمة ',
  'location': 'بن عبدالعزيز, المنزم، طريق الملك عبدالله المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.4 نجمة ',
  'location': 'طريق الملك خالد بن عبدالعزيز،، الروضة، سراة عبيدة 64532، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود والعطور',
  'rating': '3.6 نجمة ',
  'location': 'Q97H+M2، الصفة 28939، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '4.6 نجمة ',
  'location': 'طريق الأمير سلطان، الروابي، العارضة 83224، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '5.0 نجمة ',
  'location': 'Unnamed Road 62497، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '5.0 نجمة ',
  'location': '8452 جنوبا الى احد رفيده و شمالا الى خميس مشيط، سكن المدينة العسكرية، 3615، خميس مشيط 62413، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '4.1 نجمة ',
  'location': '8379 طريق الأمير سلطان، الموسى، خميس مشيط 62463، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.8 نجمة ',
  'location': 'جرير، النخيل، السليل 18621، المملكة العربية السعودية'},
 {'store_name': '745 العربية للعود | Arabian Oud',
  'rating': '4.1 نجمة ',
  'location': 'H6G5+G3، طريب 62828، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '5.0 نجمة ',
  'location': '6714، الباحة 65522 3341، 65522، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '3.9 نجمة ',
  'location': 'أم سرور، خميس مشيط 62461، المملكة العربية السعودية'},
 {'store_name': '498 العربية للعود | Arabian Oud',
  'rating': '4.0 نجمة ',
  'location': '8P4J+CX3، العرق الجنوبي، خميس مشيط 62461، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.5 نجمة ',
  'location': 'شارع الملك خالد، الشفاء، خميس مشيط 62433، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.6 نجمة ',
  'location': 'مجمع الغنيم، طريق الملك فيصل، الخالدية، Muhayil,Abha 63687، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.6 نجمة ',
  'location': 'HMPW+J9، عريجة، وادي ابن هشبل 62931، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '5.0 نجمة ',
  'location': '6142 طريق الملك عبدالله، حي الزهور، AEPA3680، 3680، بارق 63916، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.6 نجمة ',
  'location': 'VHQC+P6W، جازان 82722، المملكة العربية السعودية'},
 {'store_name': '871 العربية للعود | Arabian Oud',
  'rating': '4.7 نجمة ',
  'location': 'P7PC+WC، الدرب 89888، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.4 نجمة ',
  'location': 'الواحة سنتر، طريق الملك فهد، خميس مشيط 62434، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'طريق الامير سلطان، ذي ريجن مول، أبو عريش 84522، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.7 نجمة ',
  'location': 'الواحة، خميس مشيط 62456، المملكة العربية السعودية'},
 {'store_name': '716 العربية للعود | Arabian Oud',
  'rating': '3.0 نجمة ',
  'location': 'العرق الجنوبي، خميس مشيط 62461، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'JW3P+GRW، صامطة 86735، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': '5457 طريق الملك فهد، خميس مشيط 62461، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'شارع الملك عبدالعزيز, حي الشامية، جازان 82714، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.6 نجمة ',
  'location': 'طريق احمد بن عبدالعزيز، القوز 28829، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.0 نجمة ',
  'location': '6221 2054 طريق الملك عبدالعزيز، المجد، صبيا 85534، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': '8764 طريق الملك فهد، الشاطيء، جازان 82727، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': '5، الشريعة 87587، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'حي, طريق الملك عبدالعزيز، الشرفية، أبها 62542، المملكة العربية السعودية'},
 {'store_name': '776 العربية للعود | Arabian Oud',
  'rating': '4.3 نجمة ',
  'location': '2687 طريق المطار، جازان 82722، المملكة العربية السعودية'},
 {'store_name': '131 العربية للعود | Arabian Oud',
  'rating': '3.8 نجمة ',
  'location': '8770، السلام، خميس مشيط 62461، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.4 نجمة ',
  'location': '3033 طريق الملك عبدالعزيز، الرحاب، 7228 طريق الملك عبدالعزيز،، صبيا 85457، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'صامطة 86736، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'Avenue، طريق الملك خالد،، ذلالة، خميس مشيط 62411، المملكة العربية السعودية'},
 {'store_name': '1224 العربية للعود | Arabian Oud',
  'rating': '4.0 نجمة ',
  'location': 'الراشد مول, طريق الملك فهد، البديع، أبها 12839، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'المنسك، حي، أبها 62581، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'P7RH+9V، الدرب 89699، المملكة العربية السعودية'},
 {'store_name': '756 العربية للعود | Arabian Oud',
  'rating': '3.9 نجمة ',
  'location': 'العزيزية، صبيا 85297، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '4.4 نجمة ',
  'location': 'السوق، شرورة 68372، المملكة العربية السعودية'},
 {'store_name': '578 العربية للعود | Arabian Oud',
  'rating': '3.7 نجمة ',
  'location': 'الرونة، أحد رفيدة 62447، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.7 نجمة ',
  'location': 'طريق الملك فيصل، الفيصلية، محايل عسير 63687، المملكة العربية السعودية'},
 {'store_name': '701 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': 'التاج مول, طريق الملك فهد، بن عبدالعزيز, أبو عريش 82511، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'الفيصلية، محايل عسير 63715، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '5.0 نجمة ',
  'location': 'الطريق العام, نمرة 65439، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': '44FJ+H2، طريق الملك فيصل، السلام، النماص 67393، المملكة العربية السعودية'},
 {'store_name': '857 العربية للعود | Arabian Oud',
  'rating': '4.0 نجمة ',
  'location': '76MR+H2، الجرف 63454، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.0 نجمة ',
  'location': '4608 طريق الملك عبدالعزيز، السد، أبها 62521، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '5.0 نجمة ',
  'location': 'الشروق، طريق الملك فهد - مول, الباحة المملكة العربية السعودية'},
 {'store_name': '1228 العربية للعود | Arabian Oud',
  'rating': '3.7 نجمة ',
  'location': '8772 البلد 13, حي السلام, AKPA3785، 3785, خميس مشيط 62461، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'الملك عبدالله، بيشة 67712، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.0 نجمة ',
  'location': 'طريق الملك فهد بن عبدالعزيز، القنفذة 28822، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'طريق الملك عبدالعزيز، الصفا، جازان 82721، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'بارق 63916، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': '7HF3QC8M+FV، المخواة 65614، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': '15، تنومة 62795، المملكة العربية السعودية'},
 {'store_name': '364 العربية للعود | Arabian Oud',
  'rating': '3.5 نجمة ',
  'location': 'العزيزية، سبت العلاية 67542، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': '3980، بحر ابو سكينة 63585، المملكة العربية السعودية'}]

In [661]:
alarabya_list_17=pickle.load(open('alarabya_pkl\\alarabya_jazan.pkl','rb'))
alarabya_list_17 = [dictionary for dictionary in alarabya_list_17 if 'الإسكندرية' not in dictionary['location'] and 'القاهرة' not in dictionary['location']]
print(len(alarabya_list_17))

alarabya_list_17

113

[{'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'شارع الملك عبدالعزيز, حي الشامية، جازان 82714، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.6 نجمة ',
  'location': 'VHQC+P6W، جازان 82722، المملكة العربية السعودية'},
 {'store_name': '776 العربية للعود | Arabian Oud',
  'rating': '4.3 نجمة ',
  'location': '2687 طريق المطار، جازان 82722، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': 'مول الرشيد, طريق الملك فهد، الشاطيء، جازان 82723، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': '8764 طريق الملك فهد، الشاطيء، جازان 82727، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'طريق الملك عبدالعزيز، الصفا، جازان 82721، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'طريق الكورنيش، الشاطيء، جازان 82811، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '3.5 نجمة ',
  'location': 'مول الغروي, طريق الملك فهد، حي الروضة, جازان 82723، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'طريق الكورنيش، كادي مول، جازان 82725، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'طريق الامير سلطان، ذي ريجن مول، أبو عريش 84522، المملكة العربية السعودية'},
 {'store_name': '1248 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': 'طريق الملك عبدالعزيز، 6316, GBMA3134، 3134, ضمد 84971، المملكة العربية السعودية'},
 {'store_name': 'Dkhoun | دخون',
  'rating': '4.4 نجمة ',
  'location': 'Al Rashid Mall, Prince Mohammad Bin Nasser Rd, Jazan 82723, جازان المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.4 نجمة ',
  'location': '3033 طريق الملك عبدالعزيز، الرحاب، 7228 طريق الملك عبدالعزيز،، صبيا 85457، المملكة العربية السعودية'},
 {'store_name': '756 العربية للعود | Arabian Oud',
  'rating': '3.9 نجمة ',
  'location': 'العزيزية، صبيا 85297، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'الملك فهد،، الملك فهد، أبو عريش 84522، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.0 نجمة ',
  'location': '6221 2054 طريق الملك عبدالعزيز، المجد، صبيا 85534، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.7 نجمة ',
  'location': 'طريق الملك فهد، تاج مول، أبو عريش 84416، المملكة العربية السعودية'},
 {'store_name': '701 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': 'التاج مول, طريق الملك فهد، بن عبدالعزيز, أبو عريش 82511، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.6 نجمة ',
  'location': 'طريق الملك عبدالعزيز، 6349، GBMA3194، 3194، ضمد 84971، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'JW3P+GRW، صامطة 86735، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': '5، الشريعة 87587، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '4.3 نجمة ',
  'location': 'بن عبدالعزيز, المنزم، طريق الملك عبدالله المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'طريق الداير وادي الجنية، الدائر 83862، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'صامطة 86736، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.5 نجمة ',
  'location': 'شارع الملك خالد، الشفاء، خميس مشيط 62433، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.7 نجمة ',
  'location': 'الواحة، خميس مشيط 62456، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '4.6 نجمة ',
  'location': 'طريق الأمير سلطان، الروابي، العارضة 83224، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.4 نجمة ',
  'location': 'الواحة سنتر، طريق الملك فهد، خميس مشيط 62434، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '3.9 نجمة ',
  'location': 'أم سرور، خميس مشيط 62461، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '4.1 نجمة ',
  'location': '8379 طريق الأمير سلطان، الموسى، خميس مشيط 62463، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'P7RH+9V، الدرب 89699، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'Dhahran Al Janub، Dhahran 64271، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'Avenue، طريق الملك خالد،، ذلالة، خميس مشيط 62411، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': '5457 طريق الملك فهد، خميس مشيط 62461، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'حي, طريق الملك عبدالعزيز، الشرفية، أبها 62542، المملكة العربية السعودية'},
 {'store_name': '871 العربية للعود | Arabian Oud',
  'rating': '4.7 نجمة ',
  'location': 'P7PC+WC، الدرب 89888، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'المنسك، حي، أبها 62581، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '5.0 نجمة ',
  'location': 'Unnamed Road 62497، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': '9674، 3491 طريق الملك عبد العزيز، نجران 66263 المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'الفيصلية، محايل عسير 63715، المملكة العربية السعودية'},
 {'store_name': '131 العربية للعود | Arabian Oud',
  'rating': '3.8 نجمة ',
  'location': '8770، السلام، خميس مشيط 62461، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': '3980، بحر ابو سكينة 63585، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.6 نجمة ',
  'location': 'HMPW+J9، عريجة، وادي ابن هشبل 62931، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': '8457 طريق الملك عبدالعزيز، الخالدية، نجران 66262، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': '44FJ+H2، طريق الملك فيصل، السلام، النماص 67393، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.7 نجمة ',
  'location': 'طريق الملك عبدالعزيز، مخطط العريسة الشمالي 66243، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '3.7 نجمة ',
  'location': 'شارع الملك فيصل، وسط المدينة، أبها 62521، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '3.6 نجمة ',
  'location': '7248، 2415 سعود الفيصل، الصفا،، جدة 23451، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'بارق 63916، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '4.1 نجمة ',
  'location': 'H5V3+VV4، شارع شرق النهضه، السلامة، جدة 28383، المملكة العربية السعودية'},
 {'store_name': 'الماجد للعود',
  'rating': '4.4 نجمة ',
  'location': 'طريق الامير سلطان، النهضة، أبو عريش 84411، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'الحمراء، جدة 23323، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.5 نجمة ',
  'location': 'الطريق العام, حبونا 66342، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': '7337 الامير سلطان فرعي، حي المحمدية، جدة 23625 2115، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.4 نجمة ',
  'location': 'طريق الملك خالد بن عبدالعزيز،، الروضة، سراة عبيدة 64532، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.0 نجمة ',
  'location': '4608 طريق الملك عبدالعزيز، السد، أبها 62521، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.3 نجمة ',
  'location': '2645 8840 طريق الملك عبدالله، السليمانية، جدة 22253، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'CV77+4X، المرسلات، مكة 24243، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': '7599 الأمير ماجد، حي العزيزية، 2335، جدة 23342، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.6 نجمة ',
  'location': 'الملك عبد العزيز، القنفذة 28821، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'الملك عبدالله، بيشة 67712، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'Taibah District, جدة 23831، المملكة العربية السعودية'},
 {'store_name': '716 العربية للعود | Arabian Oud',
  'rating': '3.0 نجمة ',
  'location': 'العرق الجنوبي، خميس مشيط 62461، المملكة العربية السعودية'},
 {'store_name': '1224 العربية للعود | Arabian Oud',
  'rating': '4.0 نجمة ',
  'location': 'الراشد مول, طريق الملك فهد، البديع، أبها 12839، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.7 نجمة ',
  'location': 'طريق الملك فيصل، الفيصلية، محايل عسير 63687، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': '6326 طريق الامير متعب بن عبدالعزيز، 3578، حي مشرفة، جدة 23341، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'حي, شارع العزيزية العام، الجامعة، مكة 24243، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.0 نجمة ',
  'location': 'طريق الملك فهد بن عبدالعزيز، القنفذة 28822، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'شارع إبراهيم الجفالي، مكة 24372، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': '2F77+4GJ، الإمام محمد بن سعود، الحاوية، الباحة 65525، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'الخضراء، مكة 24267، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'شارع الملك سعود، الشرقية، الطائف 26513، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'المنار، جدة 23462، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.6 نجمة ',
  'location': 'الملك عبدالعزيز, النصباء 65581، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.7 نجمة ',
  'location': 'Batha Quraish, 9400, مكة 24361، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'طريق بدر، المجاردة 63971، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'قصر الضيافة، الزهراء، مكة 24221، المملكة العربية السعودية'},
 {'store_name': '498 العربية للعود | Arabian Oud',
  'rating': '4.0 نجمة ',
  'location': '8P4J+CX3، العرق الجنوبي، خميس مشيط 62461، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'شارع عبدالله سليمان، الفيحاء، جدة 22246، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': '2555, مخطط الموسى, خميس مشيط 62463، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '4.0 نجمة ',
  'location': 'السداد، الطائف 26514، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.5 نجمة ',
  'location': 'طريق الملك عبدالله، 3363 طريق الملك عبدالله، حي ابرق الرغامة، جدة 22261، 9059، جدة 22261، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'الجامعة، مكة 24243، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': '15، تنومة 62795، المملكة العربية السعودية'},
 {'store_name': '578 العربية للعود | Arabian Oud',
  'rating': '3.7 نجمة ',
  'location': 'الرونة، أحد رفيدة 62447، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'اسماعيل بن كثير، البساتين، جدة 23719، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.3 نجمة ',
  'location': 'المستشفى، بلجرشي 65635، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'الاجاويد، جدة 22442، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': '6306 Al Shouhadaa, الشهداء، 3576، مكة 24223، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': '3144، 7842، النزهة، الباحة 65711، المملكة العربية السعودية'},
 {'store_name': '705 العربية للعود | Arabian Oud',
  'rating': '4.1 نجمة ',
  'location': 'طريق الملك خالد، حي السحيلي،، فرع العربية للعود بشارع الملك خالد، شارع، الطائف المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '5.0 نجمة ',
  'location': '8452 جنوبا الى احد رفيده و شمالا الى خميس مشيط، سكن المدينة العسكرية، 3615، خميس مشيط 62413، المملكة العربية السعودية'},
 {'store_name': 'Oudelite - نخبة العود',
  'rating': '4.1 نجمة ',
  'location': 'شارع أسامة بن زيد، النهضة، أبو عريش 84714، المملكة العربية السعودية'},
 {'store_name': '923 العربية للعود | Arabian Oud',
  'rating': '3.9 نجمة ',
  'location': 'نجران 66252، المملكة العربية السعودية'},
 {'store_name': '1228 العربية للعود | Arabian Oud',
  'rating': '3.7 نجمة ',
  'location': '8772 البلد 13, حي السلام, AKPA3785، 3785, خميس مشيط 62461، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'HMJ6+XJ, 211، نمرة 65466، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': '3006 قريش، 6211، حي البوادي، جدة 23531، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.7 نجمة ',
  'location': 'الصيرفي مول، حي الفيصلية، الفيصلية، جدة 23441، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.5 نجمة ',
  'location': 'Ibrahim Al Khalil, St Abraj Al Bait 1، مكة 24231، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '4.1 نجمة ',
  'location': 'الطريق الساحلي الدولي - جده ،, جازان المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': '4020 شارع الامير سلطان، الخزامى، بيشة 67711، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.6 نجمة ',
  'location': 'طريق احمد بن عبدالعزيز، القوز 28829، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.7 نجمة ',
  'location': 'طريق الملك خالد، الخزامى، بيشة 67711، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': '3789، جدة 22434، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود والعطور',
  'rating': '3.6 نجمة ',
  'location': 'Q97H+M2، الصفة 28939، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'شارع الستين، الحوية، الطائف 26576، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'المنار، حي المنار، 3938, جدة 23463، المملكة العربية السعودية'},
 {'store_name': '1213 العربية للعود | Arabian Oud',
  'rating': '4.4 نجمة ',
  'location': 'NJUB7872، 7872 حمد ابن ماضي, 3844, حي أبا السعود, نجران 66281، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '5.0 نجمة ',
  'location': 'مدرسه الثغر، District، 5580 Ahmad Al Badawi، جدة 22338، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'طريق الملك فيصل، العدل، مكة 24244، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': '2167 محمد صالح باشراحيل، الراشدية، مكة 24268، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.1 نجمة ',
  'location': 'العقيق 65914، المملكة العربية السعودية'},
 {'store_name': '262 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': 'شارع حلي، الأزهار، القنفذة 28821، المملكة العربية السعودية'}]

In [662]:
alarabya_list_18=pickle.load(open('alarabya_pkl\\alarabya_arar.pkl','rb'))
alarabya_list_18 = [dictionary for dictionary in alarabya_list_18 if 'الإسكندرية' not in dictionary['location'] and 'القاهرة' not in dictionary['location']]
print(len(alarabya_list_18))

alarabya_list_18

62

[{'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'جوهرة، عرعر 73551، المملكة العربية السعودية'},
 {'store_name': '118 العربية للعود | Arabian Oud',
  'rating': '4.4 نجمة ',
  'location': 'العزيزية، عرعر 73311، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '4.0 نجمة ',
  'location': 'طريق الأمير ماجد بن عبدالعزيز، حي المباركية، عرعر 73551، المملكة العربية السعودية'},
 {'store_name': '596 العربية للعود | Arabian Oud',
  'rating': '2.3 نجمة ',
  'location': '6929 King Abdul Aziz Rd، حي المساعديه، عرعر 73311، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود Arabian Oud',
  'rating': '4.4 نجمة ',
  'location': 'Juhaina Sq Mall of Arabia, Unit No. H96, محافظة الجيزة 12573'},
 {'store_name': '548 العربية للعود | Arabian Oud',
  'rating': '4.2 نجمة ',
  'location': 'Sakakah Road Nayomi Al Jouf Plaza، سكاكا 72341، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.6 نجمة ',
  'location': 'المطر، 72341،، سكاكا المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'طريق الملك سعود، السوق القديم، تبوك، دومة الجندل 74632، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'طريق الملك عبدالعزيز، الحي الإداري، سكاكا 72341، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '5.0 نجمة ',
  'location': '88HV+C9P، الحميدية، القريات 77453، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'الجوف بلازا .. 6902 طريق الملك سعود سكاكا السعودية،، سكاكا المملكة العربية السعودية'},
 {'store_name': '51 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': 'برزان، حائل 55428، المملكة العربية السعودية'},
 {'store_name': 'دخون',
  'rating': '4.3 نجمة ',
  'location': 'Mall، عرعر 73551، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': '88PP+38F، السديرية، القريات 77481، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود |Arabian Oud',
  'rating': '4.4 نجمة ',
  'location': '3585، مروج الأمير، تبوك 47315، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'شارع الاندلس، طبرجل 74765، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'العزيزية، طريف 75211، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.5 نجمة ',
  'location': 'المكان مول، طريق الملك عبدالعزيز، النايفية، حفر الباطن 39811، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'طريق الملك عبدالله، الملز، رفحاء 76333، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': '4651، المنتزه الشرقي،، حائل 55428، المملكة العربية السعودية'},
 {'store_name': 'Arabian oud',
  'rating': '4.7 نجمة ',
  'location': 'MALL OF EGYPT, قسم أول 6 أكتوبر، محافظة الجيزة 3294001'},
 {'store_name': '57 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': '6459 باب الصفاقات، برزان، حائل 55428، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'المصيف، المروج،،, تبوك 47321، المملكة العربية السعودية'},
 {'store_name': '825 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': 'طريق الملك فيصل، الخالدية، القريات 77453، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'طريق فيصل بن عبدالعزيز، البلدية، حفر الباطن 39921، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'طريق عبدالعزيز بن مساعد، الادارية، رفحاء 76313، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.0 نجمة ',
  'location': 'المنتزه الغربي، حائل 55427، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'KGAB7336، 7336 خديجة بنت خويلد، 5635، الصفا، تبوك 47919، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '4.2 نجمة ',
  'location': '2791 أبو أيوب الأنصاري، بني خدرة، المدينة المنورة 42311 6233،، بني خدرة، 42311،، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'حي, الطريق العام, السويفلة، حائل 55481، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'النقرة، حائل 55431، المملكة العربية السعودية'},
 {'store_name': '58 العربية للعود | Arabian Oud',
  'rating': '4.0 نجمة ',
  'location': '7673 الامير سلطان بن عبدالعزيز، 3515، المطار، حائل 55421، المملكة العربية السعودية'},
 {'store_name': '706 العربية للعود | Arabian Oud',
  'rating': '4.0 نجمة ',
  'location': 'عمر بن الخطاب، العزيزية القديمة، تبوك 47912، المملكة العربية السعودية'},
 {'store_name': '129 العربية للعود | Arabian Oud',
  'rating': '3.9 نجمة ',
  'location': '3361 طيبة، العزيزية القديمة، تبوك 47912، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'طريق الملك عبدالعزيز، برزان، حائل 55428، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود Arabian Oud - شارع العراصات',
  'rating': '5.0 نجمة ',
  'location': 'Arasat St, Arasat Al-Hindiyah, Baghdad, Baghdad Governorate, العراق'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'طريق أنس ابن مالك، الصحافة، الرياض 13321، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'طريق عثمان بن عفان، الصفراء، بريدة 52381، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'العليا، تبوك 47911، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '4.1 نجمة ',
  'location': 'Mecca Mall, Abdullah Al Dawoud St 20، عمّان، الأردن'},
 {'store_name': 'العربية للعود بالشارع العام (Arabianoud Tabuk )',
  'rating': '4.4 نجمة ',
  'location': '3673 الامام محمد بن عبدالوهاب، المنشية القديمة، تبوك 47914، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.4 نجمة ',
  'location': 'علي بن ابي طالب، السعادة، تبوك 47914، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.4 نجمة ',
  'location': 'طريق الملك عبدالعزيز، الواحة، حفر الباطن 39913، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '4.4 نجمة ',
  'location': 'مخطط الرواف 5070, بريدة 52379، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '4.0 نجمة ',
  'location': 'الامير عبدالمجيد بن عبدالعزيز، المروج ب،، تبوك 47312، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'الزبارة، حائل 55425، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.3 نجمة ',
  'location': 'عمر بن الخطاب، الصالحية، تبوك 47913، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود Arabain Oud',
  'rating': '4.9 نجمة ',
  'location': 'الفهد، شارع السوق التجاري،، البكيرية 51941، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': '7011، عين ابن فهيد 52454، المملكة العربية السعودية'},
 {'store_name': '436 العربية للعود | Arabian Oud',
  'rating': '3.3 نجمة ',
  'location': '7619 ابي بكر الصديق، المروج،، تبوك 47312، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.4 نجمة ',
  'location': 'طريق الملك فهد، العليا، تبوك 47911، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'الصفراء، بريدة 52382، المملكة العربية السعودية'},
 {'store_name': '535 العربية للعود | Arabian Oud',
  'rating': '3.7 نجمة ',
  'location': 'King Fahd Bin Abdulaziz rd، الظهرة، حقل 49938، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'شارع عمر بن سليم، سلطانة، بريدة 52375، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود فرع 102',
  'rating': '3.9 نجمة ',
  'location': '3593 جادة الامير فهد بن سلطان،، العوايشة، تبوك 47914، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'طريق الملك عبدالله، الصفراء، بريدة 52383، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'الخالدية، حفر الباطن 39953، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.5 نجمة ',
  'location': 'طريق الملك فهد، سلطانة، تبوك 47312، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': '4049، النازية، بريدة 52359، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود Arabia Oud',
  'rating': '4.4 نجمة ',
  'location': 'GVP8+C47، إربد، الأردن'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'الإمام سعود بن عبد العزيز بن محمد، المغرزات، الرياض المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'طريق الملك عبدالله الفرعي، الحمراء، الرياض 13217، المملكة العربية السعودية'}]

In [663]:
alarabya_list_19=pickle.load(open('alarabya_pkl\\alarabya_taif.pkl','rb'))
alarabya_list_19 = [dictionary for dictionary in alarabya_list_19 if 'الإسكندرية' not in dictionary['location'] and 'القاهرة' not in dictionary['location']]
print(len(alarabya_list_19))

alarabya_list_19

119

[{'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'طريق الملك فهد فرعي، الربوة، جدة 23533، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'طريق الأمير محمد بن عبدالعزيز، الروضة، جدة 23431، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'الحمراء، جدة 23323، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': '8912 قاسم زينة، 4471 قاسم زينة، حي الروضة، جدة 23434، جدة 23434، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'شارع عبدالله سليمان، الفيحاء، جدة 22246، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': '7599 الأمير ماجد، حي العزيزية، 2335، جدة 23342، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'شارع عبدالله سليمان، الفيحاء، جدة 22246، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'ابو حذيفه بن عتبه، مدائن الفهد، جدة 22337، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': '6155 ابراهيم الخليل، الشوقية، مكة 24351، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': '3811 حراء, AZ Zahra District, جدة 23522، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'شارع إبراهيم الجفالي، مكة 24372، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': '7337 الامير سلطان فرعي، حي المحمدية، جدة 23625 2115، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': '6306 Al Shouhadaa, الشهداء، 3576، مكة 24223، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'Taibah District, جدة 23831، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'الحمدانية، جدة 23761، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'قاده الفكر، الرويس، جدة 23215، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.7 نجمة ',
  'location': 'الصيرفي مول، حي الفيصلية، الفيصلية، جدة 23441، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'اسماعيل بن كثير، البساتين، جدة 23719، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'CV77+4X، المرسلات، مكة 24243، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'ام القرى، الصفا، جدة 23453، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'شارع الشيخ محمد بن جبير، الشوقية، مكة 24351، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'Fruit Boat Sculpture, شارع حراء، النهضة، جدة 23523، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '4.2 نجمة ',
  'location': 'طريق الامير سلطان، الزهراء، جدة 23425، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'الجامعة، مكة 24243، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'سوق الشاطئ _ شارع أحمد العطاس _ حي الزهراء، الزهراء، جدة 23425، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': '3006 قريش، 6211، حي البوادي، جدة 23531، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.5 نجمة ',
  'location': 'طريق الملك عبدالله، 3363 طريق الملك عبدالله، حي ابرق الرغامة، جدة 22261، 9059، جدة 22261، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'CRW5+5M، طريق المدينة المنورة، الحجون، مكة 24237، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'المنار، جدة 23462، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'شارع عابر القرات، أبحر الشمالية، جدة 23815، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود - Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': 'F6RC+FC8، الفيحاء، جدة 22246، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.5 نجمة ',
  'location': 'Ibrahim Al Khalil, St Abraj Al Bait 1، مكة 24231، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'الاجاويد، جدة 22442، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'شارع أبي ذر الغفاري، حي النسيم 7280, جدة 23234، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.3 نجمة ',
  'location': '2645 8840 طريق الملك عبدالله، السليمانية، جدة 22253، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '3.6 نجمة ',
  'location': '7248، 2415 سعود الفيصل، الصفا،، جدة 23451، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'الخضراء، مكة 24267، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'المنار، حي المنار، 3938, جدة 23463، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.7 نجمة ',
  'location': 'شارع الحسين السهواجي، الربيع، جدة 23461، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود arabian oud',
  'rating': '3.5 نجمة ',
  'location': 'Al Marwah District، 3972 حراء،، جدة 23543، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'النوارية، مكة 24215، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'طريق الليث الفرعي، القرينية، جدة 22535، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'قصر الضيافة، الزهراء، مكة 24221، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.7 نجمة ',
  'location': 'Batha Quraish, 9400, مكة 24361، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.6 نجمة ',
  'location': 'النزهة، جدة 23532، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.4 نجمة ',
  'location': 'طريق الأمير سلطان، النهضة، جدة 23523، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': '3789، جدة 22434، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'شارع الملك سعود، الشرقية، الطائف 26513، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': '7906، الجامعة،، مكة 24242، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'الزاهر، مكة 24222، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'البهجه، مشرفة، جدة 23336، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.7 نجمة ',
  'location': 'طريق الامير متعب بن عبدالعزيز، الصفا، جدة 23451، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'الحمراء، الحمراء وأم الجود،، مكة 24321، المملكة العربية السعودية'},
 {'store_name': '698 العربية للعود | Arabian Oud',
  'rating': '4.3 نجمة ',
  'location': 'الحمدانية، جدة 23761، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود Arabian Oud',
  'rating': '4.9 نجمة ',
  'location': 'شارع الدكتور عبدالقادر كوشك، ولي العهد، مكة 24353، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.2 نجمة ',
  'location': 'شارع الأمير محمد بن عبدالعزيز، الرحاب، Jarir Mall،، جدة 23345، المملكة العربية السعودية'},
 {'store_name': '963 العربية للعود | Arabian Oud',
  'rating': '4.1 نجمة ',
  'location': 'الحمراء وأم الجود، مكة 24331، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'فازع، خليص 25542، المملكة العربية السعودية'},
 {'store_name': '674 العربية للعود | Arabian Oud',
  'rating': '4.1 نجمة ',
  'location': 'District, Madain Al Fahd, جدة 22347، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'الراشدية، مكة 24269، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': '5567 الشرائع الشمالية 7140، مكة 24432، المملكة العربية السعودية'},
 {'store_name': '683 العربية للعود | Arabian Oud',
  'rating': '4.7 نجمة ',
  'location': 'طريق الملك عبدالله، الفيحاء، جدة 22251، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': '8712 شارع القادسية، 3863, مكة 24268، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'طريق مكة القديم, القديمة، بحره 22826، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'البترجي فرعي، الزهراء، جدة 23521، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.4 نجمة ',
  'location': 'حي, شارع العزيزية العام، الجامعة، مكة 24243، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.2 نجمة ',
  'location': 'مطار الملك عبدالعزيز الدولي، جدة 23635، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'مطار الملك عبدالعزيز الدولي، جدة 23635، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.6 نجمة ',
  'location': 'شارع الخمسين، حي الجال، الطائف 26523، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': '3297، مكة 24416، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': '6326 طريق الامير متعب بن عبدالعزيز، 3578، حي مشرفة، جدة 23341، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.1 نجمة ',
  'location': 'الامير فواز الجنوبي، جدة 22431، المملكة العربية السعودية'},
 {'store_name': '646 العربية للعود | Arabian Oud',
  'rating': '3.8 نجمة ',
  'location': '6793، Al Marwah District، جدة 23545، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'طريق الملك فيصل، العدل، مكة 24244، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود | Arabian Oud',
  'rating': '4.4 نجمة ',
  'location': 'طريق الليث، ولي العهد، مكة 24567، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': '2167 محمد صالح باشراحيل، الراشدية، مكة 24268، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '5.0 نجمة ',
  'location': 'مدرسه الثغر، District، 5580 Ahmad Al Badawi، جدة 22338، المملكة العربية السعودية'},
 {'store_name': '1217 العربية للعود | Arabian Oud',
  'rating': '4.5 نجمة ',
  'location': '7358، 5431 عبد الرحمن الناصر، الأصالة، جدة 23738، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '4.1 نجمة ',
  'location': 'H5V3+VV4، شارع شرق النهضه، السلامة، جدة 28383، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود حراء الفحص',
  'rating': '3.6 نجمة ',
  'location': 'المروة، جدة 23541، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.6 نجمة ',
  'location': '7400 شارع القمرية، القطبية، الطائف 26523، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '3.7 نجمة ',
  'location': 'حي, طريق المدينة المنورة، النعيم، جدة 23526، المملكة العربية السعودية'},
 {'store_name': '1231 العربية للعود | Arabian Oud',
  'rating': '4.5 نجمة ',
  'location': 'الحمراء، جدة 23324، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'حمد الجاسر، الروضة، جدة 23434، المملكة العربية السعودية'},
 {'store_name': '705 العربية للعود | Arabian Oud',
  'rating': '4.1 نجمة ',
  'location': 'طريق الملك خالد، حي السحيلي،، فرع العربية للعود بشارع الملك خالد، شارع، الطائف المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': '5026 الشيخ عبدالله القرعاوي، الملك فهد, 6510، مكة 24341، المملكة العربية السعودية'},
 {'store_name': '624 العربية للعود | Arabian Oud',
  'rating': '3.4 نجمة ',
  'location': 'الحمدانية، جدة 23761، المملكة العربية السعودية'},
 {'store_name': '662 العربية للعود | Arabian Oud',
  'rating': '2.9 نجمة ',
  'location': '3749 صقر قريش، As Salamah District، جدة 23436، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'المحاميد 22393، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود Arabian Oud',
  'rating': '3.8 نجمة ',
  'location': '6248 طريق الليث، ولي العهد، مكة 24356، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود الحمدانيه',
  'rating': '4.6 نجمة ',
  'location': 'حي, JGAA4079, 8462 عمرو بن ابي وقاص(رضي الله عن، الحمدانية، 4079, جدة 23761، المملكة العربية السعودية'},
 {'store_name': '224 العربية للعود | Arabian Oud',
  'rating': '3.9 نجمة ',
  'location': '7871 طريق الامير سلطان، 2647, An Naim District, جدة 23621، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud العربية للعود',
  'rating': '4.5 نجمة ',
  'location': 'FQGR+GRF، مكة 24227، المملكة العربية السعودية'},
 {'store_name': '291 العربية للعود | Arabian Oud',
  'rating': '3.6 نجمة ',
  'location': 'شارع الأجواد، المنار، جدة 23462، المملكة العربية السعودية'},
 {'store_name': '358 العربية للعود | Arabian Oud',
  'rating': '3.1 نجمة ',
  'location': '8276 الأمير ماجد، الفيصلية، جدة 23447، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '5.0 نجمة ',
  'location': 'الواسيط, الطائف 26577، المملكة العربية السعودية'},
 {'store_name': '982 العربية للعود | Arabian Oud',
  'rating': '4.6 نجمة ',
  'location': '7425 قصر الضيافة، الزهراء، مكة 24221، المملكة العربية السعودية'},
 {'store_name': '212 العربية للعود | Arabian Oud',
  'rating': '3.6 نجمة ',
  'location': 'البوادي، جدة 23443، المملكة العربية السعودية'},
 {'store_name': '726 العربية للعود | Arabian Oud',
  'rating': '4.0 نجمة ',
  'location': '3413 شارع الحجون، الحجون، مكة 24231، المملكة العربية السعودية'},
 {'store_name': '220 العربية للعود | Arabian Oud',
  'rating': '4.8 نجمة ',
  'location': 'سوق الحجاز، طريق مكة جدة السريع، النزهة، مكة 24225، المملكة العربية السعودية'},
 {'store_name': '220 العربية للعود | Arabian Oud',
  'rating': '4.8 نجمة ',
  'location': 'سوق الحجاز، طريق مكة جدة السريع، النزهة، مكة 24225، المملكة العربية السعودية'},
 {'store_name': 'Arabian oud العربية للعود 1273',
  'rating': '5.0 نجمة ',
  'location': '9QHV+JV3، الشوقية، مكة 24351، المملكة العربية السعودية'},
 {'store_name': '228 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': 'البهجه، مشرفة، جدة 23336، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '2.7 نجمة ',
  'location': 'المنصور، مكة 24231، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '4.0 نجمة ',
  'location': 'السداد، الطائف 26514، المملكة العربية السعودية'},
 {'store_name': 'الإدارة الإقليمية لشركة العربية للعود بمكة',
  'rating': '4.4 نجمة ',
  'location': 'طريق مكة جدة القديم، النزهة، مكة 24225، المملكة العربية السعودية'},
 {'store_name': 'Arabian Oud',
  'rating': '4.6 نجمة ',
  'location': 'الهجلة، مكة 24231، المملكة العربية السعودية'},
 {'store_name': '992 العربية للعود | Arabian Oud',
  'rating': '5.0 نجمة ',
  'location': 'حي الخضراء, MEKA4495، 4495 شارع الحدرجان بن مالك الأزدي، 8592, مكة 24263، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'شارع عمر بن الخطاب, حي الوسام، الطائف 26711، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.0 نجمة ',
  'location': 'شارع الستين، الحوية، الطائف 26576، المملكة العربية السعودية'},
 {'store_name': '949 العربية للعود | Arabian Oud',
  'rating': '4.2 نجمة ',
  'location': 'الفيصلية، الجموم 25335، المملكة العربية السعودية'},
 {'store_name': '258 العربية للعود | Arabian Oud',
  'rating': '3.7 نجمة ',
  'location': '3923 ابراهيم الخليل، الهجلة، 7089 ابراهيم الخليل،، مكة 24231، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود Arabia Oud',
  'rating': '4.4 نجمة ',
  'location': 'JDSA8673، 8673 ام القرى، 4142، حي الصفا،، جدة 23456، المملكة العربية السعودية'},
 {'store_name': 'العربيه للعود',
  'rating': '4.2 نجمة ',
  'location': 'طريق الجنوب الباحه - السر، الطائف 26738، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.9 نجمة ',
  'location': 'طريق المطار، الحوية، الطائف 26576، المملكة العربية السعودية'},
 {'store_name': '907 العربية للعود | Arabian Oud',
  'rating': '4.3 نجمة ',
  'location': 'فرع العربية للعود بالحلقة الشرقية، حي الحلقة الشرقية شارع العام،، الطائف المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.1 نجمة ',
  'location': '3952، 6873 حي، مريخ، جدة 23361، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '3.8 نجمة ',
  'location': 'الحوية، الطائف 26411، المملكة العربية السعودية'},
 {'store_name': 'العربية للعود',
  'rating': '4.3 نجمة ',
  'location': 'حي القيم الأعلى، الطائف 26561، المملكة العربية السعودية'}]

In [664]:
all_alarabya_stores=[*alarabya_list,*alarabya_list_1,*alarabya_list_2,*alarabya_list_3,*alarabya_list_4,*alarabya_list_5,\
                     *alarabya_list_7,*alarabya_list_8,*alarabya_list_9,*alarabya_list_10,*alarabya_list_11,*alarabya_list_12,*alarabya_list_13,\
                     *alarabya_list_14,*alarabya_list_15,*alarabya_list_16,*alarabya_list_17,*alarabya_list_18,*alarabya_list_19
                    ]
print(len(all_alarabya_stores))

1919

In [665]:
stores_names=[]
locations=[]
ratings=[]
for dictionary in all_alarabya_stores:
        stores_names.append(dictionary['store_name']) if dictionary['store_name'] else ' '
        locations.append(dictionary['location']) if dictionary['location'] else ' '
        ratings.append(dictionary['rating']) if dictionary['rating'] else ' '

In [666]:
len(stores_names),len(locations),len(ratings)

(1919, 1919, 1919)

In [667]:
import pandas as pd 
alarabia_stores_df=pd.DataFrame({'store_name':stores_names,'location':locations,'rating':ratings})
# تنظيف البيانات قبل دمجها
alarabia_stores_df['store_name'] = alarabia_stores_df['store_name'].str.strip().str.lower()
alarabia_stores_df['location'] = alarabia_stores_df['location'].str.strip().str.lower()
alarabia_stores_df['rating']=alarabia_stores_df['rating'].apply(lambda x : x.replace('نجمة','').strip())
alarabia_stores_df['rating']=alarabia_stores_df['rating'].astype('float16')
alarabia_stores_df['rating']=alarabia_stores_df['rating'].apply(lambda x : round(x,1))
import re
import warnings 
warnings.filterwarnings('ignore')
# List of unwanted store names
unwanted_names = ['الدخيل للعود', 'الماجد للعود', 'درعه DERAAH', 'السامر للعود', 
                  'محمود للعود', 'Abdul Samad Al Qurashi', 'Dkhoun | دخون', 
                  'OudElite - نخبة العود 7345', 'عطور رسيس | Rasees perfumes', 
                  'Almajed For Oud', 'نخبة العود','دخون']

# Join unwanted names into a single regex pattern
unwanted_pattern = '|'.join(map(re.escape, unwanted_names))

# Iterate over the DataFrame and drop rows where the store name matches any unwanted name
for index, row in alarabia_stores_df.iterrows():
    store_name = row['store_name']  # Replace with your actual column name for store names
    if re.search(unwanted_pattern, store_name):
        alarabia_stores_df.drop(index, inplace=True)

# Alternatively, you can achieve the same in a vectorized way:
alarabia_stores_df = alarabia_stores_df[~alarabia_stores_df['store_name'].str.contains(unwanted_pattern, regex=True)]

alarabia_stores_df

,store_name,location,rating
0,العربية للعود |arabian oud,3585، مروج الأمير، تبوك 47315، المملكة العربية...,4.4
1,العربية للعود,طريق الملك فهد، سلطانة، تبوك 47312، المملكة ال...,4.5
2,العربية للعود,العليا، تبوك 47911، المملكة العربية السعودية,3.9
3,العربيه للعود,الامير عبدالمجيد بن عبدالعزيز، المروج ب،، تبوك...,4.0
4,العربية للعود,علي بن ابي طالب، السعادة، تبوك 47914، المملكة ...,3.4
...,...,...,...
1914,العربية للعود,طريق المطار، الحوية، الطائف 26576، المملكة الع...,3.9
1915,907 العربية للعود | arabian oud,فرع العربية للعود بالحلقة الشرقية، حي الحلقة ا...,4.3
1916,العربية للعود,3952، 6873 حي، مريخ، جدة 23361، المملكة العربي...,3.1
1917,العربية للعود,الحوية، الطائف 26411، المملكة العربية السعودية,3.8
1918,العربية للعود,حي القيم الأعلى، الطائف 26561، المملكة العربية...,4.3

In [668]:
alarabia_stores_df.duplicated().sum()

1272

In [669]:
alarabia_stores_df=alarabia_stores_df.drop_duplicates() 
print(len(alarabia_stores_df))

602

In [670]:
alarabia_stores_df['rating'].unique()

array([4.4, 4.5, 3.9, 4. , 3.4, 3.3, 5. , 4.2, 4.7, 4.1, 3.7, 3.6, 3.8,
       4.3, 3. , 1. , 2. , 4.9, 3.2, 1.9, 4.6, 4.8, 3.1, 3.5, 2.7, 2.9,
       2.3, 2.8])

In [671]:

# alarabia_stores_df.iloc[870,:]

In [672]:
alarabia_stores_df['rating'].unique()

array([4.4, 4.5, 3.9, 4. , 3.4, 3.3, 5. , 4.2, 4.7, 4.1, 3.7, 3.6, 3.8,
       4.3, 3. , 1. , 2. , 4.9, 3.2, 1.9, 4.6, 4.8, 3.1, 3.5, 2.7, 2.9,
       2.3, 2.8])

In [673]:
alarabia_stores_df.isnull().sum()

store_name    0
location      0
rating        0
dtype: int64

In [674]:

alarabia_stores_df.dtypes

store_name     object
location       object
rating        float64
dtype: object

In [675]:
# 589

In [676]:
len(alarabia_stores_df)

602

In [677]:
alarabia_stores_df.to_csv('alarabia_oud_stores.csv',index=False)

In [678]:
os.listdir()

['.ipynb_checkpoints',
 'alarabia_oud_stores.csv',
 'alarabia_oud_stores_1.csv',
 'alarabya',
 'alarabya_oud.xlsx',
 'ksa_perfume_stores.ipynb',
 'main.py']

In [679]:
df_1=pd.read_excel('alarabya_oud.xlsx')
df_1

,store_name,location,rating
0,العربية للعود |Arabian Oud,3585، مروج الأمير، تبوك 47315، المملكة العربية...,4.4
1,العربية للعود,طريق الملك فهد، سلطانة، تبوك 47312، المملكة ال...,4.5
2,العربية للعود,العليا، تبوك 47911، المملكة العربية السعودية,3.9
3,العربيه للعود,الامير عبدالمجيد بن عبدالعزيز، المروج ب،، تبوك...,4.0
4,العربية للعود,علي بن ابي طالب، السعادة، تبوك 47914، المملكة ...,3.4
...,...,...,...
728,العربية للعود,فازع، خليص 25542، المملكة العربية السعودية,3.7
729,العربية للعود,"المنار، حي المنار، 3938, جدة 23463، المملكة ال...",3.7
730,264 العربية للعود | Arabian Oud,"TADC2314، 2314 سعد بن بخيت, حي شبرا, 7070, الط...",3.7
731,العربية للعود,شارع الحسين السهواجي، الربيع، جدة 23461، الممل...,3.7
732,العربية للعود,اسماعيل بن كثير، البساتين، جدة 23719، المملكة ...,3.7

In [680]:
df_1.duplicated().sum()

8

In [681]:
all_df=pd.concat([alarabia_stores_df,df_1],axis=0)
all_df.duplicated().sum()

357

In [682]:
df_1

,store_name,location,rating
0,العربية للعود |Arabian Oud,3585، مروج الأمير، تبوك 47315، المملكة العربية...,4.4
1,العربية للعود,طريق الملك فهد، سلطانة، تبوك 47312، المملكة ال...,4.5
2,العربية للعود,العليا، تبوك 47911، المملكة العربية السعودية,3.9
3,العربيه للعود,الامير عبدالمجيد بن عبدالعزيز، المروج ب،، تبوك...,4.0
4,العربية للعود,علي بن ابي طالب، السعادة، تبوك 47914، المملكة ...,3.4
...,...,...,...
728,العربية للعود,فازع، خليص 25542، المملكة العربية السعودية,3.7
729,العربية للعود,"المنار، حي المنار، 3938, جدة 23463، المملكة ال...",3.7
730,264 العربية للعود | Arabian Oud,"TADC2314، 2314 سعد بن بخيت, حي شبرا, 7070, الط...",3.7
731,العربية للعود,شارع الحسين السهواجي، الربيع، جدة 23461، الممل...,3.7
732,العربية للعود,اسماعيل بن كثير، البساتين، جدة 23719، المملكة ...,3.7

In [683]:
# 964

In [684]:
all_df.drop_duplicates(inplace=True)
len(all_df)

978

In [685]:
# 679

In [688]:
all_df=all_df[all_df['store_name'].str.contains('العربية للعود|العربيه للعود|arabian oud|Arabian Oud',regex=True)]
all_df.drop_duplicates(subset=['location','rating'])

,store_name,location,rating
0,العربية للعود |arabian oud,3585، مروج الأمير، تبوك 47315، المملكة العربية...,4.4
1,العربية للعود,طريق الملك فهد، سلطانة، تبوك 47312، المملكة ال...,4.5
2,العربية للعود,العليا، تبوك 47911، المملكة العربية السعودية,3.9
3,العربيه للعود,الامير عبدالمجيد بن عبدالعزيز، المروج ب،، تبوك...,4.0
4,العربية للعود,علي بن ابي طالب، السعادة، تبوك 47914، المملكة ...,3.4
...,...,...,...
727,674 العربية للعود | Arabian Oud,"District, Madain Al Fahd, جدة 22347، المملكة ا...",3.7
728,العربية للعود,فازع، خليص 25542، المملكة العربية السعودية,3.7
729,العربية للعود,"المنار، حي المنار، 3938, جدة 23463، المملكة ال...",3.7
730,264 العربية للعود | Arabian Oud,"TADC2314، 2314 سعد بن بخيت, حي شبرا, 7070, الط...",3.7
732,العربية للعود,اسماعيل بن كثير، البساتين، جدة 23719، المملكة ...,3.7

In [689]:
all_df.drop_duplicates(subset=['location','rating']).to_csv('alarabia_oud_stores_1.csv',index=False)